import type Stripe from 'stripe'
import { getCloudflareSql } from '@/data/neon-cloudflare'
import { stripe } from '@/lib/stripe'
import { isMockMode } from '@/lib/mocks'
import { COMMERCIAL_PLAN_VERSION } from '@/modules/store/domain/merchant-commercial-plans'
import { addDays, commercialStatusForSubscription, type MerchantBillablePlanCode, type MerchantRecurringPlanCode } from '../domain/merchant-billing'
import { MERCHANT_BILLING_PROVIDER, MerchantBillingError, assertMerchantStripeEnvironment, isMerchantBillingMetadata, merchantStripePriceForPlan, metadataRecord, resolveMerchantStripePrice, stripeId, unixDate } from './merchant-billing-shared'

type Account = { id: string; merchantId: string; provider: string; stripeCustomerId: string; stripeSubscriptionId: string | null; stripePriceId: string | null; stripeCheckoutSessionId: string | null; subscriptionStatus: string | null; cancelAtPeriodEnd: boolean; currentPeriodStart: Date | null; currentPeriodEnd: Date | null; lastEventCreatedAt: number | null; lastEventId: string | null }
const accountSelect = `"id", "merchantId", "provider", "stripeCustomerId", "stripeSubscriptionId", "stripePriceId", "stripeCheckoutSessionId", "subscriptionStatus", "cancelAtPeriodEnd", "currentPeriodStart", "currentPeriodEnd", "lastEventCreatedAt", "lastEventId"`
const sqlClient = () => getCloudflareSql() as any
function account(row: Record<string, unknown>): Account { return { id: String(row.id), merchantId: String(row.merchantId), provider: String(row.provider), stripeCustomerId: String(row.stripeCustomerId), stripeSubscriptionId: row.stripeSubscriptionId == null ? null : String(row.stripeSubscriptionId), stripePriceId: row.stripePriceId == null ? null : String(row.stripePriceId), stripeCheckoutSessionId: row.stripeCheckoutSessionId == null ? null : String(row.stripeCheckoutSessionId), subscriptionStatus: row.subscriptionStatus == null ? null : String(row.subscriptionStatus), cancelAtPeriodEnd: Boolean(row.cancelAtPeriodEnd), currentPeriodStart: row.currentPeriodStart == null ? null : new Date(String(row.currentPeriodStart)), currentPeriodEnd: row.currentPeriodEnd == null ? null : new Date(String(row.currentPeriodEnd)), lastEventCreatedAt: row.lastEventCreatedAt == null ? null : Number(row.lastEventCreatedAt), lastEventId: row.lastEventId == null ? null : String(row.lastEventId) } }
function id(prefix: string) { return `${prefix}_${globalThis.crypto?.randomUUID?.() ?? `${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`}` }
function mask(value: string | null) { return value ? `${value.slice(0, 4)}••••${value.slice(-4)}` : null }
async function findAccount(merchantId: string) { const sql = sqlClient(); const rows = await sql`SELECT ${sql.unsafe(accountSelect)} FROM "MerchantBillingAccount" WHERE "merchantId" = ${merchantId} AND "provider" = ${MERCHANT_BILLING_PROVIDER} LIMIT 1`; return rows[0] ? account(rows[0]) : null }

async function ensureAccount(merchantId: string, name: string) {
  const existing = await findAccount(merchantId); if (existing) return existing
  const client = stripe as any
  const customer = isMockMode && !client.customers?.create ? { id: `cus_mock_merchant_${merchantId}` } : await client.customers.create({ name, metadata: { merchantId, billingPurpose: 'MERCHANT_PLAN' } }, { idempotencyKey: `merchant-customer:${merchantId}` })
  const sql = sqlClient()
  await sql`INSERT INTO "MerchantBillingAccount" ("id", "merchantId", "provider", "stripeCustomerId", "createdAt", "updatedAt") VALUES (${id('mba')}, ${merchantId}, ${MERCHANT_BILLING_PROVIDER}, ${customer.id}, NOW(), NOW()) ON CONFLICT ("merchantId", "provider") DO NOTHING`
  const result = await findAccount(merchantId); if (!result) throw new MerchantBillingError('BILLING_IDENTITY_NOT_FOUND', 'Merchant billing identity was not created.', 409); return result
}

export async function getMerchantBillingSummary(input: { merchantId: string }) { const result = await findAccount(input.merchantId); return result ? { ...result, maskedCustomerId: mask(result.stripeCustomerId), maskedSubscriptionId: mask(result.stripeSubscriptionId) } : null }
function metadata(merchantId: string, planCode: MerchantBillablePlanCode, priceId: string) { return { billingPurpose: 'MERCHANT_PLAN', merchantId, requestedPlanCode: planCode, stripePriceId: priceId, pricingVersion: COMMERCIAL_PLAN_VERSION, entitlementVersion: COMMERCIAL_PLAN_VERSION } }

export async function createMerchantCheckoutSession(input: { merchantId: string; planCode: MerchantBillablePlanCode; successUrl: string; cancelUrl: string }) {
  assertMerchantStripeEnvironment(); const price = merchantStripePriceForPlan(input.planCode); const sql = sqlClient(); const merchants = await sql`SELECT "id", "name" FROM "Merchant" WHERE "id" = ${input.merchantId} LIMIT 1`
  const merchant = merchants[0]; if (!merchant) throw new MerchantBillingError('MERCHANT_NOT_FOUND', 'Merchant not found.', 404); const billingAccount = await ensureAccount(input.merchantId, String(merchant.name))
  if (price.billingType === 'subscription' && billingAccount.stripeSubscriptionId && ['active', 'trialing', 'past_due', 'unpaid'].includes(billingAccount.subscriptionStatus ?? '')) throw new MerchantBillingError('SUBSCRIPTION_EXISTS', 'This Merchant already has a billing plan. Use Manage plan to change it.', 409)
  const session = await (stripe as any).checkout.sessions.create({ mode: price.billingType === 'subscription' ? 'subscription' : 'payment', customer: billingAccount.stripeCustomerId, line_items: [{ price: price.priceId, quantity: 1 }], success_url: input.successUrl, cancel_url: input.cancelUrl, client_reference_id: input.merchantId, metadata: metadata(input.merchantId, price.planCode, price.priceId), ...(price.billingType === 'subscription' ? { subscription_data: { metadata: metadata(input.merchantId, price.planCode, price.priceId) } } : {}) }, { idempotencyKey: `merchant-checkout:${input.merchantId}:${price.planCode}:${billingAccount.stripeCheckoutSessionId ?? 'new'}` })
  return { kind: 'checkout' as const, sessionId: String(session.id), url: session.url == null ? null : String(session.url), planCode: price.planCode, priceId: price.priceId }
}

export async function updateMerchantSubscription(input: { merchantId: string; planCode: MerchantRecurringPlanCode }) {
  assertMerchantStripeEnvironment(); const price = merchantStripePriceForPlan(input.planCode); const billingAccount = await findAccount(input.merchantId); if (!billingAccount?.stripeSubscriptionId) throw new MerchantBillingError('SUBSCRIPTION_NOT_FOUND', 'No active Merchant subscription was found.', 404); const subscription = await (stripe as any).subscriptions.retrieve(billingAccount.stripeSubscriptionId); if (stripeId(subscription.customer) !== billingAccount.stripeCustomerId) throw new MerchantBillingError('BILLING_IDENTITY_MISMATCH', 'The billing identity does not belong to this Merchant.', 409); const item = subscription.items?.data?.[0]; if (!item?.id) throw new MerchantBillingError('SUBSCRIPTION_NOT_SUPPORTED', 'This subscription cannot be changed automatically.', 409); await (stripe as any).subscriptions.update(billingAccount.stripeSubscriptionId, { items: [{ id: item.id, price: price.priceId }], proration_behavior: 'create_prorations', metadata: metadata(input.merchantId, price.planCode, price.priceId) }); return { kind: 'subscription_update' as const, subscriptionId: billingAccount.stripeSubscriptionId, planCode: input.planCode, priceId: price.priceId }
}

export async function createMerchantBillingPortalSession(input: { merchantId: string; returnUrl: string }) { assertMerchantStripeEnvironment(); const billingAccount = await findAccount(input.merchantId); if (!billingAccount?.stripeSubscriptionId) throw new MerchantBillingError('SUBSCRIPTION_NOT_FOUND', 'No active Merchant subscription was found.', 404); const portal = await (stripe as any).billingPortal.sessions.create({ customer: billingAccount.stripeCustomerId, return_url: input.returnUrl }); return { url: String(portal.url) } }

async function findAccountForEvent(event: Stripe.Event) { const object = event.data.object as Record<string, unknown>; const meta = metadataRecord(object.metadata); const customer = stripeId(object.customer as string | { id: string } | null | undefined); const subscription = stripeId(object.subscription as string | { id: string } | null | undefined) ?? (event.type.startsWith('customer.subscription.') ? String(object.id ?? '') : null); const sql = sqlClient(); const rows = meta.merchantId ? await sql`SELECT ${sql.unsafe(accountSelect)} FROM "MerchantBillingAccount" WHERE "merchantId" = ${meta.merchantId} AND "provider" = ${MERCHANT_BILLING_PROVIDER} LIMIT 1` : subscription ? await sql`SELECT ${sql.unsafe(accountSelect)} FROM "MerchantBillingAccount" WHERE "stripeSubscriptionId" = ${subscription} LIMIT 1` : customer ? await sql`SELECT ${sql.unsafe(accountSelect)} FROM "MerchantBillingAccount" WHERE "stripeCustomerId" = ${customer} LIMIT 1` : []; return rows[0] ? account(rows[0]) : null }
function subPrice(value: Record<string, unknown>) { const items = (value.items as { data?: Array<Record<string, unknown>> } | undefined)?.data ?? []; return stripeId(items[0]?.price as string | { id: string } | null | undefined) }
function subPeriod(value: Record<string, unknown>, fallback: Date) { return { start: unixDate(value.current_period_start) ?? fallback, end: unixDate(value.current_period_end) } }
async function retrieveSubscription(value: string) { try { return await (stripe as any).subscriptions.retrieve(value) as Record<string, unknown> } catch { return null } }
const supported = new Set(['checkout.session.completed', 'checkout.session.async_payment_succeeded', 'customer.subscription.created', 'customer.subscription.updated', 'customer.subscription.deleted', 'invoice.paid', 'invoice.payment_succeeded', 'invoice.payment_failed'])
export function isMerchantStripeEventCandidate(event: Stripe.Event) { return supported.has(event.type) && isMerchantBillingMetadata((event.data.object as Record<string, unknown>).metadata) }

export async function processMerchantStripeEvent(event: Stripe.Event): Promise<{ handled: boolean; duplicate: boolean; merchantId?: string; eventType?: string }> {
  if (!supported.has(event.type)) return { handled: false, duplicate: false }
  const object = event.data.object as Record<string, unknown>; if (!isMerchantBillingMetadata(object.metadata) && !event.type.startsWith('invoice.')) return { handled: false, duplicate: false }; const billingAccount = await findAccountForEvent(event); if (!billingAccount) return { handled: false, duplicate: false }
  const customer = stripeId(object.customer as string | { id: string } | null | undefined); if (customer && customer !== billingAccount.stripeCustomerId) throw new MerchantBillingError('BILLING_IDENTITY_MISMATCH', 'Stripe billing identity does not match this Merchant.', 409)
  const subscriptionId = stripeId(object.subscription as string | { id: string } | null | undefined) ?? billingAccount.stripeSubscriptionId; const subscription = event.type.startsWith('customer.subscription.') ? object : subscriptionId ? await retrieveSubscription(subscriptionId) : null; const priceId = subscription ? subPrice(subscription) ?? billingAccount.stripePriceId : billingAccount.stripePriceId; if (!priceId) throw new MerchantBillingError('SUBSCRIPTION_PRICE_MISSING', 'Stripe billing price is missing.', 409); const price = resolveMerchantStripePrice(priceId); const start = subscription ? subPeriod(subscription, new Date(event.created * 1000)).start : billingAccount.currentPeriodStart ?? new Date(event.created * 1000); const endFromStripe = subscription ? subPeriod(subscription, new Date(event.created * 1000)).end : billingAccount.currentPeriodEnd; const rawStatus = subscription ? String(subscription.status ?? 'active') : event.type === 'invoice.payment_failed' ? 'past_due' : 'active'; const cancelAtPeriodEnd = Boolean(subscription?.cancel_at_period_end); const status = event.type === 'customer.subscription.deleted' ? 'EXPIRED' : price.billingType === 'one_time' ? 'PILOT_ACTIVE' : commercialStatusForSubscription({ status: rawStatus, cancelAtPeriodEnd }); const periodEnd = price.billingType === 'one_time' ? addDays(start, 30) : endFromStripe; const sql = sqlClient(); const alreadyProcessed = billingAccount.lastEventId === event.id
  const statements: any[] = [sql`SELECT "id" FROM "MerchantBillingAccount" WHERE "id" = ${billingAccount.id} FOR UPDATE`]
  statements.push(sql`UPDATE "MerchantBillingAccount" SET "stripeSubscriptionId" = ${event.type === 'customer.subscription.deleted' ? null : subscriptionId}, "stripePriceId" = ${price.priceId}, "stripeCheckoutSessionId" = ${event.type.startsWith('checkout.session.') ? String(object.id ?? '') : billingAccount.stripeCheckoutSessionId}, "subscriptionStatus" = ${price.billingType === 'one_time' ? 'paid' : event.type === 'customer.subscription.deleted' ? 'canceled' : rawStatus}, "cancelAtPeriodEnd" = ${cancelAtPeriodEnd}, "currentPeriodStart" = ${start}, "currentPeriodEnd" = ${periodEnd}, "lastEventCreatedAt" = ${event.created}, "lastEventId" = ${event.id}, "updatedAt" = NOW() WHERE "id" = ${billingAccount.id} AND ("lastEventCreatedAt" IS NULL OR "lastEventCreatedAt" <= ${event.created}) AND NOT EXISTS (SELECT 1 FROM "MerchantBillingEvent" WHERE "provider" = ${MERCHANT_BILLING_PROVIDER} AND "providerEventId" = ${event.id})`)
  statements.push(sql`UPDATE "Merchant" SET "planCode" = ${price.planCode}, "commercialStatus" = ${status}, "pricingVersion" = ${COMMERCIAL_PLAN_VERSION}, "entitlementVersion" = ${COMMERCIAL_PLAN_VERSION}, "entitlementEffectiveFrom" = ${start}, "billingPeriodEnd" = ${periodEnd}, "commercialStage" = ${price.planCode === 'FOUNDING_PILOT' ? 'MARKET_CAPTURE' : null}, "updatedAt" = NOW() WHERE "id" = ${billingAccount.merchantId} AND NOT EXISTS (SELECT 1 FROM "MerchantBillingEvent" WHERE "provider" = ${MERCHANT_BILLING_PROVIDER} AND "providerEventId" = ${event.id})`)
  statements.push(sql`INSERT INTO "MerchantBillingEvent" ("id", "provider", "providerEventId", "merchantId", "billingAccountId", "eventType", "stripeCustomerId", "stripeSubscriptionId", "eventCreatedAt", "status", "processedAt", "createdAt") VALUES (${id('mbe')}, ${MERCHANT_BILLING_PROVIDER}, ${event.id}, ${billingAccount.merchantId}, ${billingAccount.id}, ${event.type}, ${customer}, ${subscriptionId}, ${event.created}, 'PROCESSED', NOW(), NOW()) ON CONFLICT ("provider", "providerEventId") DO NOTHING`)
  await sql.transaction(statements, { isolationLevel: 'Serializable' }); return { handled: true, duplicate: alreadyProcessed, merchantId: billingAccount.merchantId, eventType: event.type }
}

export { MERCHANT_BILLING_PROVIDER, MerchantBillingError, assertMerchantStripeEnvironment, merchantStripePriceForPlan, resolveMerchantStripePrice }
