import { defaultLocale, isValidLocale, type Locale } from '@/i18n'

export type FaceShapeDetectorUiCopy = {
  toolLabel: string
  uploadTitle: string
  resultTitle: string
  privacyText: string
  startOver: string
  choosePhoto: string
  fileHint: string
  photoHint: string
  analyzingTitle: string
  analyzingText: string
  errorTitle: string
  errorHint: string
  featuresTitle: string
  features: readonly string[]
  disclaimer: string
}

const copies: Record<Locale, FaceShapeDetectorUiCopy> = {
  en: { toolLabel: 'Free on-device tool', uploadTitle: 'Upload one straight-on photo', resultTitle: 'Your measured face-shape result', privacyText: 'Your photo and raw landmarks stay in this browser. This tool does not upload or store them.', startOver: 'Start over', choosePhoto: 'Choose a face photo', fileHint: 'JPG, PNG, or WebP · up to 10 MB', photoHint: 'One face, neutral expression, hair away from the outline', analyzingTitle: 'Mapping facial landmarks on your device', analyzingText: 'The first run may take a moment while the browser loads the model.', errorTitle: 'Try another photo', errorHint: 'Use one centered face, level eyes, even lighting, and a visible forehead and jaw.', featuresTitle: 'What this free result includes', features: ['A likely result across seven face-shape categories', 'A live landmark mesh drawn over your photo', 'Six visualized geometry and alignment details', 'Quality checks for multiple faces, tilt, and face size'], disclaimer: 'This is a styling estimate, not identity recognition, medical advice, or a physical frame-size measurement. Your selected image remains in browser memory.' },
  fr: { toolLabel: 'Outil gratuit sur votre appareil', uploadTitle: 'Importez une photo de face', resultTitle: 'Résultat mesuré de votre forme de visage', privacyText: 'Votre photo et les repères restent dans ce navigateur. Ils ne sont ni envoyés ni stockés.', startOver: 'Recommencer', choosePhoto: 'Choisir une photo du visage', fileHint: 'JPG, PNG ou WebP · 10 Mo maximum', photoHint: 'Un visage, expression neutre, contour dégagé', analyzingTitle: 'Mesure des repères du visage sur votre appareil', analyzingText: 'Le premier lancement peut prendre un instant pendant le chargement du modèle.', errorTitle: 'Essayez une autre photo', errorHint: 'Utilisez un visage centré, les yeux à niveau, une lumière régulière, le front et la mâchoire visibles.', featuresTitle: 'Ce que comprend le résultat gratuit', features: ['Estimation parmi sept formes de visage', 'Maillage de repères affiché sur votre photo', 'Six mesures de géométrie et d’alignement', 'Contrôles du nombre de visages, de l’inclinaison et de la taille'], disclaimer: 'Il s’agit d’une estimation de style, pas d’une reconnaissance d’identité, d’un avis médical ou d’une mesure physique de monture. La photo reste dans la mémoire du navigateur.' },
  ru: { toolLabel: 'Бесплатный инструмент на устройстве', uploadTitle: 'Загрузите фото анфас', resultTitle: 'Результат измерения формы лица', privacyText: 'Фото и ориентиры остаются в этом браузере. Инструмент не отправляет и не хранит их.', startOver: 'Начать заново', choosePhoto: 'Выбрать фото лица', fileHint: 'JPG, PNG или WebP · до 10 МБ', photoHint: 'Одно лицо, нейтральное выражение, открытый контур', analyzingTitle: 'Измеряем ориентиры лица на вашем устройстве', analyzingText: 'При первом запуске загрузка модели может занять немного времени.', errorTitle: 'Попробуйте другое фото', errorHint: 'Используйте фото анфас с ровным освещением, открытым лбом и линией челюсти.', featuresTitle: 'Что входит в бесплатный результат', features: ['Оценка одной из семи форм лица', 'Сетка ориентиров поверх вашего фото', 'Шесть показателей геометрии и положения', 'Проверка количества лиц, наклона и размера'], disclaimer: 'Это стилистическая оценка, а не распознавание личности, медицинская рекомендация или физический размер оправы. Фото остаётся в памяти браузера.' },
  de: { toolLabel: 'Kostenloses Tool auf deinem Gerät', uploadTitle: 'Ein frontales Foto hochladen', resultTitle: 'Gemessenes Ergebnis deiner Gesichtsform', privacyText: 'Foto und Messpunkte bleiben in diesem Browser und werden nicht gespeichert oder hochgeladen.', startOver: 'Neu beginnen', choosePhoto: 'Gesichtsfoto auswählen', fileHint: 'JPG, PNG oder WebP · bis 10 MB', photoHint: 'Ein Gesicht, neutraler Ausdruck, freie Kontur', analyzingTitle: 'Gesichtspunkte werden auf deinem Gerät gemessen', analyzingText: 'Beim ersten Start kann das Laden des Modells kurz dauern.', errorTitle: 'Anderes Foto versuchen', errorHint: 'Nutze ein zentriertes Gesicht, gerade Augen, gleichmäßiges Licht sowie sichtbare Stirn und Kiefer.', featuresTitle: 'Das kostenlose Ergebnis enthält', features: ['Schätzung aus sieben Gesichtsformen', 'Live-Messpunktnetz auf deinem Foto', 'Sechs Geometrie- und Ausrichtungsdetails', 'Prüfung von Gesichtern, Neigung und Größe'], disclaimer: 'Dies ist eine Stil-Einschätzung, keine Identitätserkennung, medizinische Beratung oder physische Brillengrößenmessung. Das Bild bleibt im Browser.' },
  es: { toolLabel: 'Herramienta gratuita en tu dispositivo', uploadTitle: 'Sube una foto frontal', resultTitle: 'Resultado medido de la forma de tu rostro', privacyText: 'Tu foto y los puntos faciales permanecen en este navegador; no se suben ni almacenan.', startOver: 'Empezar de nuevo', choosePhoto: 'Elegir una foto del rostro', fileHint: 'JPG, PNG o WebP · hasta 10 MB', photoHint: 'Un rostro, expresión neutra y contorno visible', analyzingTitle: 'Midiendo puntos faciales en tu dispositivo', analyzingText: 'La primera vez puede tardar mientras el navegador carga el modelo.', errorTitle: 'Prueba otra foto', errorHint: 'Usa un rostro centrado, ojos nivelados, luz uniforme, frente y mandíbula visibles.', featuresTitle: 'Qué incluye el resultado gratuito', features: ['Estimación entre siete formas de rostro', 'Malla de puntos sobre tu foto', 'Seis detalles de geometría y alineación', 'Controles de rostros, inclinación y tamaño'], disclaimer: 'Es una estimación de estilo, no reconocimiento de identidad, consejo médico ni medida física de montura. La imagen permanece en el navegador.' },
  pt: { toolLabel: 'Ferramenta gratuita no seu dispositivo', uploadTitle: 'Envie uma foto de frente', resultTitle: 'Resultado medido do formato do rosto', privacyText: 'Sua foto e os pontos faciais ficam neste navegador; não são enviados nem armazenados.', startOver: 'Recomeçar', choosePhoto: 'Escolher foto do rosto', fileHint: 'JPG, PNG ou WebP · até 10 MB', photoHint: 'Um rosto, expressão neutra e contorno visível', analyzingTitle: 'Medindo pontos faciais no seu dispositivo', analyzingText: 'Na primeira vez, o carregamento do modelo pode levar alguns instantes.', errorTitle: 'Tente outra foto', errorHint: 'Use um rosto centralizado, olhos nivelados, luz uniforme, testa e mandíbula visíveis.', featuresTitle: 'O resultado gratuito inclui', features: ['Estimativa entre sete formatos de rosto', 'Malha de pontos sobre a foto', 'Seis detalhes de geometria e alinhamento', 'Verificação de rostos, inclinação e tamanho'], disclaimer: 'É uma estimativa de estilo, não reconhecimento de identidade, orientação médica ou medida física da armação. A imagem permanece no navegador.' },
  ja: { toolLabel: '端末内で使える無料ツール', uploadTitle: '正面写真を1枚アップロード', resultTitle: '顔型の測定結果', privacyText: '写真と顔の測定点はブラウザ内に留まり、送信・保存されません。', startOver: '最初からやり直す', choosePhoto: '顔写真を選ぶ', fileHint: 'JPG・PNG・WebP、10MBまで', photoHint: '1人、自然な表情、輪郭が見える写真', analyzingTitle: '端末上で顔の測定点を解析中', analyzingText: '初回はモデルの読み込みに少し時間がかかる場合があります。', errorTitle: '別の写真をお試しください', errorHint: '顔を中央にし、目を水平にして、額とあごが見える均一な明るさの写真を使ってください。', featuresTitle: '無料結果に含まれるもの', features: ['7種類から顔型を推定', '写真上に顔の測定メッシュを表示', '形状と位置に関する6つの指標', '複数の顔・傾き・顔サイズを確認'], disclaimer: 'これはスタイル選びのための推定であり、本人認証、医療助言、実物のフレームサイズ測定ではありません。画像はブラウザ内に留まります。' },
  id: { toolLabel: 'Alat gratis di perangkat', uploadTitle: 'Unggah satu foto dari depan', resultTitle: 'Hasil pengukuran bentuk wajah', privacyText: 'Foto dan titik wajah tetap di browser ini; tidak diunggah atau disimpan.', startOver: 'Mulai ulang', choosePhoto: 'Pilih foto wajah', fileHint: 'JPG, PNG, atau WebP · maksimal 10 MB', photoHint: 'Satu wajah, ekspresi netral, garis wajah terlihat', analyzingTitle: 'Mengukur titik wajah di perangkat Anda', analyzingText: 'Pada penggunaan pertama, pemuatan model mungkin memerlukan waktu sejenak.', errorTitle: 'Coba foto lain', errorHint: 'Gunakan wajah di tengah, mata sejajar, cahaya merata, dahi dan rahang terlihat.', featuresTitle: 'Isi hasil gratis', features: ['Perkiraan dari tujuh bentuk wajah', 'Jaring titik wajah di atas foto', 'Enam detail geometri dan posisi', 'Pemeriksaan jumlah wajah, kemiringan, dan ukuran'], disclaimer: 'Ini adalah perkiraan gaya, bukan pengenalan identitas, saran medis, atau ukuran fisik bingkai. Gambar tetap berada di browser.' },
  ar: { toolLabel: 'أداة مجانية تعمل على جهازك', uploadTitle: 'ارفع صورة أمامية واحدة', resultTitle: 'نتيجة قياس شكل الوجه', privacyText: 'تبقى الصورة ونقاط الوجه داخل هذا المتصفح ولا يتم رفعها أو تخزينها.', startOver: 'ابدأ من جديد', choosePhoto: 'اختر صورة للوجه', fileHint: 'JPG أو PNG أو WebP · حتى 10 ميجابايت', photoHint: 'وجه واحد، تعبير طبيعي، وحدود الوجه ظاهرة', analyzingTitle: 'جارٍ قياس معالم الوجه على جهازك', analyzingText: 'قد يستغرق التشغيل الأول لحظة أثناء تحميل النموذج.', errorTitle: 'جرّب صورة أخرى', errorHint: 'استخدم وجهًا في المنتصف، عينين مستويتين، إضاءة متوازنة، وجبهة وفكًا ظاهرين.', featuresTitle: 'ما تتضمنه النتيجة المجانية', features: ['تقدير ضمن سبعة أشكال للوجه', 'شبكة معالم مباشرة فوق الصورة', 'ستة تفاصيل للهندسة والمحاذاة', 'فحص عدد الوجوه والميل والحجم'], disclaimer: 'هذا تقدير للأناقة وليس تعرّفًا على الهوية أو نصيحة طبية أو قياسًا فعليًا لإطار النظارة. تبقى الصورة في ذاكرة المتصفح.' },
}

export function getFaceShapeDetectorUiCopy(locale: string): FaceShapeDetectorUiCopy {
  return copies[isValidLocale(locale) ? locale : defaultLocale]
}
