import { defaultLocale, isValidLocale, type Locale } from '@/i18n'

export type OrdinaryGlassesDetailCopy = {
  metaTitle: string
  metaDescription: string
  title: string
  badge: string
  home: string
  description: string
  characteristicsTitle: string
  characteristicsText: string
  guidance: string
  tryFirstTitle: string
  avoidFirstTitle: string
  whyTitle: string
  recommendedEyebrow: string
  recommendedTitle: string
  tryAny: string
  tryStyle: string
  workflowEyebrow: string
  workflowTitle: string
  advisorCta: string
  faqTitle: string
  faqBest: string
  faqAvoid: string
  faqAi: string
  otherTitle: string
}

const copies: Record<Locale, OrdinaryGlassesDetailCopy> = {
  en: {
    metaTitle: 'Best Glasses for {shape} Faces: Styles to Try First', metaDescription: 'Best glasses for a {shape} face. Compare recommended frame styles and fit checks, then try the shortlist on your photo with virtual try-on or frame compare.', title: 'Best Glasses for {shape} Faces', badge: 'Glasses guide by face shape', home: 'Home', description: 'Use your {shape} face shape to shortlist frames, then compare width, lens depth, bridge fit, color, and style on your own photo.', characteristicsTitle: '{shape} face shopping goal', characteristicsText: 'Face shape is a useful first filter. The strongest choice also fits your measurements, prescription needs, comfort, and personal style.', guidance: 'Start with the recommendations below, then use virtual try-on as the visual check.', tryFirstTitle: 'Try first', avoidFirstTitle: 'Reconsider first', whyTitle: 'Why it works', recommendedEyebrow: 'Recommended frame styles', recommendedTitle: 'Glasses to try for {shape} faces', tryAny: 'Try any glasses on your photo', tryStyle: 'Try this style', workflowEyebrow: 'AI shopping workflow', workflowTitle: 'From {shape} face guide to virtual try-on', advisorCta: 'Get personalized glasses advice', faqTitle: '{shape} face glasses FAQ', faqBest: 'What glasses are best for a {shape} face?', faqAvoid: 'Should {shape} faces avoid any glasses?', faqAi: 'Can AI help me choose glasses for my face shape?', otherTitle: 'Compare glasses for other face shapes',
  },
  fr: {
    metaTitle: 'Meilleures lunettes pour un visage {shape}', metaDescription: 'Trouvez les meilleures lunettes pour un visage {shape}, comparez montures et ajustement, puis essayez la sélection sur votre photo.', title: 'Meilleures lunettes pour un visage {shape}', badge: 'Guide lunettes par forme de visage', home: 'Accueil', description: 'Utilisez votre visage {shape} pour présélectionner des montures, puis comparez largeur, hauteur des verres, pont, couleur et style sur votre photo.', characteristicsTitle: 'Objectif pour un visage {shape}', characteristicsText: 'La forme du visage est un premier filtre utile. Le meilleur choix respecte aussi vos mesures, votre correction, votre confort et votre style.', guidance: 'Commencez par les conseils ci-dessous, puis utilisez l’essayage virtuel comme vérification visuelle.', tryFirstTitle: 'À essayer en premier', avoidFirstTitle: 'À reconsidérer', whyTitle: 'Pourquoi cela fonctionne', recommendedEyebrow: 'Montures recommandées', recommendedTitle: 'Lunettes à essayer pour un visage {shape}', tryAny: 'Essayer des lunettes sur votre photo', tryStyle: 'Essayer ce style', workflowEyebrow: 'Parcours d’achat avec IA', workflowTitle: 'Du guide visage {shape} à l’essayage virtuel', advisorCta: 'Recevoir un conseil personnalisé', faqTitle: 'FAQ lunettes pour visage {shape}', faqBest: 'Quelles lunettes conviennent à un visage {shape} ?', faqAvoid: 'Un visage {shape} doit-il éviter certaines lunettes ?', faqAi: 'L’IA peut-elle m’aider à choisir mes lunettes ?', otherTitle: 'Comparer les autres formes de visage',
  },
  ru: {
    metaTitle: 'Лучшие очки для формы лица {shape}', metaDescription: 'Подберите очки для формы лица {shape}, сравните оправы и посадку, затем примерьте выбранные модели на своей фотографии.', title: 'Лучшие очки для формы лица {shape}', badge: 'Гид по очкам и форме лица', home: 'Главная', description: 'Используйте форму лица {shape} для первого отбора оправ, затем сравните ширину, высоту линз, мост, цвет и стиль на своём фото.', characteristicsTitle: 'Цель выбора для формы {shape}', characteristicsText: 'Форма лица — полезный первый фильтр. Лучшая оправа также учитывает размеры, рецепт, комфорт и личный стиль.', guidance: 'Начните с рекомендаций ниже, а затем проверьте результат виртуальной примеркой.', tryFirstTitle: 'Попробуйте сначала', avoidFirstTitle: 'Сначала пересмотрите', whyTitle: 'Почему это работает', recommendedEyebrow: 'Рекомендуемые оправы', recommendedTitle: 'Очки для формы лица {shape}', tryAny: 'Примерить очки на своём фото', tryStyle: 'Примерить этот стиль', workflowEyebrow: 'Путь выбора с ИИ', workflowTitle: 'От гида для формы {shape} к виртуальной примерке', advisorCta: 'Получить персональный совет', faqTitle: 'Вопросы об очках для формы {shape}', faqBest: 'Какие очки подходят форме лица {shape}?', faqAvoid: 'Каких очков стоит избегать при форме {shape}?', faqAi: 'Может ли ИИ помочь выбрать очки?', otherTitle: 'Сравнить другие формы лица',
  },
  de: {
    metaTitle: 'Beste Brillen für eine {shape} Gesichtsform', metaDescription: 'Finden Sie Brillen für eine {shape} Gesichtsform, vergleichen Sie Fassungen und Passform und testen Sie die Auswahl auf Ihrem Foto.', title: 'Beste Brillen für eine {shape} Gesichtsform', badge: 'Brillenratgeber nach Gesichtsform', home: 'Startseite', description: 'Nutzen Sie Ihre {shape} Gesichtsform für die Vorauswahl und prüfen Sie Breite, Glashöhe, Steg, Farbe und Stil auf Ihrem Foto.', characteristicsTitle: 'Auswahlziel für die Gesichtsform {shape}', characteristicsText: 'Die Gesichtsform ist ein hilfreicher erster Filter. Die beste Fassung berücksichtigt auch Maße, Sehstärke, Komfort und persönlichen Stil.', guidance: 'Beginnen Sie mit den Empfehlungen und prüfen Sie das Ergebnis anschließend mit der virtuellen Anprobe.', tryFirstTitle: 'Zuerst probieren', avoidFirstTitle: 'Zuerst überdenken', whyTitle: 'Warum es funktioniert', recommendedEyebrow: 'Empfohlene Fassungen', recommendedTitle: 'Brillen für die Gesichtsform {shape}', tryAny: 'Brillen auf meinem Foto testen', tryStyle: 'Diesen Stil testen', workflowEyebrow: 'KI-gestützter Auswahlweg', workflowTitle: 'Vom {shape}-Ratgeber zur virtuellen Anprobe', advisorCta: 'Persönliche Brillenberatung erhalten', faqTitle: 'Brillen-FAQ für {shape} Gesichter', faqBest: 'Welche Brillen passen zu einer {shape} Gesichtsform?', faqAvoid: 'Sollten {shape} Gesichter bestimmte Brillen vermeiden?', faqAi: 'Kann KI bei der Brillenwahl helfen?', otherTitle: 'Andere Gesichtsformen vergleichen',
  },
  pt: {
    metaTitle: 'Melhores óculos para rosto {shape}', metaDescription: 'Encontre os melhores óculos para rosto {shape}, compare armações e ajuste e experimente a seleção na sua foto.', title: 'Melhores óculos para rosto {shape}', badge: 'Guia de óculos por formato de rosto', home: 'Início', description: 'Use o formato {shape} para selecionar armações e depois compare largura, altura das lentes, ponte, cor e estilo na sua foto.', characteristicsTitle: 'Objetivo para rosto {shape}', characteristicsText: 'O formato do rosto é um bom primeiro filtro. A melhor armação também respeita medidas, receita, conforto e estilo pessoal.', guidance: 'Comece pelas recomendações abaixo e use a prova virtual como verificação visual.', tryFirstTitle: 'Experimente primeiro', avoidFirstTitle: 'Reconsidere primeiro', whyTitle: 'Por que funciona', recommendedEyebrow: 'Armações recomendadas', recommendedTitle: 'Óculos para experimentar em rosto {shape}', tryAny: 'Experimentar óculos na minha foto', tryStyle: 'Experimentar este estilo', workflowEyebrow: 'Jornada de compra com IA', workflowTitle: 'Do guia de rosto {shape} à prova virtual', advisorCta: 'Receber recomendação personalizada', faqTitle: 'Perguntas sobre óculos para rosto {shape}', faqBest: 'Quais óculos combinam com rosto {shape}?', faqAvoid: 'Rostos {shape} devem evitar algum óculos?', faqAi: 'A IA pode ajudar a escolher óculos?', otherTitle: 'Comparar outros formatos de rosto',
  },
  id: {
    metaTitle: 'Kacamata Terbaik untuk Wajah {shape}', metaDescription: 'Temukan kacamata terbaik untuk wajah {shape}, bandingkan bingkai dan kecocokannya, lalu coba pilihan pada foto Anda.', title: 'Kacamata Terbaik untuk Wajah {shape}', badge: 'Panduan kacamata berdasarkan bentuk wajah', home: 'Beranda', description: 'Gunakan bentuk wajah {shape} untuk memilih bingkai awal, lalu periksa lebar, tinggi lensa, jembatan, warna, dan gaya pada foto Anda.', characteristicsTitle: 'Tujuan pilihan untuk wajah {shape}', characteristicsText: 'Bentuk wajah adalah filter awal yang berguna. Bingkai terbaik juga sesuai dengan ukuran, resep, kenyamanan, dan gaya pribadi.', guidance: 'Mulai dengan rekomendasi berikut, lalu gunakan coba virtual sebagai pemeriksaan visual.', tryFirstTitle: 'Coba lebih dulu', avoidFirstTitle: 'Pertimbangkan kembali', whyTitle: 'Mengapa cocok', recommendedEyebrow: 'Bingkai yang direkomendasikan', recommendedTitle: 'Kacamata untuk wajah {shape}', tryAny: 'Coba kacamata pada foto saya', tryStyle: 'Coba gaya ini', workflowEyebrow: 'Alur belanja dengan AI', workflowTitle: 'Dari panduan wajah {shape} ke coba virtual', advisorCta: 'Dapatkan saran kacamata personal', faqTitle: 'FAQ kacamata untuk wajah {shape}', faqBest: 'Kacamata apa yang cocok untuk wajah {shape}?', faqAvoid: 'Apakah wajah {shape} perlu menghindari kacamata tertentu?', faqAi: 'Bisakah AI membantu memilih kacamata?', otherTitle: 'Bandingkan bentuk wajah lain',
  },
  ja: {
    metaTitle: '{shape}顔に似合うおすすめメガネ', metaDescription: '{shape}顔に似合うメガネを比較し、サイズやフィットを確認して、自分の写真で候補を試着できます。', title: '{shape}顔に似合うおすすめメガネ', badge: '顔型別メガネガイド', home: 'ホーム', description: '{shape}顔を最初の絞り込みに使い、フレーム幅、レンズの高さ、ブリッジ、色、印象を自分の写真で確認しましょう。', characteristicsTitle: '{shape}顔のフレーム選び', characteristicsText: '顔型は便利な最初の基準です。最適なフレームは、実寸、度数、掛け心地、自分らしいスタイルも満たします。', guidance: '下の候補から始め、最後はバーチャル試着で見た目を確認してください。', tryFirstTitle: '最初に試す', avoidFirstTitle: '最初の候補では再検討', whyTitle: '似合いやすい理由', recommendedEyebrow: 'おすすめフレーム', recommendedTitle: '{shape}顔で試したいメガネ', tryAny: '自分の写真でメガネを試す', tryStyle: 'このスタイルを試す', workflowEyebrow: 'AIメガネ選び', workflowTitle: '{shape}顔ガイドからバーチャル試着へ', advisorCta: 'パーソナル提案を見る', faqTitle: '{shape}顔のメガネFAQ', faqBest: '{shape}顔にはどんなメガネが似合いますか？', faqAvoid: '{shape}顔が避けるべきメガネはありますか？', faqAi: 'AIで似合うメガネを選べますか？', otherTitle: 'ほかの顔型も比較する',
  },
  es: {
    metaTitle: 'Mejores gafas para rostro {shape}', metaDescription: 'Encuentra las mejores gafas para rostro {shape}, compara monturas y ajuste y prueba la selección en tu foto.', title: 'Mejores gafas para rostro {shape}', badge: 'Guía de gafas por forma de rostro', home: 'Inicio', description: 'Usa tu rostro {shape} para preseleccionar monturas y después compara anchura, altura de lente, puente, color y estilo en tu foto.', characteristicsTitle: 'Objetivo para un rostro {shape}', characteristicsText: 'La forma del rostro es un primer filtro útil. La mejor montura también respeta medidas, graduación, comodidad y estilo personal.', guidance: 'Empieza por estas recomendaciones y usa la prueba virtual como comprobación visual.', tryFirstTitle: 'Prueba primero', avoidFirstTitle: 'Reconsidera primero', whyTitle: 'Por qué funciona', recommendedEyebrow: 'Monturas recomendadas', recommendedTitle: 'Gafas para probar en un rostro {shape}', tryAny: 'Probar gafas en mi foto', tryStyle: 'Probar este estilo', workflowEyebrow: 'Proceso de compra con IA', workflowTitle: 'De la guía para rostro {shape} a la prueba virtual', advisorCta: 'Recibir recomendación personalizada', faqTitle: 'Preguntas sobre gafas para rostro {shape}', faqBest: '¿Qué gafas quedan bien a un rostro {shape}?', faqAvoid: '¿Un rostro {shape} debe evitar algunas gafas?', faqAi: '¿Puede la IA ayudarme a elegir gafas?', otherTitle: 'Comparar otras formas de rostro',
  },
  ar: {
    metaTitle: 'أفضل النظارات للوجه {shape}', metaDescription: 'اكتشف أفضل النظارات للوجه {shape}، وقارن الإطارات والملاءمة، ثم جرّب الخيارات على صورتك.', title: 'أفضل النظارات للوجه {shape}', badge: 'دليل النظارات حسب شكل الوجه', home: 'الرئيسية', description: 'استخدم شكل الوجه {shape} لاختيار الإطارات أوليًا، ثم قارن العرض وارتفاع العدسة والجسر واللون والأسلوب على صورتك.', characteristicsTitle: 'هدف الاختيار للوجه {shape}', characteristicsText: 'شكل الوجه مرشح أولي مفيد. الإطار الأفضل يراعي أيضًا المقاسات والوصفة والراحة والأسلوب الشخصي.', guidance: 'ابدأ بالتوصيات أدناه ثم استخدم التجربة الافتراضية للتحقق من المظهر.', tryFirstTitle: 'جرّب أولًا', avoidFirstTitle: 'أعد النظر أولًا', whyTitle: 'لماذا يناسب', recommendedEyebrow: 'إطارات مقترحة', recommendedTitle: 'نظارات لتجربتها للوجه {shape}', tryAny: 'جرّب النظارات على صورتي', tryStyle: 'جرّب هذا النمط', workflowEyebrow: 'مسار تسوق بالذكاء الاصطناعي', workflowTitle: 'من دليل الوجه {shape} إلى التجربة الافتراضية', advisorCta: 'احصل على نصيحة مخصصة', faqTitle: 'أسئلة النظارات للوجه {shape}', faqBest: 'ما النظارات المناسبة للوجه {shape}؟', faqAvoid: 'هل ينبغي للوجه {shape} تجنب بعض النظارات؟', faqAi: 'هل يساعد الذكاء الاصطناعي في اختيار النظارات؟', otherTitle: 'قارن أشكال الوجه الأخرى',
  },
}

export function getOrdinaryGlassesDetailCopy(locale: string): OrdinaryGlassesDetailCopy {
  return copies[isValidLocale(locale) ? locale : defaultLocale]
}

export function interpolateOrdinaryGlassesCopy(template: string, shape: string): string {
  return template.split('{shape}').join(shape)
}
