import { getValidLocale, type Locale } from '@/i18n'

export type SearchToToolRouteId =
  | 'what-is-my-face-shape'
  | 'find-glasses-for-my-face'
  | 'try-glasses-on-photo'
  | 'ai-glasses-advisor'
  | 'what-glasses-suit-my-face'
  | 'virtual-glasses-try-on'
  | 'compare-glasses-frames'

export type SearchToToolFaq = { question: string; answer: string }
export type SearchToToolStepCopy = { title: string; text: string }

export type SearchToToolLandingCopy = {
  metaTitle: string
  metaDescription: string
  eyebrow: string
  title: string
  intro: string
  steps: readonly [SearchToToolStepCopy, SearchToToolStepCopy, SearchToToolStepCopy]
  principles: readonly [string, string, string]
  faq: readonly [SearchToToolFaq, SearchToToolFaq, SearchToToolFaq]
  faqEyebrow: string
  faqTitle: string
  ctaLabels: {
    detector: string
    tryOn: string
    compare: string
    advisor: string
  }
}

export type GlassesGuideHubCopy = {
  metaTitle: string
  metaDescription: string
  eyebrow: string
  title: string
  intro: string
  groups: readonly {
    type: 'face-frame' | 'gender-style' | 'decision-question'
    eyebrow: string
    title: string
    description: string
  }[]
  openGuide: string
  homeBreadcrumb: string
  guidesBreadcrumb: string
  phaseBNote: string
}

type SharedCopy = {
  commonQuestions: string
  nextStep: string
  ctaLabels: SearchToToolLandingCopy['ctaLabels']
  principles: readonly [string, string, string]
}

const shared: Record<Locale, SharedCopy> = {
  en: {
    commonQuestions: 'Common questions', nextStep: 'Next step',
    ctaLabels: { detector: 'Detect my face shape', tryOn: 'Open virtual try-on', compare: 'Compare frames', advisor: 'Get glasses advice' },
    principles: ['Use face shape as a first filter, not a rigid rule.', 'Validate appearance on your own photo.', 'Confirm physical size, fit, and prescription needs separately.'],
  },
  id: {
    commonQuestions: 'Pertanyaan umum', nextStep: 'Langkah berikutnya',
    ctaLabels: { detector: 'Deteksi bentuk wajah saya', tryOn: 'Buka coba kacamata virtual', compare: 'Bandingkan bingkai', advisor: 'Dapatkan saran kacamata' },
    principles: ['Gunakan bentuk wajah sebagai filter awal, bukan aturan mutlak.', 'Validasi tampilan pada foto Anda sendiri.', 'Periksa ukuran fisik, kecocokan, dan kebutuhan resep secara terpisah.'],
  },
  ar: {
    commonQuestions: 'أسئلة شائعة', nextStep: 'الخطوة التالية',
    ctaLabels: { detector: 'اكتشف شكل وجهي', tryOn: 'افتح التجربة الافتراضية', compare: 'قارن الإطارات', advisor: 'احصل على نصيحة للنظارات' },
    principles: ['استخدم شكل الوجه كمرشح أولي وليس كقاعدة صارمة.', 'تحقق من المظهر على صورتك أنت.', 'تحقق من المقاس والملاءمة واحتياجات الوصفة الطبية بشكل منفصل.'],
  },
  ru: {
    commonQuestions: 'Частые вопросы', nextStep: 'Следующий шаг',
    ctaLabels: { detector: 'Определить форму лица', tryOn: 'Открыть виртуальную примерку', compare: 'Сравнить оправы', advisor: 'Получить совет по очкам' },
    principles: ['Используйте форму лица как первый фильтр, а не жёсткое правило.', 'Проверяйте внешний вид на своей фотографии.', 'Размер, посадку и требования рецепта проверяйте отдельно.'],
  },
  de: {
    commonQuestions: 'Häufige Fragen', nextStep: 'Nächster Schritt',
    ctaLabels: { detector: 'Meine Gesichtsform erkennen', tryOn: 'Virtuelle Anprobe öffnen', compare: 'Fassungen vergleichen', advisor: 'Brillenberatung erhalten' },
    principles: ['Nutze die Gesichtsform als ersten Filter, nicht als starre Regel.', 'Prüfe die Wirkung auf deinem eigenen Foto.', 'Größe, Passform und Sehstärke separat bestätigen.'],
  },
  ja: {
    commonQuestions: 'よくある質問', nextStep: '次のステップ',
    ctaLabels: { detector: '顔型を判定する', tryOn: 'バーチャル試着を開く', compare: 'フレームを比較する', advisor: 'メガネの提案を見る' },
    principles: ['顔型は最初の絞り込みに使い、絶対的なルールにはしません。', '自分の写真で見え方を確認します。', '実寸・フィット・度数条件は別途確認します。'],
  },
  es: {
    commonQuestions: 'Preguntas frecuentes', nextStep: 'Siguiente paso',
    ctaLabels: { detector: 'Detectar la forma de mi cara', tryOn: 'Abrir prueba virtual', compare: 'Comparar monturas', advisor: 'Obtener consejo sobre gafas' },
    principles: ['Usa la forma del rostro como primer filtro, no como una regla rígida.', 'Valida el aspecto con tu propia foto.', 'Confirma por separado talla, ajuste y necesidades de graduación.'],
  },
  pt: {
    commonQuestions: 'Perguntas frequentes', nextStep: 'Próximo passo',
    ctaLabels: { detector: 'Detectar o formato do meu rosto', tryOn: 'Abrir prova virtual', compare: 'Comparar armações', advisor: 'Receber orientação de óculos' },
    principles: ['Use o formato do rosto como primeiro filtro, não como regra rígida.', 'Valide a aparência na sua própria foto.', 'Confirme separadamente tamanho, ajuste e necessidades de grau.'],
  },
  fr: {
    commonQuestions: 'Questions fréquentes', nextStep: 'Étape suivante',
    ctaLabels: { detector: 'Détecter la forme de mon visage', tryOn: 'Ouvrir l’essayage virtuel', compare: 'Comparer les montures', advisor: 'Obtenir des conseils lunettes' },
    principles: ['Utilisez la forme du visage comme premier filtre, pas comme règle stricte.', 'Validez le rendu sur votre propre photo.', 'Vérifiez séparément la taille, l’ajustement et les besoins de correction.'],
  },
}

const en: Record<SearchToToolRouteId, Omit<SearchToToolLandingCopy, 'principles' | 'ctaLabels' | 'faqEyebrow' | 'faqTitle'>> = {
  'what-is-my-face-shape': {
    metaTitle: 'What Is My Face Shape? Free Photo Face Shape Detector | VisuTry',
    metaDescription: 'What is my face shape? Upload one clear photo and use the free on-device VisuTry detector to estimate your likely face shape, then continue into glasses advice.',
    eyebrow: 'Free photo face-shape check', title: 'What Is My Face Shape?',
    intro: 'Use one clear photo to estimate your likely face shape, then turn that result into practical glasses guidance instead of stopping at a label.',
    steps: [{ title: 'Upload one photo', text: 'Use a straight-on photo with your full face visible.' }, { title: 'Detect your likely shape', text: 'The free detector runs on-device in your browser.' }, { title: 'Use the result', text: 'Continue into glasses advice, try-on, or frame compare.' }],
    faq: [{ question: 'How can I tell what my face shape is?', answer: 'Compare the relative width of your forehead, cheekbones, and jaw together with overall face length. VisuTry can estimate the likely shape from one clear photo.' }, { question: 'Is the face shape detector free?', answer: 'Yes. The basic face shape detector is free and runs on-device in your browser.' }, { question: 'What should I do after I know my face shape?', answer: 'Use it as a first filter, then compare frame width, lens depth, bridge fit, and style with advice, try-on, or frame compare.' }],
  },
  'find-glasses-for-my-face': {
    metaTitle: 'Find Glasses for My Face from a Photo | VisuTry', metaDescription: 'Find glasses for your face from one photo. Detect your likely face shape, shortlist frame directions, then validate them with virtual try-on or side-by-side compare.',
    eyebrow: 'Photo-first frame shortlisting', title: 'Find Glasses for My Face', intro: 'Turn one photo into a practical shortlist: understand your face proportions, narrow the frame directions worth trying, then validate the final candidates visually.',
    steps: [{ title: 'Understand your face', text: 'Start with the free face shape detector as a first filter.' }, { title: 'Shortlist frame directions', text: 'Focus on a few shapes and proportions instead of browsing everything.' }, { title: 'Validate on your photo', text: 'Use try-on or side-by-side compare before you decide.' }],
    faq: [{ question: 'How do I find glasses that suit my face?', answer: 'Start with face proportions, then narrow the frame shapes and widths worth testing. A photo-based try-on or side-by-side comparison helps confirm the shortlist.' }, { question: 'Should I choose glasses only by face shape?', answer: 'No. Face shape is a useful first filter, but frame width, bridge fit, lens depth, prescription needs, and personal style also matter.' }, { question: 'Can I use my own glasses product image?', answer: 'Yes. VisuTry virtual try-on can use a glasses product image or retailer screenshot to validate a specific pair.' }],
  },
  'try-glasses-on-photo': {
    metaTitle: 'Try Glasses on a Photo Online | VisuTry', metaDescription: 'Try glasses on your photo online. Upload a clear face photo and a glasses product image or screenshot, preview the look, then compare alternative frames side by side.',
    eyebrow: 'Photo-based virtual glasses preview', title: 'Try Glasses on Your Photo Online', intro: 'Upload your own photo and a glasses image to preview one specific pair, then compare alternatives side by side when you need more confidence before buying.',
    steps: [{ title: 'Upload your face photo', text: 'Use a clear, straight-on image with even light.' }, { title: 'Add the glasses image', text: 'Use a product photo or retailer screenshot of the frame you are considering.' }, { title: 'Compare if needed', text: 'Move into Frame Compare when one preview is not enough.' }],
    faq: [{ question: 'Can I try glasses on a photo online?', answer: 'Yes. Upload a clear face photo and a glasses product image or screenshot to preview how the frame looks on you.' }, { question: 'Can I use a screenshot from an eyewear store?', answer: 'Yes. A clean product image or retailer screenshot can be used for virtual try-on. Confirm exact size and model details with the seller before buying.' }, { question: 'What if I want to compare more than one pair?', answer: 'Use Frame Compare after try-on to review several candidates side by side instead of relying on memory.' }],
  },
  'ai-glasses-advisor': {
    metaTitle: 'AI Glasses Advisor: Find Frames for Your Face | VisuTry', metaDescription: 'Use the VisuTry AI glasses advisor to turn a face photo into practical frame guidance, then validate the shortlist with virtual try-on or side-by-side comparison.',
    eyebrow: 'Personalized eyewear guidance', title: 'AI Glasses Advisor', intro: 'Use your photo to narrow the frame directions worth considering, understand why they may work, then validate the shortlist with try-on or side-by-side comparison.',
    steps: [{ title: 'Understand your face', text: 'Use face proportions as a practical starting point.' }, { title: 'Get frame guidance', text: 'Turn the analysis into a smaller set of frame directions worth testing.' }, { title: 'Validate the shortlist', text: 'Use virtual try-on and compare before you decide.' }],
    faq: [{ question: 'What does an AI glasses advisor do?', answer: 'It turns visible face proportions and your photo into practical frame guidance, helping you narrow shapes and styles before trying specific glasses.' }, { question: 'Is the advisor the same as virtual try-on?', answer: 'No. The advisor helps decide what directions are worth trying. Virtual try-on then shows how a specific frame looks on your photo.' }, { question: 'Should I use face shape alone to choose glasses?', answer: 'No. Frame width, lens depth, bridge fit, prescription needs, and your preferred style should also be considered.' }],
  },
  'what-glasses-suit-my-face': {
    metaTitle: 'What Glasses Suit My Face? Upload a Photo and Shortlist Frames', metaDescription: 'What glasses suit my face? Use the free face shape detector on your photo, shortlist frame shapes, then confirm with virtual try-on or side-by-side compare.',
    eyebrow: 'Photo-first glasses advice', title: 'What Glasses Suit My Face?', intro: 'Upload one photo to estimate your face shape, turn that into a practical frame shortlist, then confirm the look with try-on or frame compare.',
    steps: [{ title: 'Detect your face shape', text: 'Use the free on-device detector—no login required.' }, { title: 'Shortlist frame shapes', text: 'Narrow options before you fall in love with a single pair.' }, { title: 'Validate on your photo', text: 'Check scale and style with try-on or side-by-side compare.' }],
    faq: [{ question: 'How do I know what glasses suit my face?', answer: 'Start with a free face-shape estimate from one photo, shortlist complementary frame shapes, then validate width, scale, and style on your own image.' }, { question: 'Do I need to upload a photo?', answer: 'A photo helps the free detector and virtual try-on. You can also read face-shape guidance first.' }, { question: 'Is face shape enough to choose glasses?', answer: 'No. Also check frame width, bridge fit, lens depth, prescription needs, comfort, and personal style.' }],
  },
  'virtual-glasses-try-on': {
    metaTitle: 'Virtual Glasses Try On from Your Photo | VisuTry', metaDescription: 'Virtual glasses try on online from a face photo and any glasses product image or screenshot. See the look before you buy, then compare frames side by side.',
    eyebrow: 'Virtual try-on from your photo', title: 'Virtual Glasses Try On Online', intro: 'See how glasses look on your face before you buy. Upload your photo and a frame image, then continue into compare when you want a cleaner side-by-side decision.',
    steps: [{ title: 'Upload your photo', text: 'Use a straight-on face photo with even light.' }, { title: 'Add a glasses image', text: 'Use a product photo or retailer screenshot.' }, { title: 'Preview and decide', text: 'Check the look, then compare alternatives if needed.' }],
    faq: [{ question: 'Can I try glasses on my photo online?', answer: 'Yes. Upload a clear face photo and a glasses product image or screenshot to preview how the frames look on you.' }, { question: 'Do I need the exact brand catalog?', answer: 'No. VisuTry works with your own glasses image, including retailer screenshots. Confirm the exact model and size with the seller.' }, { question: 'What if I want to compare a few pairs?', answer: 'After try-on, use Frame Compare to review several options side by side.' }],
  },
  'compare-glasses-frames': {
    metaTitle: 'Compare Glasses Frames Side by Side on Your Photo | VisuTry', metaDescription: 'Compare glasses frames on your photo. Choose up to four built-in presets, generate AI try-on results side by side, and decide which look works better.',
    eyebrow: 'Side-by-side frame decisions', title: 'Compare Glasses Frames on Your Photo', intro: 'When one try-on is not enough, compare a few frame directions together. Pick presets, generate results side by side, and keep the look that fits you best.',
    steps: [{ title: 'Upload one photo', text: 'Use a clear, straight-on face photo.' }, { title: 'Choose up to four frames', text: 'Select built-in presets that feel different enough to compare.' }, { title: 'Review side by side', text: 'Decide with a cleaner board instead of memory alone.' }],
    faq: [{ question: 'How do I compare glasses frames online?', answer: 'Upload one face photo, select up to four built-in frame presets, and generate side-by-side AI try-on results.' }, { question: 'Is this better than trying one pair at a time?', answer: 'Side-by-side compare helps when two or more silhouettes look similar alone. Use single try-on when you already have one exact product image.' }, { question: 'Do I need to know my face shape first?', answer: 'It helps but is optional. You can start with compare directly or use the free detector first.' }],
  },
}

type LocaleRouteCopy = Omit<SearchToToolLandingCopy, 'principles' | 'ctaLabels' | 'faqEyebrow' | 'faqTitle'>

const localized: Record<Exclude<Locale, 'en'>, Record<SearchToToolRouteId, LocaleRouteCopy>> = {
  ja: {
    'what-is-my-face-shape': { metaTitle: '私の顔型は？写真で無料診断 | VisuTry', metaDescription: '正面写真1枚から顔型の傾向を無料で確認し、その結果をメガネ選びや試着につなげます。', eyebrow: '写真で無料の顔型チェック', title: '私の顔型は？', intro: '正面写真1枚から顔型の傾向を確認し、単なる分類で終わらせず、実際のメガネ選びに活用します。', steps: [{ title: '写真を1枚選ぶ', text: '顔全体が見える正面写真を使います。' }, { title: '顔型を判定', text: '無料判定はブラウザ内で実行されます。' }, { title: '結果を活用', text: 'メガネ提案、試着、フレーム比較へ進みます。' }], faq: [{ question: '自分の顔型はどう分かりますか？', answer: '額・頬骨・あごの幅と顔全体の長さを比較します。VisuTryは正面写真から顔型の傾向を推定します。' }, { question: '顔型判定は無料ですか？', answer: 'はい。基本の顔型判定は無料で、ブラウザ上で処理されます。' }, { question: '顔型が分かった後は？', answer: '顔型を最初の絞り込みに使い、フレーム幅やレンズの深さを確認し、試着や比較で最終判断します。' }] },
    'find-glasses-for-my-face': { metaTitle: '自分の顔に似合うメガネを写真から探す | VisuTry', metaDescription: '写真から顔の特徴を確認し、似合いやすいフレーム候補を絞り、バーチャル試着や比較で確認できます。', eyebrow: '写真からフレーム候補を絞る', title: '自分の顔に似合うメガネを探す', intro: '写真1枚から顔のバランスを把握し、試す価値のあるフレーム方向を絞り、最後は見た目で確認します。', steps: [{ title: '顔の特徴を把握', text: '無料の顔型判定を最初のフィルターにします。' }, { title: '候補を絞る', text: 'すべてを見るのではなく、数種類の形と比率に絞ります。' }, { title: '写真で確認', text: '試着または横並び比較で決めます。' }], faq: [{ question: '顔に似合うメガネはどう探しますか？', answer: '顔の比率からフレーム形状と幅を絞り、写真試着や横並び比較で候補を確認します。' }, { question: '顔型だけで選んでよいですか？', answer: 'いいえ。幅、ブリッジ、レンズの深さ、度数条件、好みも重要です。' }, { question: '手元の商品画像を使えますか？', answer: 'はい。商品画像やショップのスクリーンショットを使って特定のフレームを試着できます。' }] },
    'try-glasses-on-photo': { metaTitle: '写真でメガネをオンライン試着 | VisuTry', metaDescription: '顔写真とメガネの商品画像を使ってオンライン試着し、必要なら複数フレームを横並びで比較できます。', eyebrow: '写真ベースのメガネ試着', title: '自分の写真でメガネをオンライン試着', intro: '自分の写真とメガネ画像を使って特定の1本を確認し、迷ったら候補を横並びで比較します。', steps: [{ title: '顔写真をアップロード', text: '明るく正面を向いた写真を使います。' }, { title: 'メガネ画像を追加', text: '商品写真やショップのスクリーンショットを使えます。' }, { title: '必要なら比較', text: '1枚だけでは決めにくい場合はFrame Compareへ進みます。' }], faq: [{ question: '写真でメガネを試着できますか？', answer: 'はい。顔写真とメガネの商品画像を使って見え方を確認できます。' }, { question: 'ショップのスクリーンショットでも使えますか？', answer: 'はい。鮮明な商品画像なら利用できます。購入前に実寸と型番は販売店で確認してください。' }, { question: '複数を比較したい場合は？', answer: 'Frame Compareで候補を横並びにし、記憶だけに頼らず比較できます。' }] },
    'ai-glasses-advisor': { metaTitle: 'AIメガネアドバイザー：顔に合うフレーム提案 | VisuTry', metaDescription: '顔写真からフレーム選びの方向性を整理し、試着や比較で候補を検証できるAIメガネアドバイザーです。', eyebrow: 'パーソナライズされたメガネ提案', title: 'AIメガネアドバイザー', intro: '写真から試す価値のあるフレーム方向を絞り、その理由を理解した上で試着や比較で確認します。', steps: [{ title: '顔の特徴を把握', text: '顔の比率を実用的な出発点にします。' }, { title: 'フレーム提案を得る', text: '試す候補を少数の方向性に絞ります。' }, { title: '候補を検証', text: 'バーチャル試着と比較で最終確認します。' }], faq: [{ question: 'AIメガネアドバイザーは何をしますか？', answer: '顔写真と見える比率から、試す価値のある形やスタイルを絞ります。' }, { question: 'バーチャル試着と同じですか？', answer: 'いいえ。アドバイザーは候補を絞り、試着は特定フレームの見え方を確認します。' }, { question: '顔型だけで選びますか？', answer: 'いいえ。幅、レンズの深さ、ブリッジ、度数条件、好みも考慮します。' }] },
    'what-glasses-suit-my-face': { metaTitle: '私の顔に似合うメガネは？写真で候補を絞る | VisuTry', metaDescription: '無料の顔型判定からフレーム候補を絞り、写真で試着・比較して自分に似合うメガネを確認します。', eyebrow: '写真から始めるメガネ選び', title: '私の顔に似合うメガネは？', intro: '写真1枚から顔型の傾向を確認し、フレーム候補を絞ってから試着や比較で見え方を確かめます。', steps: [{ title: '顔型を判定', text: 'ログイン不要の無料判定を使います。' }, { title: '形を絞る', text: 'まず少数のフレーム形状に絞ります。' }, { title: '写真で確認', text: '試着や横並び比較でサイズ感とスタイルを確認します。' }], faq: [{ question: '似合うメガネはどう判断しますか？', answer: '顔型を最初の絞り込みに使い、相性の良い形を選んで、自分の写真で幅やバランスを確認します。' }, { question: '写真は必要ですか？', answer: '顔型判定と試着には写真が役立ちます。先にガイドだけ読むこともできます。' }, { question: '顔型だけで十分ですか？', answer: 'いいえ。幅、ブリッジ、レンズの深さ、度数条件、快適さ、好みも確認してください。' }] },
    'virtual-glasses-try-on': { metaTitle: 'バーチャルメガネ試着：自分の写真で確認 | VisuTry', metaDescription: '顔写真と任意のメガネ商品画像を使ってオンラインでバーチャル試着し、購入前に複数候補も比較できます。', eyebrow: '自分の写真でバーチャル試着', title: 'メガネをオンラインでバーチャル試着', intro: '購入前に、自分の写真とフレーム画像で見え方を確認します。迷ったら複数候補を横並びで比較できます。', steps: [{ title: '写真をアップロード', text: '明るい正面写真を使います。' }, { title: 'メガネ画像を追加', text: '商品写真やショップのスクリーンショットを使えます。' }, { title: '確認して決める', text: '見え方を確認し、必要なら別候補も比較します。' }], faq: [{ question: '自分の写真でメガネを試着できますか？', answer: 'はい。顔写真とメガネ商品画像を使って見え方を確認できます。' }, { question: 'ブランドの専用カタログが必要ですか？', answer: 'いいえ。手元の商品画像やショップのスクリーンショットを使えます。' }, { question: '何本か比較したい場合は？', answer: '試着後にFrame Compareで複数候補を横並びにできます。' }] },
    'compare-glasses-frames': { metaTitle: 'メガネフレームを写真で横並び比較 | VisuTry', metaDescription: '顔写真に最大4つのプリセットフレームを生成し、AI試着結果を横並びで比較して選べます。', eyebrow: 'フレームを横並びで判断', title: '自分の写真でメガネフレームを比較', intro: '1本ずつでは迷うとき、複数のフレーム方向を同じ画面で比較し、より似合う候補を選びます。', steps: [{ title: '写真を1枚アップロード', text: '明るく正面を向いた顔写真を使います。' }, { title: '最大4フレームを選択', text: '違いが分かるプリセットを選びます。' }, { title: '横並びで確認', text: '記憶ではなく同じボード上で比較します。' }], faq: [{ question: 'オンラインでフレームを比較するには？', answer: '顔写真を1枚アップロードし、最大4つのプリセットを選んでAI試着結果を横並びにします。' }, { question: '1本ずつ試すより良いですか？', answer: '似た候補で迷う場合は横並び比較が便利です。特定の商品1本なら単体試着が適しています。' }, { question: '先に顔型を知る必要がありますか？', answer: '必須ではありません。直接比較しても、無料判定で候補を絞ってからでも構いません。' }] },
  },
  de: {
    'what-is-my-face-shape': { metaTitle: 'Welche Gesichtsform habe ich? Kostenlos per Foto | VisuTry', metaDescription: 'Bestimme deine wahrscheinliche Gesichtsform kostenlos aus einem frontalen Foto und nutze das Ergebnis für die Brillenauswahl.', eyebrow: 'Kostenloser Gesichtsform-Check per Foto', title: 'Welche Gesichtsform habe ich?', intro: 'Schätze deine Gesichtsform mit einem klaren Foto und verwende das Ergebnis direkt als praktische Hilfe bei der Brillenauswahl.', steps: [{ title: 'Ein Foto wählen', text: 'Nutze ein frontales Foto mit vollständig sichtbarem Gesicht.' }, { title: 'Gesichtsform erkennen', text: 'Die kostenlose Analyse läuft lokal im Browser.' }, { title: 'Ergebnis nutzen', text: 'Gehe weiter zu Beratung, Anprobe oder Vergleich.' }], faq: [{ question: 'Wie erkenne ich meine Gesichtsform?', answer: 'Vergleiche Stirn, Wangenknochen, Kiefer und Gesichtslänge. VisuTry schätzt die Form aus einem klaren Foto.' }, { question: 'Ist der Gesichtsform-Check kostenlos?', answer: 'Ja. Die Basisanalyse ist kostenlos und läuft im Browser.' }, { question: 'Was mache ich danach?', answer: 'Nutze die Form als ersten Filter und prüfe Breite, Glashöhe, Steg und Stil anschließend per Anprobe oder Vergleich.' }] },
    'find-glasses-for-my-face': { metaTitle: 'Brille für mein Gesicht per Foto finden | VisuTry', metaDescription: 'Analysiere dein Gesicht, grenze passende Fassungsrichtungen ein und bestätige die Auswahl per virtueller Anprobe oder Vergleich.', eyebrow: 'Fassungen mit einem Foto eingrenzen', title: 'Brille für mein Gesicht finden', intro: 'Mach aus einem Foto eine kleine, praktische Auswahl: Proportionen verstehen, Fassungsrichtungen eingrenzen und Kandidaten visuell prüfen.', steps: [{ title: 'Gesicht verstehen', text: 'Beginne mit dem kostenlosen Gesichtsform-Check.' }, { title: 'Fassungen eingrenzen', text: 'Konzentriere dich auf wenige Formen und Proportionen.' }, { title: 'Auf dem Foto prüfen', text: 'Nutze Anprobe oder direkten Vergleich.' }], faq: [{ question: 'Wie finde ich eine Brille, die zu meinem Gesicht passt?', answer: 'Starte mit den Proportionen und grenze Formen und Breiten ein. Eine Foto-Anprobe bestätigt die Auswahl.' }, { question: 'Soll ich nur nach Gesichtsform wählen?', answer: 'Nein. Breite, Steg, Glashöhe, Sehstärke und persönlicher Stil zählen ebenfalls.' }, { question: 'Kann ich mein eigenes Produktbild verwenden?', answer: 'Ja. Ein Produktbild oder Händler-Screenshot kann für die virtuelle Anprobe genutzt werden.' }] },
    'try-glasses-on-photo': { metaTitle: 'Brille online auf Foto anprobieren | VisuTry', metaDescription: 'Lade dein Gesichtsfoto und ein Brillenbild hoch, prüfe die Wirkung online und vergleiche bei Bedarf mehrere Fassungen.', eyebrow: 'Virtuelle Brillenansicht per Foto', title: 'Brille online auf deinem Foto anprobieren', intro: 'Prüfe eine konkrete Brille mit deinem Foto und einem Produktbild. Vergleiche Alternativen nebeneinander, wenn du mehr Sicherheit brauchst.', steps: [{ title: 'Gesichtsfoto hochladen', text: 'Nutze ein klares frontales Bild mit gleichmäßigem Licht.' }, { title: 'Brillenbild hinzufügen', text: 'Produktfoto oder Händler-Screenshot funktionieren.' }, { title: 'Bei Bedarf vergleichen', text: 'Wechsle zum Frame Compare, wenn eine Ansicht nicht reicht.' }], faq: [{ question: 'Kann ich eine Brille online auf meinem Foto anprobieren?', answer: 'Ja. Lade ein klares Gesichtsfoto und ein Produktbild der Brille hoch.' }, { question: 'Funktioniert ein Screenshot aus einem Shop?', answer: 'Ja. Prüfe vor dem Kauf Modell und tatsächliche Maße beim Händler.' }, { question: 'Wie vergleiche ich mehrere Brillen?', answer: 'Nutze Frame Compare, um Kandidaten direkt nebeneinander zu sehen.' }] },
    'ai-glasses-advisor': { metaTitle: 'KI-Brillenberater: Fassungen für dein Gesicht | VisuTry', metaDescription: 'Erhalte aus deinem Foto praktische Fassungs-Empfehlungen und bestätige die Auswahl mit virtueller Anprobe oder Vergleich.', eyebrow: 'Personalisierte Brillenberatung', title: 'KI-Brillenberater', intro: 'Grenze mit deinem Foto sinnvolle Fassungsrichtungen ein, verstehe die Gründe und bestätige die Auswahl anschließend visuell.', steps: [{ title: 'Gesicht verstehen', text: 'Nutze Proportionen als praktischen Ausgangspunkt.' }, { title: 'Fassungsberatung erhalten', text: 'Reduziere die Auswahl auf wenige sinnvolle Richtungen.' }, { title: 'Auswahl bestätigen', text: 'Nutze Anprobe und Vergleich vor der Entscheidung.' }], faq: [{ question: 'Was macht ein KI-Brillenberater?', answer: 'Er übersetzt sichtbare Gesichtsproportionen in praktische Vorschläge für Formen und Stile.' }, { question: 'Ist das dasselbe wie virtuelle Anprobe?', answer: 'Nein. Beratung grenzt ein; die Anprobe zeigt eine konkrete Fassung auf deinem Foto.' }, { question: 'Reicht die Gesichtsform allein?', answer: 'Nein. Breite, Glashöhe, Steg, Sehstärke und Stil sind ebenfalls wichtig.' }] },
    'what-glasses-suit-my-face': { metaTitle: 'Welche Brille passt zu meinem Gesicht? Foto-Check | VisuTry', metaDescription: 'Bestimme kostenlos deine Gesichtsform, grenze Fassungen ein und bestätige den Look per virtueller Anprobe oder Vergleich.', eyebrow: 'Brillenberatung mit Foto', title: 'Welche Brille passt zu meinem Gesicht?', intro: 'Nutze ein Foto, um die Gesichtsform einzugrenzen, passende Fassungen zu wählen und den Look anschließend visuell zu prüfen.', steps: [{ title: 'Gesichtsform erkennen', text: 'Nutze den kostenlosen lokalen Check ohne Anmeldung.' }, { title: 'Fassungsformen eingrenzen', text: 'Reduziere die Auswahl auf wenige Formen.' }, { title: 'Auf deinem Foto prüfen', text: 'Prüfe Maßstab und Stil per Anprobe oder Vergleich.' }], faq: [{ question: 'Woher weiß ich, welche Brille mir steht?', answer: 'Nutze die Gesichtsform als ersten Filter und prüfe anschließend Form, Breite und Wirkung auf deinem Foto.' }, { question: 'Brauche ich ein Foto?', answer: 'Für Analyse und Anprobe ist ein Foto hilfreich; du kannst aber zuerst die Ratgeber lesen.' }, { question: 'Ist die Gesichtsform genug?', answer: 'Nein. Breite, Steg, Glashöhe, Komfort und Sehstärke spielen ebenfalls eine Rolle.' }] },
    'virtual-glasses-try-on': { metaTitle: 'Virtuelle Brillenanprobe mit deinem Foto | VisuTry', metaDescription: 'Probiere Brillen online mit deinem Gesichtsfoto und einem beliebigen Produktbild an und vergleiche Alternativen vor dem Kauf.', eyebrow: 'Virtuelle Anprobe mit deinem Foto', title: 'Brille online virtuell anprobieren', intro: 'Sieh vor dem Kauf, wie eine Fassung auf deinem Gesicht wirkt. Lade Foto und Brillenbild hoch und vergleiche bei Bedarf Alternativen.', steps: [{ title: 'Foto hochladen', text: 'Nutze ein frontales Gesichtsfoto bei gleichmäßigem Licht.' }, { title: 'Brillenbild hinzufügen', text: 'Produktfoto oder Händler-Screenshot funktionieren.' }, { title: 'Vorschau prüfen', text: 'Beurteile den Look und vergleiche bei Bedarf Alternativen.' }], faq: [{ question: 'Kann ich Brillen online auf meinem Foto anprobieren?', answer: 'Ja. Lade Gesichtsfoto und Produktbild hoch, um den Look zu prüfen.' }, { question: 'Brauche ich einen Markenkatalog?', answer: 'Nein. Eigene Produktbilder und Händler-Screenshots funktionieren.' }, { question: 'Wie vergleiche ich mehrere Modelle?', answer: 'Nutze nach der Anprobe Frame Compare für eine direkte Gegenüberstellung.' }] },
    'compare-glasses-frames': { metaTitle: 'Brillenfassungen auf deinem Foto vergleichen | VisuTry', metaDescription: 'Vergleiche bis zu vier Fassungen als KI-Anprobe direkt nebeneinander auf deinem Foto.', eyebrow: 'Fassungen direkt vergleichen', title: 'Brillenfassungen auf deinem Foto vergleichen', intro: 'Wenn eine einzelne Anprobe nicht reicht, stelle mehrere Fassungsrichtungen nebeneinander und entscheide anhand eines direkten Vergleichs.', steps: [{ title: 'Ein Foto hochladen', text: 'Nutze ein klares frontales Gesichtsfoto.' }, { title: 'Bis zu vier Fassungen wählen', text: 'Wähle Presets mit klar erkennbaren Unterschieden.' }, { title: 'Nebeneinander prüfen', text: 'Vergleiche auf einer gemeinsamen Ansicht statt aus dem Gedächtnis.' }], faq: [{ question: 'Wie vergleiche ich Brillenfassungen online?', answer: 'Lade ein Foto hoch, wähle bis zu vier Presets und erzeuge die Ergebnisse nebeneinander.' }, { question: 'Ist das besser als einzelne Anproben?', answer: 'Bei ähnlichen Kandidaten ist der direkte Vergleich hilfreich; für ein konkretes Produkt reicht oft die Einzelanprobe.' }, { question: 'Muss ich meine Gesichtsform zuerst kennen?', answer: 'Nein. Du kannst direkt vergleichen oder vorher mit dem kostenlosen Check eingrenzen.' }] },
  },
  fr: {
    'what-is-my-face-shape': { metaTitle: 'Quelle est la forme de mon visage ? Test photo gratuit | VisuTry', metaDescription: 'Estimez gratuitement la forme de votre visage à partir d’une photo, puis utilisez le résultat pour choisir des lunettes.', eyebrow: 'Vérification gratuite par photo', title: 'Quelle est la forme de mon visage ?', intro: 'Utilisez une photo nette pour estimer votre forme de visage et transformer le résultat en conseils pratiques pour vos lunettes.', steps: [{ title: 'Choisir une photo', text: 'Utilisez une photo de face où tout le visage est visible.' }, { title: 'Détecter la forme', text: 'Le détecteur gratuit fonctionne localement dans le navigateur.' }, { title: 'Utiliser le résultat', text: 'Continuez vers les conseils, l’essayage ou la comparaison.' }], faq: [{ question: 'Comment connaître la forme de mon visage ?', answer: 'Comparez la largeur du front, des pommettes et de la mâchoire avec la longueur du visage. VisuTry peut l’estimer sur une photo nette.' }, { question: 'Le détecteur est-il gratuit ?', answer: 'Oui. La détection de base est gratuite et s’exécute dans le navigateur.' }, { question: 'Que faire ensuite ?', answer: 'Utilisez la forme comme premier filtre, puis vérifiez largeur, profondeur des verres, pont et style avec l’essayage ou la comparaison.' }] },
    'find-glasses-for-my-face': { metaTitle: 'Trouver des lunettes pour mon visage à partir d’une photo | VisuTry', metaDescription: 'Analysez votre visage, réduisez les styles de montures à tester puis validez-les par essayage virtuel ou comparaison.', eyebrow: 'Présélection de montures par photo', title: 'Trouver des lunettes pour mon visage', intro: 'Transformez une photo en sélection pratique : comprenez vos proportions, réduisez les directions de montures et validez les finalistes visuellement.', steps: [{ title: 'Comprendre votre visage', text: 'Commencez par le détecteur gratuit de forme du visage.' }, { title: 'Réduire les options', text: 'Concentrez-vous sur quelques formes et proportions.' }, { title: 'Valider sur votre photo', text: 'Utilisez l’essayage ou la comparaison côte à côte.' }], faq: [{ question: 'Comment trouver des lunettes qui me vont ?', answer: 'Partez des proportions du visage, réduisez formes et largeurs, puis confirmez avec un essayage sur photo.' }, { question: 'Dois-je choisir uniquement selon la forme du visage ?', answer: 'Non. Largeur, pont, hauteur des verres, correction et style comptent aussi.' }, { question: 'Puis-je utiliser ma propre image produit ?', answer: 'Oui. Une photo produit ou une capture d’écran d’un marchand peut servir à l’essayage virtuel.' }] },
    'try-glasses-on-photo': { metaTitle: 'Essayer des lunettes en ligne sur une photo | VisuTry', metaDescription: 'Importez votre photo et une image de lunettes, visualisez le rendu puis comparez plusieurs montures si nécessaire.', eyebrow: 'Aperçu virtuel sur votre photo', title: 'Essayer des lunettes en ligne sur votre photo', intro: 'Testez une paire précise avec votre photo et une image produit, puis comparez les alternatives côte à côte si vous hésitez.', steps: [{ title: 'Importer votre photo', text: 'Utilisez une photo nette, de face et bien éclairée.' }, { title: 'Ajouter l’image des lunettes', text: 'Une photo produit ou une capture d’écran convient.' }, { title: 'Comparer si nécessaire', text: 'Passez à Frame Compare si un seul aperçu ne suffit pas.' }], faq: [{ question: 'Puis-je essayer des lunettes sur une photo ?', answer: 'Oui. Importez une photo de votre visage et une image produit pour voir le rendu.' }, { question: 'Une capture d’écran de boutique fonctionne-t-elle ?', answer: 'Oui. Vérifiez toutefois la taille et la référence exactes auprès du vendeur.' }, { question: 'Comment comparer plusieurs paires ?', answer: 'Utilisez Frame Compare pour voir plusieurs candidats côte à côte.' }] },
    'ai-glasses-advisor': { metaTitle: 'Conseiller lunettes IA : trouver des montures adaptées | VisuTry', metaDescription: 'Transformez votre photo en conseils de montures puis validez la sélection par essayage virtuel ou comparaison.', eyebrow: 'Conseils lunettes personnalisés', title: 'Conseiller lunettes IA', intro: 'Utilisez votre photo pour réduire les directions de montures intéressantes, comprendre pourquoi elles peuvent fonctionner puis les valider visuellement.', steps: [{ title: 'Comprendre votre visage', text: 'Utilisez les proportions comme point de départ pratique.' }, { title: 'Recevoir des conseils', text: 'Réduisez le choix à quelques directions de montures.' }, { title: 'Valider la sélection', text: 'Utilisez l’essayage et la comparaison avant de décider.' }], faq: [{ question: 'Que fait un conseiller lunettes IA ?', answer: 'Il transforme les proportions visibles du visage en recommandations pratiques de formes et de styles.' }, { question: 'Est-ce la même chose que l’essayage virtuel ?', answer: 'Non. Le conseiller réduit les options ; l’essayage montre une monture précise sur votre photo.' }, { question: 'La forme du visage suffit-elle ?', answer: 'Non. Largeur, profondeur, pont, correction et préférences comptent aussi.' }] },
    'what-glasses-suit-my-face': { metaTitle: 'Quelles lunettes me vont ? Trouver avec une photo | VisuTry', metaDescription: 'Détectez gratuitement votre forme de visage, réduisez les montures puis confirmez le rendu avec essayage ou comparaison.', eyebrow: 'Conseils lunettes à partir d’une photo', title: 'Quelles lunettes vont à mon visage ?', intro: 'Utilisez une photo pour estimer votre forme de visage, créer une petite sélection de montures puis confirmer le rendu visuellement.', steps: [{ title: 'Détecter votre forme', text: 'Utilisez le détecteur gratuit dans le navigateur, sans connexion.' }, { title: 'Réduire les formes', text: 'Concentrez-vous d’abord sur quelques silhouettes.' }, { title: 'Valider sur votre photo', text: 'Vérifiez l’échelle et le style par essayage ou comparaison.' }], faq: [{ question: 'Comment savoir quelles lunettes me vont ?', answer: 'Commencez par la forme du visage, réduisez les silhouettes puis validez largeur et style sur votre photo.' }, { question: 'Ai-je besoin d’une photo ?', answer: 'Elle aide pour la détection et l’essayage, mais vous pouvez d’abord lire les guides.' }, { question: 'La forme du visage suffit-elle ?', answer: 'Non. Vérifiez aussi largeur, pont, profondeur, confort, correction et style.' }] },
    'virtual-glasses-try-on': { metaTitle: 'Essayage virtuel de lunettes avec votre photo | VisuTry', metaDescription: 'Essayez des lunettes en ligne avec votre photo et n’importe quelle image produit, puis comparez les alternatives avant achat.', eyebrow: 'Essayage virtuel avec votre photo', title: 'Essayer des lunettes virtuellement en ligne', intro: 'Voyez le rendu d’une monture sur votre visage avant d’acheter. Importez votre photo et une image de lunettes, puis comparez si besoin.', steps: [{ title: 'Importer votre photo', text: 'Utilisez une photo de face avec un éclairage uniforme.' }, { title: 'Ajouter une image de lunettes', text: 'Photo produit ou capture d’écran de marchand.' }, { title: 'Prévisualiser et décider', text: 'Vérifiez le rendu puis comparez les alternatives si nécessaire.' }], faq: [{ question: 'Puis-je essayer des lunettes sur ma photo en ligne ?', answer: 'Oui. Importez votre photo et une image produit pour visualiser le rendu.' }, { question: 'Ai-je besoin du catalogue de la marque ?', answer: 'Non. Vos propres images produit et captures d’écran conviennent.' }, { question: 'Comment comparer plusieurs paires ?', answer: 'Après l’essayage, utilisez Frame Compare pour les voir côte à côte.' }] },
    'compare-glasses-frames': { metaTitle: 'Comparer des montures côte à côte sur votre photo | VisuTry', metaDescription: 'Comparez jusqu’à quatre montures avec des résultats d’essayage IA côte à côte sur votre photo.', eyebrow: 'Décider avec une comparaison côte à côte', title: 'Comparer des montures sur votre photo', intro: 'Quand un seul essayage ne suffit pas, comparez plusieurs directions de montures ensemble et choisissez celle qui vous convient le mieux.', steps: [{ title: 'Importer une photo', text: 'Utilisez une photo nette et de face.' }, { title: 'Choisir jusqu’à quatre montures', text: 'Sélectionnez des préréglages suffisamment différents.' }, { title: 'Comparer côte à côte', text: 'Décidez sur une même vue plutôt que de mémoire.' }], faq: [{ question: 'Comment comparer des montures en ligne ?', answer: 'Importez une photo, sélectionnez jusqu’à quatre préréglages et générez les résultats côte à côte.' }, { question: 'Est-ce mieux qu’un essayage à la fois ?', answer: 'La comparaison directe aide quand plusieurs silhouettes sont proches. Pour un produit précis, l’essayage simple suffit souvent.' }, { question: 'Dois-je connaître ma forme de visage avant ?', answer: 'Non. Vous pouvez comparer directement ou utiliser d’abord le détecteur gratuit.' }] },
  },
  es: {
    'what-is-my-face-shape': { metaTitle: '¿Cuál es la forma de mi cara? Detector gratis con foto | VisuTry', metaDescription: 'Estima gratis la forma de tu rostro con una foto y usa el resultado para elegir monturas y probar gafas.', eyebrow: 'Comprobación facial gratuita con foto', title: '¿Cuál es la forma de mi cara?', intro: 'Usa una foto clara para estimar la forma de tu rostro y convertir el resultado en una guía práctica para elegir gafas.', steps: [{ title: 'Elige una foto', text: 'Usa una foto frontal con todo el rostro visible.' }, { title: 'Detecta la forma', text: 'El detector gratuito funciona en tu navegador.' }, { title: 'Usa el resultado', text: 'Continúa a consejos, prueba virtual o comparación.' }], faq: [{ question: '¿Cómo puedo saber la forma de mi cara?', answer: 'Compara frente, pómulos, mandíbula y longitud del rostro. VisuTry puede estimarla con una foto clara.' }, { question: '¿El detector es gratis?', answer: 'Sí. La detección básica es gratuita y se procesa en el navegador.' }, { question: '¿Qué hago después?', answer: 'Úsala como primer filtro y después revisa ancho, profundidad, puente y estilo con prueba o comparación.' }] },
    'find-glasses-for-my-face': { metaTitle: 'Encontrar gafas para mi cara a partir de una foto | VisuTry', metaDescription: 'Analiza tu rostro, reduce las opciones de montura y valida la selección con prueba virtual o comparación.', eyebrow: 'Preselección de monturas con foto', title: 'Encontrar gafas para mi cara', intro: 'Convierte una foto en una selección práctica: entiende tus proporciones, reduce las direcciones de montura y valida los finalistas visualmente.', steps: [{ title: 'Entiende tu rostro', text: 'Empieza con el detector gratuito de forma facial.' }, { title: 'Reduce opciones', text: 'Concéntrate en pocas formas y proporciones.' }, { title: 'Valida en tu foto', text: 'Usa prueba virtual o comparación lado a lado.' }], faq: [{ question: '¿Cómo encuentro gafas que me queden bien?', answer: 'Empieza por las proporciones, reduce formas y anchos y confirma con una prueba sobre tu foto.' }, { question: '¿Debo elegir solo por la forma de la cara?', answer: 'No. También importan ancho, puente, profundidad, graduación y estilo.' }, { question: '¿Puedo usar mi propia imagen de producto?', answer: 'Sí. Puedes usar una foto de producto o captura de una tienda para la prueba virtual.' }] },
    'try-glasses-on-photo': { metaTitle: 'Probar gafas online en una foto | VisuTry', metaDescription: 'Sube tu foto y una imagen de gafas, comprueba el resultado online y compara varias monturas si lo necesitas.', eyebrow: 'Vista virtual de gafas con foto', title: 'Probar gafas online en tu foto', intro: 'Prueba una montura concreta con tu foto y una imagen de producto, y compara alternativas lado a lado si aún dudas.', steps: [{ title: 'Sube tu foto', text: 'Usa una imagen frontal, clara y bien iluminada.' }, { title: 'Añade la imagen de gafas', text: 'Sirve una foto de producto o captura de una tienda.' }, { title: 'Compara si hace falta', text: 'Pasa a Frame Compare si una sola vista no basta.' }], faq: [{ question: '¿Puedo probar gafas en una foto online?', answer: 'Sí. Sube una foto de tu cara y una imagen de producto para ver el resultado.' }, { question: '¿Sirve una captura de una tienda?', answer: 'Sí. Confirma talla y modelo exactos con el vendedor antes de comprar.' }, { question: '¿Cómo comparo más de un par?', answer: 'Usa Frame Compare para revisar candidatos lado a lado.' }] },
    'ai-glasses-advisor': { metaTitle: 'Asesor de gafas con IA: monturas para tu rostro | VisuTry', metaDescription: 'Convierte tu foto en orientación práctica sobre monturas y valida la selección con prueba virtual o comparación.', eyebrow: 'Orientación personalizada de gafas', title: 'Asesor de gafas con IA', intro: 'Usa tu foto para reducir las direcciones de montura que vale la pena probar, entender por qué y validarlas visualmente.', steps: [{ title: 'Entiende tu rostro', text: 'Usa las proporciones como punto de partida práctico.' }, { title: 'Recibe orientación', text: 'Reduce la selección a unas pocas direcciones.' }, { title: 'Valida la selección', text: 'Usa prueba virtual y comparación antes de decidir.' }], faq: [{ question: '¿Qué hace un asesor de gafas con IA?', answer: 'Convierte las proporciones visibles del rostro en recomendaciones prácticas de formas y estilos.' }, { question: '¿Es lo mismo que una prueba virtual?', answer: 'No. El asesor reduce opciones; la prueba muestra una montura concreta en tu foto.' }, { question: '¿Basta con la forma del rostro?', answer: 'No. También cuentan ancho, profundidad, puente, graduación y preferencias.' }] },
    'what-glasses-suit-my-face': { metaTitle: '¿Qué gafas me quedan bien? Usa una foto para elegir | VisuTry', metaDescription: 'Detecta gratis la forma de tu cara, reduce las monturas y confirma el resultado con prueba virtual o comparación.', eyebrow: 'Consejo de gafas basado en foto', title: '¿Qué gafas le quedan bien a mi cara?', intro: 'Usa una foto para estimar tu forma facial, crear una selección pequeña de monturas y confirmar el resultado visualmente.', steps: [{ title: 'Detecta tu forma facial', text: 'Usa el detector gratuito en el navegador sin iniciar sesión.' }, { title: 'Reduce las formas', text: 'Concéntrate primero en unas pocas siluetas.' }, { title: 'Valida en tu foto', text: 'Comprueba escala y estilo con prueba o comparación.' }], faq: [{ question: '¿Cómo sé qué gafas me quedan bien?', answer: 'Empieza con la forma facial, reduce las siluetas y valida ancho y estilo en tu foto.' }, { question: '¿Necesito subir una foto?', answer: 'Ayuda para detección y prueba virtual, aunque puedes leer primero las guías.' }, { question: '¿La forma facial es suficiente?', answer: 'No. Revisa también ancho, puente, profundidad, comodidad, graduación y estilo.' }] },
    'virtual-glasses-try-on': { metaTitle: 'Prueba virtual de gafas con tu foto | VisuTry', metaDescription: 'Prueba gafas online con tu foto y cualquier imagen de producto, y compara alternativas antes de comprar.', eyebrow: 'Prueba virtual con tu foto', title: 'Probar gafas virtualmente online', intro: 'Mira cómo queda una montura en tu rostro antes de comprar. Sube tu foto y una imagen de gafas y compara alternativas si hace falta.', steps: [{ title: 'Sube tu foto', text: 'Usa una foto frontal con iluminación uniforme.' }, { title: 'Añade una imagen de gafas', text: 'Sirve una foto de producto o captura de tienda.' }, { title: 'Previsualiza y decide', text: 'Comprueba el resultado y compara alternativas si lo necesitas.' }], faq: [{ question: '¿Puedo probar gafas online en mi foto?', answer: 'Sí. Sube tu foto y una imagen de producto para visualizar el resultado.' }, { question: '¿Necesito el catálogo de la marca?', answer: 'No. Funcionan tus propias imágenes de producto y capturas de tienda.' }, { question: '¿Cómo comparo varios pares?', answer: 'Después de la prueba, usa Frame Compare para verlos lado a lado.' }] },
    'compare-glasses-frames': { metaTitle: 'Comparar monturas lado a lado en tu foto | VisuTry', metaDescription: 'Compara hasta cuatro monturas con resultados de prueba IA lado a lado sobre tu foto.', eyebrow: 'Decisiones lado a lado', title: 'Comparar monturas de gafas en tu foto', intro: 'Cuando una sola prueba no basta, compara varias direcciones de montura juntas y elige la que mejor te funciona.', steps: [{ title: 'Sube una foto', text: 'Usa una foto frontal y clara.' }, { title: 'Elige hasta cuatro monturas', text: 'Selecciona presets suficientemente distintos.' }, { title: 'Revisa lado a lado', text: 'Decide en una misma vista, no de memoria.' }], faq: [{ question: '¿Cómo comparo monturas online?', answer: 'Sube una foto, elige hasta cuatro presets y genera los resultados lado a lado.' }, { question: '¿Es mejor que probar una a una?', answer: 'La comparación directa ayuda con opciones parecidas; para un producto concreto suele bastar una prueba individual.' }, { question: '¿Necesito saber antes mi forma facial?', answer: 'No. Puedes comparar directamente o usar primero el detector gratuito.' }] },
  },
  pt: {
    'what-is-my-face-shape': { metaTitle: 'Qual é o formato do meu rosto? Detector grátis por foto | VisuTry', metaDescription: 'Estime gratuitamente o formato do seu rosto com uma foto e use o resultado para escolher e experimentar óculos.', eyebrow: 'Verificação facial gratuita por foto', title: 'Qual é o formato do meu rosto?', intro: 'Use uma foto nítida para estimar o formato do rosto e transformar o resultado em orientação prática para escolher óculos.', steps: [{ title: 'Escolha uma foto', text: 'Use uma foto de frente com todo o rosto visível.' }, { title: 'Detecte o formato', text: 'O detector gratuito funciona no seu navegador.' }, { title: 'Use o resultado', text: 'Continue para orientação, prova virtual ou comparação.' }], faq: [{ question: 'Como saber o formato do meu rosto?', answer: 'Compare testa, maçãs do rosto, mandíbula e comprimento do rosto. O VisuTry pode estimar pela foto.' }, { question: 'O detector é grátis?', answer: 'Sim. A detecção básica é gratuita e roda no navegador.' }, { question: 'O que faço depois?', answer: 'Use como primeiro filtro e depois confira largura, profundidade, ponte e estilo com prova ou comparação.' }] },
    'find-glasses-for-my-face': { metaTitle: 'Encontrar óculos para meu rosto usando uma foto | VisuTry', metaDescription: 'Analise seu rosto, reduza as opções de armação e valide a seleção com prova virtual ou comparação.', eyebrow: 'Pré-seleção de armações por foto', title: 'Encontrar óculos para meu rosto', intro: 'Transforme uma foto em uma seleção prática: entenda suas proporções, reduza as direções de armação e valide os finalistas visualmente.', steps: [{ title: 'Entenda seu rosto', text: 'Comece com o detector gratuito de formato facial.' }, { title: 'Reduza as opções', text: 'Concentre-se em poucas formas e proporções.' }, { title: 'Valide na sua foto', text: 'Use prova virtual ou comparação lado a lado.' }], faq: [{ question: 'Como encontrar óculos que combinam comigo?', answer: 'Comece pelas proporções, reduza formas e larguras e confirme com uma prova na sua foto.' }, { question: 'Devo escolher só pelo formato do rosto?', answer: 'Não. Largura, ponte, profundidade, grau e estilo também importam.' }, { question: 'Posso usar minha própria imagem do produto?', answer: 'Sim. Uma foto do produto ou captura de loja pode ser usada na prova virtual.' }] },
    'try-glasses-on-photo': { metaTitle: 'Experimentar óculos online em uma foto | VisuTry', metaDescription: 'Envie sua foto e uma imagem dos óculos, veja o resultado online e compare várias armações se precisar.', eyebrow: 'Visualização virtual por foto', title: 'Experimentar óculos online na sua foto', intro: 'Teste uma armação específica com sua foto e uma imagem do produto, e compare alternativas lado a lado quando precisar de mais confiança.', steps: [{ title: 'Envie sua foto', text: 'Use uma imagem frontal, nítida e bem iluminada.' }, { title: 'Adicione a imagem dos óculos', text: 'Pode ser foto do produto ou captura de uma loja.' }, { title: 'Compare se necessário', text: 'Vá para o Frame Compare quando uma única visualização não bastar.' }], faq: [{ question: 'Posso experimentar óculos em uma foto online?', answer: 'Sim. Envie sua foto e uma imagem do produto para visualizar o resultado.' }, { question: 'Uma captura de loja funciona?', answer: 'Sim. Confirme tamanho e modelo exatos com o vendedor antes da compra.' }, { question: 'Como comparo mais de um par?', answer: 'Use o Frame Compare para ver candidatos lado a lado.' }] },
    'ai-glasses-advisor': { metaTitle: 'Consultor de óculos com IA: armações para seu rosto | VisuTry', metaDescription: 'Transforme sua foto em orientação prática de armações e valide a seleção com prova virtual ou comparação.', eyebrow: 'Orientação personalizada de óculos', title: 'Consultor de óculos com IA', intro: 'Use sua foto para reduzir as direções de armação que vale a pena testar, entender os motivos e validá-las visualmente.', steps: [{ title: 'Entenda seu rosto', text: 'Use as proporções como ponto de partida prático.' }, { title: 'Receba orientação', text: 'Reduza a seleção a poucas direções de armação.' }, { title: 'Valide a seleção', text: 'Use prova virtual e comparação antes de decidir.' }], faq: [{ question: 'O que faz um consultor de óculos com IA?', answer: 'Transforma proporções visíveis do rosto em recomendações práticas de formas e estilos.' }, { question: 'É igual à prova virtual?', answer: 'Não. O consultor reduz opções; a prova mostra uma armação específica na sua foto.' }, { question: 'Só o formato do rosto basta?', answer: 'Não. Largura, profundidade, ponte, grau e preferências também contam.' }] },
    'what-glasses-suit-my-face': { metaTitle: 'Quais óculos combinam com meu rosto? Use uma foto | VisuTry', metaDescription: 'Detecte grátis o formato do rosto, reduza as armações e confirme o visual com prova virtual ou comparação.', eyebrow: 'Orientação de óculos por foto', title: 'Quais óculos combinam com meu rosto?', intro: 'Use uma foto para estimar seu formato facial, criar uma pequena seleção de armações e confirmar o visual na sua própria imagem.', steps: [{ title: 'Detecte seu formato facial', text: 'Use o detector gratuito no navegador, sem login.' }, { title: 'Reduza as formas', text: 'Concentre-se primeiro em poucas silhuetas.' }, { title: 'Valide na sua foto', text: 'Confira escala e estilo com prova ou comparação.' }], faq: [{ question: 'Como saber quais óculos combinam comigo?', answer: 'Comece pelo formato do rosto, reduza as silhuetas e valide largura e estilo na sua foto.' }, { question: 'Preciso enviar uma foto?', answer: 'Ela ajuda na detecção e prova virtual, mas você pode ler os guias primeiro.' }, { question: 'O formato facial é suficiente?', answer: 'Não. Confira também largura, ponte, profundidade, conforto, grau e estilo.' }] },
    'virtual-glasses-try-on': { metaTitle: 'Prova virtual de óculos com sua foto | VisuTry', metaDescription: 'Experimente óculos online com sua foto e qualquer imagem de produto e compare alternativas antes de comprar.', eyebrow: 'Prova virtual com sua foto', title: 'Experimentar óculos virtualmente online', intro: 'Veja como uma armação fica no seu rosto antes de comprar. Envie sua foto e uma imagem dos óculos e compare alternativas se precisar.', steps: [{ title: 'Envie sua foto', text: 'Use uma foto frontal com iluminação uniforme.' }, { title: 'Adicione uma imagem dos óculos', text: 'Pode ser foto do produto ou captura da loja.' }, { title: 'Visualize e decida', text: 'Confira o resultado e compare alternativas se necessário.' }], faq: [{ question: 'Posso experimentar óculos online na minha foto?', answer: 'Sim. Envie sua foto e uma imagem do produto para visualizar o resultado.' }, { question: 'Preciso do catálogo da marca?', answer: 'Não. Suas próprias imagens de produto e capturas de loja funcionam.' }, { question: 'Como comparo vários pares?', answer: 'Depois da prova, use o Frame Compare para vê-los lado a lado.' }] },
    'compare-glasses-frames': { metaTitle: 'Comparar armações lado a lado na sua foto | VisuTry', metaDescription: 'Compare até quatro armações com resultados de prova por IA lado a lado na sua foto.', eyebrow: 'Decisão lado a lado', title: 'Comparar armações de óculos na sua foto', intro: 'Quando uma única prova não basta, compare várias direções de armação juntas e escolha a que funciona melhor para você.', steps: [{ title: 'Envie uma foto', text: 'Use uma foto frontal e nítida.' }, { title: 'Escolha até quatro armações', text: 'Selecione presets suficientemente diferentes.' }, { title: 'Veja lado a lado', text: 'Decida em uma mesma tela, não de memória.' }], faq: [{ question: 'Como comparar armações online?', answer: 'Envie uma foto, escolha até quatro presets e gere os resultados lado a lado.' }, { question: 'É melhor do que provar uma por vez?', answer: 'A comparação direta ajuda com opções parecidas; para um produto específico, a prova individual costuma bastar.' }, { question: 'Preciso saber meu formato facial primeiro?', answer: 'Não. Você pode comparar direto ou usar o detector gratuito antes.' }] },
  },
  id: {
    'what-is-my-face-shape': { metaTitle: 'Apa bentuk wajah saya? Detektor foto gratis | VisuTry', metaDescription: 'Perkirakan bentuk wajah gratis dari satu foto lalu gunakan hasilnya untuk memilih dan mencoba kacamata.', eyebrow: 'Cek bentuk wajah gratis dari foto', title: 'Apa Bentuk Wajah Saya?', intro: 'Gunakan satu foto yang jelas untuk memperkirakan bentuk wajah dan mengubah hasilnya menjadi panduan praktis memilih kacamata.', steps: [{ title: 'Pilih satu foto', text: 'Gunakan foto lurus dari depan dengan seluruh wajah terlihat.' }, { title: 'Deteksi bentuk', text: 'Detektor gratis berjalan di browser Anda.' }, { title: 'Gunakan hasilnya', text: 'Lanjutkan ke saran, try-on, atau perbandingan.' }], faq: [{ question: 'Bagaimana mengetahui bentuk wajah saya?', answer: 'Bandingkan lebar dahi, tulang pipi, rahang, dan panjang wajah. VisuTry dapat memperkirakannya dari foto yang jelas.' }, { question: 'Apakah detektor ini gratis?', answer: 'Ya. Deteksi dasar gratis dan diproses di browser.' }, { question: 'Apa yang dilakukan setelah tahu bentuk wajah?', answer: 'Gunakan sebagai filter awal, lalu cek lebar frame, kedalaman lensa, bridge, dan gaya dengan try-on atau compare.' }] },
    'find-glasses-for-my-face': { metaTitle: 'Cari kacamata untuk wajah saya dari foto | VisuTry', metaDescription: 'Analisis wajah, persempit arah frame, lalu validasi pilihan dengan virtual try-on atau perbandingan berdampingan.', eyebrow: 'Shortlist frame dari foto', title: 'Cari Kacamata untuk Wajah Saya', intro: 'Ubah satu foto menjadi shortlist praktis: pahami proporsi wajah, persempit arah frame, lalu validasi kandidat secara visual.', steps: [{ title: 'Pahami wajah Anda', text: 'Mulai dengan detektor bentuk wajah gratis.' }, { title: 'Persempit pilihan frame', text: 'Fokus pada beberapa bentuk dan proporsi.' }, { title: 'Validasi pada foto', text: 'Gunakan try-on atau perbandingan berdampingan.' }], faq: [{ question: 'Bagaimana mencari kacamata yang cocok?', answer: 'Mulai dari proporsi wajah, persempit bentuk dan lebar frame, lalu konfirmasi dengan try-on foto.' }, { question: 'Apakah cukup memilih dari bentuk wajah?', answer: 'Tidak. Lebar, bridge, kedalaman lensa, kebutuhan resep, dan gaya juga penting.' }, { question: 'Bisakah memakai gambar produk sendiri?', answer: 'Ya. Foto produk atau screenshot toko dapat dipakai untuk virtual try-on.' }] },
    'try-glasses-on-photo': { metaTitle: 'Coba kacamata online pada foto | VisuTry', metaDescription: 'Unggah foto wajah dan gambar kacamata, lihat hasilnya online, lalu bandingkan beberapa frame bila perlu.', eyebrow: 'Preview kacamata virtual dari foto', title: 'Coba Kacamata Online pada Foto Anda', intro: 'Uji satu frame tertentu dengan foto Anda dan gambar produk, lalu bandingkan alternatif berdampingan jika masih ragu.', steps: [{ title: 'Unggah foto wajah', text: 'Gunakan foto depan yang jelas dengan cahaya merata.' }, { title: 'Tambahkan gambar kacamata', text: 'Gunakan foto produk atau screenshot toko.' }, { title: 'Bandingkan bila perlu', text: 'Buka Frame Compare jika satu preview belum cukup.' }], faq: [{ question: 'Bisakah mencoba kacamata pada foto online?', answer: 'Ya. Unggah foto wajah dan gambar produk untuk melihat tampilannya.' }, { question: 'Apakah screenshot toko bisa dipakai?', answer: 'Ya. Pastikan ukuran dan model sebenarnya dengan penjual sebelum membeli.' }, { question: 'Bagaimana membandingkan beberapa pasang?', answer: 'Gunakan Frame Compare untuk melihat kandidat berdampingan.' }] },
    'ai-glasses-advisor': { metaTitle: 'AI Glasses Advisor: frame untuk wajah Anda | VisuTry', metaDescription: 'Ubah foto menjadi panduan frame praktis lalu validasi shortlist dengan virtual try-on atau perbandingan.', eyebrow: 'Panduan kacamata personal', title: 'AI Glasses Advisor', intro: 'Gunakan foto untuk mempersempit arah frame yang layak dicoba, memahami alasannya, lalu memvalidasi shortlist secara visual.', steps: [{ title: 'Pahami wajah Anda', text: 'Gunakan proporsi sebagai titik awal praktis.' }, { title: 'Dapatkan panduan frame', text: 'Persempit pilihan menjadi beberapa arah utama.' }, { title: 'Validasi shortlist', text: 'Gunakan try-on dan compare sebelum memutuskan.' }], faq: [{ question: 'Apa fungsi AI Glasses Advisor?', answer: 'Mengubah proporsi wajah yang terlihat menjadi rekomendasi praktis untuk bentuk dan gaya frame.' }, { question: 'Apakah sama dengan virtual try-on?', answer: 'Tidak. Advisor mempersempit opsi; try-on menunjukkan frame tertentu pada foto Anda.' }, { question: 'Apakah bentuk wajah saja cukup?', answer: 'Tidak. Lebar, kedalaman lensa, bridge, resep, dan preferensi juga perlu dipertimbangkan.' }] },
    'what-glasses-suit-my-face': { metaTitle: 'Kacamata apa yang cocok untuk wajah saya? Gunakan foto | VisuTry', metaDescription: 'Deteksi bentuk wajah gratis, persempit frame, lalu konfirmasi tampilan dengan virtual try-on atau perbandingan.', eyebrow: 'Saran kacamata dari foto', title: 'Kacamata Apa yang Cocok untuk Wajah Saya?', intro: 'Gunakan satu foto untuk memperkirakan bentuk wajah, membuat shortlist frame, lalu memastikan tampilannya pada foto Anda sendiri.', steps: [{ title: 'Deteksi bentuk wajah', text: 'Gunakan detektor gratis di browser tanpa login.' }, { title: 'Persempit bentuk frame', text: 'Fokus dulu pada beberapa siluet.' }, { title: 'Validasi pada foto', text: 'Cek skala dan gaya dengan try-on atau compare.' }], faq: [{ question: 'Bagaimana tahu kacamata yang cocok?', answer: 'Mulai dari bentuk wajah, persempit siluet, lalu validasi lebar dan gaya pada foto Anda.' }, { question: 'Apakah perlu mengunggah foto?', answer: 'Foto membantu untuk deteksi dan try-on, tetapi Anda bisa membaca panduan dulu.' }, { question: 'Apakah bentuk wajah cukup?', answer: 'Tidak. Cek juga lebar, bridge, kedalaman, kenyamanan, resep, dan gaya.' }] },
    'virtual-glasses-try-on': { metaTitle: 'Virtual try-on kacamata dengan foto Anda | VisuTry', metaDescription: 'Coba kacamata online dengan foto Anda dan gambar produk apa pun, lalu bandingkan alternatif sebelum membeli.', eyebrow: 'Virtual try-on dengan foto Anda', title: 'Coba Kacamata Secara Virtual Online', intro: 'Lihat bagaimana frame terlihat di wajah Anda sebelum membeli. Unggah foto dan gambar kacamata, lalu bandingkan alternatif bila perlu.', steps: [{ title: 'Unggah foto', text: 'Gunakan foto wajah dari depan dengan cahaya merata.' }, { title: 'Tambahkan gambar kacamata', text: 'Gunakan foto produk atau screenshot toko.' }, { title: 'Preview dan putuskan', text: 'Cek tampilan lalu bandingkan alternatif bila perlu.' }], faq: [{ question: 'Bisakah mencoba kacamata online pada foto saya?', answer: 'Ya. Unggah foto dan gambar produk untuk melihat tampilannya.' }, { question: 'Apakah perlu katalog merek?', answer: 'Tidak. Gambar produk sendiri dan screenshot toko bisa digunakan.' }, { question: 'Bagaimana membandingkan beberapa pasang?', answer: 'Setelah try-on, gunakan Frame Compare untuk melihatnya berdampingan.' }] },
    'compare-glasses-frames': { metaTitle: 'Bandingkan frame kacamata berdampingan pada foto | VisuTry', metaDescription: 'Bandingkan hingga empat frame dengan hasil AI try-on berdampingan pada foto Anda.', eyebrow: 'Keputusan frame berdampingan', title: 'Bandingkan Frame Kacamata pada Foto Anda', intro: 'Jika satu try-on belum cukup, bandingkan beberapa arah frame bersama-sama dan pilih yang paling cocok.', steps: [{ title: 'Unggah satu foto', text: 'Gunakan foto wajah yang jelas dari depan.' }, { title: 'Pilih hingga empat frame', text: 'Pilih preset dengan perbedaan yang cukup jelas.' }, { title: 'Tinjau berdampingan', text: 'Putuskan pada satu papan, bukan dari ingatan.' }], faq: [{ question: 'Bagaimana membandingkan frame online?', answer: 'Unggah satu foto, pilih hingga empat preset, lalu hasilkan try-on berdampingan.' }, { question: 'Apakah lebih baik daripada mencoba satu per satu?', answer: 'Perbandingan langsung membantu untuk kandidat yang mirip; satu try-on cocok untuk produk tertentu.' }, { question: 'Apakah harus tahu bentuk wajah dulu?', answer: 'Tidak. Anda bisa langsung compare atau memakai detektor gratis terlebih dahulu.' }] },
  },
  ru: {
    'what-is-my-face-shape': { metaTitle: 'Какая у меня форма лица? Бесплатно по фото | VisuTry', metaDescription: 'Определите вероятную форму лица по одной фотографии и используйте результат для выбора и примерки очков.', eyebrow: 'Бесплатная проверка формы лица по фото', title: 'Какая у меня форма лица?', intro: 'Используйте чёткое фото, чтобы оценить форму лица и сразу превратить результат в практическую помощь при выборе очков.', steps: [{ title: 'Выберите фото', text: 'Подойдёт фронтальное фото, где лицо видно полностью.' }, { title: 'Определите форму', text: 'Бесплатный анализ выполняется в браузере.' }, { title: 'Используйте результат', text: 'Перейдите к советам, примерке или сравнению.' }], faq: [{ question: 'Как понять форму моего лица?', answer: 'Сравните ширину лба, скул и челюсти с длиной лица. VisuTry оценивает форму по чёткому фото.' }, { question: 'Определение бесплатное?', answer: 'Да. Базовый анализ бесплатный и выполняется в браузере.' }, { question: 'Что делать после определения?', answer: 'Используйте форму как первый фильтр, затем проверяйте ширину оправы, высоту линз, мост и стиль через примерку или сравнение.' }] },
    'find-glasses-for-my-face': { metaTitle: 'Найти очки для моего лица по фото | VisuTry', metaDescription: 'Оцените лицо, сузьте варианты оправ и проверьте выбор с помощью виртуальной примерки или сравнения.', eyebrow: 'Подбор оправ по фотографии', title: 'Найти очки для моего лица', intro: 'Превратите одно фото в практичный короткий список: поймите пропорции, сузьте направления оправ и визуально проверьте финалистов.', steps: [{ title: 'Поймите пропорции лица', text: 'Начните с бесплатного определения формы.' }, { title: 'Сузьте выбор оправ', text: 'Сосредоточьтесь на нескольких формах и пропорциях.' }, { title: 'Проверьте на фото', text: 'Используйте примерку или сравнение рядом.' }], faq: [{ question: 'Как найти очки, которые мне подходят?', answer: 'Начните с пропорций лица, сузьте формы и ширину, затем подтвердите выбор примеркой по фото.' }, { question: 'Нужно выбирать только по форме лица?', answer: 'Нет. Важны ширина, мост, высота линз, рецепт и личный стиль.' }, { question: 'Можно использовать своё изображение товара?', answer: 'Да. Подойдёт фото оправы или скриншот магазина.' }] },
    'try-glasses-on-photo': { metaTitle: 'Примерить очки онлайн на своей фотографии | VisuTry', metaDescription: 'Загрузите фото лица и изображение очков, оцените результат и при необходимости сравните несколько оправ.', eyebrow: 'Виртуальная примерка по фото', title: 'Примерить очки онлайн на своей фотографии', intro: 'Проверьте конкретную пару по своей фотографии и изображению товара, а при сомнениях сравните альтернативы рядом.', steps: [{ title: 'Загрузите фото лица', text: 'Используйте чёткое фронтальное фото при ровном освещении.' }, { title: 'Добавьте изображение очков', text: 'Подойдёт фото товара или скриншот магазина.' }, { title: 'Сравните при необходимости', text: 'Перейдите в Frame Compare, если одной примерки мало.' }], faq: [{ question: 'Можно примерить очки онлайн на фото?', answer: 'Да. Загрузите фото лица и изображение оправы, чтобы увидеть результат.' }, { question: 'Подойдёт скриншот из магазина?', answer: 'Да. Перед покупкой уточните точный размер и модель у продавца.' }, { question: 'Как сравнить несколько пар?', answer: 'Используйте Frame Compare для просмотра вариантов рядом.' }] },
    'ai-glasses-advisor': { metaTitle: 'ИИ-советник по очкам: оправы для вашего лица | VisuTry', metaDescription: 'Получите по фото практические рекомендации по оправам и проверьте короткий список виртуальной примеркой или сравнением.', eyebrow: 'Персональные рекомендации по очкам', title: 'ИИ-советник по очкам', intro: 'Используйте фото, чтобы сузить направления оправ, понять логику рекомендаций и затем проверить варианты визуально.', steps: [{ title: 'Поймите своё лицо', text: 'Используйте пропорции как практическую отправную точку.' }, { title: 'Получите рекомендации', text: 'Сузьте выбор до нескольких направлений оправ.' }, { title: 'Проверьте варианты', text: 'Используйте примерку и сравнение перед решением.' }], faq: [{ question: 'Что делает ИИ-советник по очкам?', answer: 'Он превращает видимые пропорции лица в практические рекомендации по формам и стилям.' }, { question: 'Это то же самое, что виртуальная примерка?', answer: 'Нет. Советник сужает выбор, а примерка показывает конкретную оправу на фото.' }, { question: 'Достаточно формы лица?', answer: 'Нет. Также важны ширина, высота линз, мост, рецепт и предпочтения.' }] },
    'what-glasses-suit-my-face': { metaTitle: 'Какие очки подходят моему лицу? Подбор по фото | VisuTry', metaDescription: 'Бесплатно определите форму лица, сузьте варианты оправ и подтвердите результат виртуальной примеркой или сравнением.', eyebrow: 'Подбор очков по фотографии', title: 'Какие очки подходят моему лицу?', intro: 'Используйте фото, чтобы оценить форму лица, составить короткий список оправ и затем проверить внешний вид на своём изображении.', steps: [{ title: 'Определите форму лица', text: 'Используйте бесплатный анализ в браузере без входа.' }, { title: 'Сузьте формы оправ', text: 'Сначала оставьте несколько силуэтов.' }, { title: 'Проверьте на фото', text: 'Оцените масштаб и стиль через примерку или сравнение.' }], faq: [{ question: 'Как понять, какие очки мне идут?', answer: 'Начните с формы лица, сузьте силуэты и проверьте ширину и стиль на своей фотографии.' }, { question: 'Нужно загружать фото?', answer: 'Фото помогает в анализе и примерке, но сначала можно прочитать рекомендации.' }, { question: 'Формы лица достаточно?', answer: 'Нет. Проверяйте ширину, мост, высоту линз, комфорт, рецепт и стиль.' }] },
    'virtual-glasses-try-on': { metaTitle: 'Виртуальная примерка очков по вашей фотографии | VisuTry', metaDescription: 'Примеряйте очки онлайн по своему фото и любому изображению товара, затем сравнивайте варианты перед покупкой.', eyebrow: 'Виртуальная примерка по вашему фото', title: 'Виртуальная примерка очков онлайн', intro: 'Посмотрите, как оправа выглядит на вашем лице до покупки. Загрузите фото и изображение очков и при необходимости сравните варианты.', steps: [{ title: 'Загрузите фото', text: 'Используйте фронтальное фото при ровном освещении.' }, { title: 'Добавьте изображение очков', text: 'Подойдёт фото товара или скриншот магазина.' }, { title: 'Оцените и решите', text: 'Проверьте результат и сравните альтернативы при необходимости.' }], faq: [{ question: 'Можно примерить очки онлайн на своём фото?', answer: 'Да. Загрузите фото и изображение товара, чтобы увидеть результат.' }, { question: 'Нужен каталог бренда?', answer: 'Нет. Можно использовать собственные изображения и скриншоты магазина.' }, { question: 'Как сравнить несколько пар?', answer: 'После примерки используйте Frame Compare, чтобы увидеть их рядом.' }] },
    'compare-glasses-frames': { metaTitle: 'Сравнить оправы рядом на своей фотографии | VisuTry', metaDescription: 'Сравнивайте до четырёх оправ с результатами ИИ-примерки рядом на своей фотографии.', eyebrow: 'Сравнение оправ рядом', title: 'Сравнить оправы на своей фотографии', intro: 'Если одной примерки мало, сравните несколько направлений оправ вместе и выберите вариант, который выглядит лучше.', steps: [{ title: 'Загрузите фото', text: 'Используйте чёткое фронтальное фото.' }, { title: 'Выберите до четырёх оправ', text: 'Берите достаточно разные пресеты.' }, { title: 'Смотрите рядом', text: 'Сравнивайте на одном экране, а не по памяти.' }], faq: [{ question: 'Как сравнить оправы онлайн?', answer: 'Загрузите фото, выберите до четырёх пресетов и создайте результаты рядом.' }, { question: 'Это лучше, чем примерять по одной?', answer: 'Прямое сравнение полезно для похожих вариантов; для конкретного товара достаточно одиночной примерки.' }, { question: 'Нужно сначала знать форму лица?', answer: 'Нет. Можно сравнивать сразу или сначала сузить выбор бесплатным детектором.' }] },
  },
  ar: {
    'what-is-my-face-shape': { metaTitle: 'ما شكل وجهي؟ اكتشاف مجاني من صورة | VisuTry', metaDescription: 'قدّر شكل وجهك مجاناً من صورة واحدة واستخدم النتيجة لاختيار النظارات وتجربتها.', eyebrow: 'فحص مجاني لشكل الوجه من صورة', title: 'ما شكل وجهي؟', intro: 'استخدم صورة واضحة لتقدير شكل وجهك وتحويل النتيجة مباشرة إلى إرشاد عملي لاختيار النظارات.', steps: [{ title: 'اختر صورة واحدة', text: 'استخدم صورة أمامية يظهر فيها الوجه كاملاً.' }, { title: 'اكتشف الشكل', text: 'يعمل الفحص المجاني داخل المتصفح.' }, { title: 'استخدم النتيجة', text: 'انتقل إلى النصائح أو التجربة أو المقارنة.' }], faq: [{ question: 'كيف أعرف شكل وجهي؟', answer: 'قارن عرض الجبهة وعظام الوجنتين والفك مع طول الوجه. يستطيع VisuTry تقدير الشكل من صورة واضحة.' }, { question: 'هل اكتشاف شكل الوجه مجاني؟', answer: 'نعم. الفحص الأساسي مجاني ويعمل داخل المتصفح.' }, { question: 'ماذا أفعل بعد معرفة شكل وجهي؟', answer: 'استخدم الشكل كمرشح أولي ثم تحقق من عرض الإطار وعمق العدسة والجسر والأسلوب بالتجربة أو المقارنة.' }] },
    'find-glasses-for-my-face': { metaTitle: 'ابحث عن نظارات تناسب وجهي من صورة | VisuTry', metaDescription: 'حلل ملامح وجهك وضيّق خيارات الإطارات ثم تحقق منها بالتجربة الافتراضية أو المقارنة جنباً إلى جنب.', eyebrow: 'اختيار أولي للإطارات من صورة', title: 'ابحث عن نظارات تناسب وجهي', intro: 'حوّل صورة واحدة إلى قائمة عملية: افهم نسب الوجه، قلّص اتجاهات الإطارات، ثم تحقق بصرياً من الخيارات النهائية.', steps: [{ title: 'افهم وجهك', text: 'ابدأ بكاشف شكل الوجه المجاني.' }, { title: 'ضيّق خيارات الإطارات', text: 'ركّز على عدد قليل من الأشكال والنسب.' }, { title: 'تحقق على صورتك', text: 'استخدم التجربة أو المقارنة جنباً إلى جنب.' }], faq: [{ question: 'كيف أجد نظارات تناسب وجهي؟', answer: 'ابدأ بنسب الوجه، ثم قلّص الأشكال والعروض، وبعدها أكد الاختيار بتجربة على صورتك.' }, { question: 'هل أختار حسب شكل الوجه فقط؟', answer: 'لا. عرض الإطار والجسر وعمق العدسة والوصفة والأسلوب مهمة أيضاً.' }, { question: 'هل يمكن استخدام صورة منتج خاصة بي؟', answer: 'نعم. يمكنك استخدام صورة منتج أو لقطة شاشة من متجر للتجربة الافتراضية.' }] },
    'try-glasses-on-photo': { metaTitle: 'جرّب النظارات على صورتك عبر الإنترنت | VisuTry', metaDescription: 'ارفع صورة وجه وصورة للنظارات، شاهد النتيجة ثم قارن عدة إطارات عند الحاجة.', eyebrow: 'معاينة افتراضية للنظارات من صورتك', title: 'جرّب النظارات على صورتك عبر الإنترنت', intro: 'اختبر إطاراً محدداً باستخدام صورتك وصورة المنتج، ثم قارن البدائل جنباً إلى جنب إذا احتجت مزيداً من الثقة.', steps: [{ title: 'ارفع صورة وجهك', text: 'استخدم صورة أمامية واضحة بإضاءة متساوية.' }, { title: 'أضف صورة النظارات', text: 'استخدم صورة منتج أو لقطة شاشة من متجر.' }, { title: 'قارن عند الحاجة', text: 'انتقل إلى Frame Compare إذا لم تكفِ معاينة واحدة.' }], faq: [{ question: 'هل يمكن تجربة النظارات على صورة عبر الإنترنت؟', answer: 'نعم. ارفع صورة وجه وصورة المنتج لرؤية المظهر.' }, { question: 'هل تعمل لقطة شاشة من متجر؟', answer: 'نعم. تأكد من المقاس والطراز الدقيقين لدى البائع قبل الشراء.' }, { question: 'كيف أقارن أكثر من زوج؟', answer: 'استخدم Frame Compare لمراجعة الخيارات جنباً إلى جنب.' }] },
    'ai-glasses-advisor': { metaTitle: 'مستشار نظارات بالذكاء الاصطناعي لوجهك | VisuTry', metaDescription: 'حوّل صورتك إلى إرشاد عملي للإطارات ثم تحقق من القائمة بالتجربة الافتراضية أو المقارنة.', eyebrow: 'إرشاد شخصي لاختيار النظارات', title: 'مستشار النظارات بالذكاء الاصطناعي', intro: 'استخدم صورتك لتضييق اتجاهات الإطارات المناسبة، وفهم سبب ملاءمتها، ثم تحقق منها بصرياً.', steps: [{ title: 'افهم وجهك', text: 'استخدم نسب الوجه كنقطة بداية عملية.' }, { title: 'احصل على إرشاد للإطارات', text: 'قلّص الاختيارات إلى اتجاهات قليلة.' }, { title: 'تحقق من القائمة', text: 'استخدم التجربة والمقارنة قبل القرار.' }], faq: [{ question: 'ماذا يفعل مستشار النظارات بالذكاء الاصطناعي؟', answer: 'يحوّل نسب الوجه الظاهرة إلى توصيات عملية للأشكال والأنماط.' }, { question: 'هل هو نفسه التجربة الافتراضية؟', answer: 'لا. المستشار يضيّق الاختيارات، والتجربة تعرض إطاراً محدداً على صورتك.' }, { question: 'هل يكفي شكل الوجه وحده؟', answer: 'لا. يجب أيضاً مراعاة العرض وعمق العدسة والجسر والوصفة والتفضيلات.' }] },
    'what-glasses-suit-my-face': { metaTitle: 'ما النظارات التي تناسب وجهي؟ اختر من صورة | VisuTry', metaDescription: 'اكتشف شكل وجهك مجاناً، قلّص خيارات الإطارات ثم أكد المظهر بالتجربة الافتراضية أو المقارنة.', eyebrow: 'نصيحة نظارات تبدأ من صورتك', title: 'ما النظارات التي تناسب وجهي؟', intro: 'استخدم صورة واحدة لتقدير شكل الوجه، وإنشاء قائمة قصيرة من الإطارات، ثم أكد المظهر على صورتك.', steps: [{ title: 'اكتشف شكل الوجه', text: 'استخدم الكاشف المجاني داخل المتصفح دون تسجيل دخول.' }, { title: 'قلّص أشكال الإطارات', text: 'ركّز أولاً على عدد قليل من الأشكال.' }, { title: 'تحقق على صورتك', text: 'افحص الحجم والأسلوب بالتجربة أو المقارنة.' }], faq: [{ question: 'كيف أعرف النظارات التي تناسبني؟', answer: 'ابدأ بشكل الوجه، قلّص الأشكال، ثم تحقق من العرض والأسلوب على صورتك.' }, { question: 'هل أحتاج إلى رفع صورة؟', answer: 'تساعد الصورة في الاكتشاف والتجربة، ويمكنك قراءة الإرشادات أولاً.' }, { question: 'هل شكل الوجه كافٍ؟', answer: 'لا. تحقق أيضاً من العرض والجسر والعمق والراحة والوصفة والأسلوب.' }] },
    'virtual-glasses-try-on': { metaTitle: 'تجربة نظارات افتراضية باستخدام صورتك | VisuTry', metaDescription: 'جرّب النظارات عبر الإنترنت باستخدام صورتك وأي صورة منتج، ثم قارن البدائل قبل الشراء.', eyebrow: 'تجربة افتراضية من صورتك', title: 'جرّب النظارات افتراضياً عبر الإنترنت', intro: 'شاهد كيف يبدو الإطار على وجهك قبل الشراء. ارفع صورتك وصورة النظارات وقارن البدائل عند الحاجة.', steps: [{ title: 'ارفع صورتك', text: 'استخدم صورة أمامية بإضاءة متساوية.' }, { title: 'أضف صورة النظارات', text: 'استخدم صورة منتج أو لقطة شاشة من متجر.' }, { title: 'عاين واتخذ القرار', text: 'تحقق من المظهر وقارن البدائل عند الحاجة.' }], faq: [{ question: 'هل يمكن تجربة النظارات على صورتي عبر الإنترنت؟', answer: 'نعم. ارفع صورتك وصورة المنتج لمعاينة المظهر.' }, { question: 'هل أحتاج إلى كتالوج العلامة؟', answer: 'لا. صور المنتجات الخاصة بك ولقطات المتاجر تعمل.' }, { question: 'كيف أقارن عدة أزواج؟', answer: 'بعد التجربة استخدم Frame Compare لرؤيتها جنباً إلى جنب.' }] },
    'compare-glasses-frames': { metaTitle: 'قارن إطارات النظارات جنباً إلى جنب على صورتك | VisuTry', metaDescription: 'قارن حتى أربعة إطارات بنتائج تجربة ذكاء اصطناعي جنباً إلى جنب على صورتك.', eyebrow: 'قرار الإطار بالمقارنة المباشرة', title: 'قارن إطارات النظارات على صورتك', intro: 'عندما لا تكفي تجربة واحدة، قارن عدة اتجاهات للإطارات معاً واختر ما يناسبك أكثر.', steps: [{ title: 'ارفع صورة واحدة', text: 'استخدم صورة وجه واضحة من الأمام.' }, { title: 'اختر حتى أربعة إطارات', text: 'اختر نماذج مختلفة بما يكفي للمقارنة.' }, { title: 'راجع جنباً إلى جنب', text: 'اتخذ القرار في شاشة واحدة بدلاً من الاعتماد على الذاكرة.' }], faq: [{ question: 'كيف أقارن إطارات النظارات عبر الإنترنت؟', answer: 'ارفع صورة، اختر حتى أربعة نماذج، ثم أنشئ نتائج التجربة جنباً إلى جنب.' }, { question: 'هل هذا أفضل من تجربة إطار واحد كل مرة؟', answer: 'المقارنة المباشرة مفيدة للخيارات المتقاربة؛ أما المنتج المحدد فتكفيه التجربة الفردية غالباً.' }, { question: 'هل يجب أن أعرف شكل وجهي أولاً؟', answer: 'لا. يمكنك المقارنة مباشرة أو استخدام الكاشف المجاني أولاً.' }] },
  },
}

const hub: Record<Locale, GlassesGuideHubCopy> = {
  en: { metaTitle: 'Glasses Guides by Face Shape, Frame Style & Fit Question | VisuTry', metaDescription: 'Explore focused glasses decision guides by face shape, frame style, and fit question, then validate the shortlist with VisuTry tools.', eyebrow: 'Focused eyewear decisions', title: 'Glasses Guides by Face Shape, Frame Style & Fit Question', intro: 'These pages are built around one decision at a time. Read the short answer, then move directly into face-shape detection, personalized advice, virtual try-on, or frame compare.', groups: [{ type: 'face-frame', eyebrow: 'Face × frame', title: 'Frame styles for specific face shapes', description: 'Use these pages when you already have a frame direction in mind and want to test whether it makes sense for your face shape.' }, { type: 'gender-style', eyebrow: 'Styling intent', title: 'Styling guides by face shape', description: 'Use these pages as style-oriented shortlists, not rigid gender rules. Proportion and fit still lead the decision.' }, { type: 'decision-question', eyebrow: 'Decision questions', title: 'Direct answers to common glasses fit questions', description: 'Start with the question, get the short answer, then validate the choice with a photo or side-by-side comparison.' }], openGuide: 'Open guide', homeBreadcrumb: 'Home', guidesBreadcrumb: 'Glasses Guides', phaseBNote: '' },
  ja: { metaTitle: '顔型・フレーム・フィット別メガネガイド | VisuTry', metaDescription: '顔型、フレーム形状、フィットの疑問ごとにメガネ選びを整理し、VisuTryのツールで候補を確認できます。', eyebrow: 'メガネ選びを1つずつ解決', title: '顔型・フレーム・フィット別メガネガイド', intro: '一度に1つの判断に集中するガイドです。答えを確認したら、顔型判定、提案、バーチャル試着、比較へ進めます。', groups: [{ type: 'face-frame', eyebrow: '顔型 × フレーム', title: '顔型ごとのフレームスタイル', description: '試したいフレーム方向があるとき、顔のバランスに合うかを確認します。' }, { type: 'gender-style', eyebrow: 'スタイリング', title: '顔型別スタイリングガイド', description: '性別の固定ルールではなく、比率とフィットを優先した候補として使います。' }, { type: 'decision-question', eyebrow: '選び方の疑問', title: 'メガネのフィットに関するよくある疑問', description: '短い答えを確認し、自分の写真や横並び比較で判断します。' }], openGuide: 'ガイドを開く', homeBreadcrumb: 'ホーム', guidesBreadcrumb: 'メガネガイド', phaseBNote: '詳細な組み合わせガイドの多言語版は次のフェーズで公開します。現在は下のツールから直接試せます。' },
  de: { metaTitle: 'Brillenratgeber nach Gesichtsform, Fassung und Passform | VisuTry', metaDescription: 'Gezielte Brillenratgeber zu Gesichtsform, Fassungsstil und Passform mit direkter Validierung über VisuTry.', eyebrow: 'Gezielte Brillenentscheidungen', title: 'Brillenratgeber nach Gesichtsform, Fassungsstil und Passform', intro: 'Jede Seite beantwortet eine konkrete Frage. Danach kannst du direkt zur Gesichtsform-Erkennung, Beratung, Anprobe oder zum Vergleich wechseln.', groups: [{ type: 'face-frame', eyebrow: 'Gesicht × Fassung', title: 'Fassungsstile für bestimmte Gesichtsformen', description: 'Prüfe, ob eine bereits interessante Fassungsrichtung zu deinen Proportionen passt.' }, { type: 'gender-style', eyebrow: 'Styling', title: 'Styling-Ratgeber nach Gesichtsform', description: 'Nutze sie als Stil-Shortlist, nicht als starre Geschlechterregel. Proportion und Passform bleiben entscheidend.' }, { type: 'decision-question', eyebrow: 'Entscheidungsfragen', title: 'Direkte Antworten zu Brillenpassform', description: 'Starte mit der Frage, lies die kurze Antwort und bestätige die Wahl anschließend visuell.' }], openGuide: 'Ratgeber öffnen', homeBreadcrumb: 'Startseite', guidesBreadcrumb: 'Brillenratgeber', phaseBNote: 'Die mehrsprachigen Detailratgeber folgen in Phase B. Bis dahin kannst du direkt mit den VisuTry-Werkzeugen weiterarbeiten.' },
  fr: { metaTitle: 'Guides lunettes par forme de visage, monture et ajustement | VisuTry', metaDescription: 'Explorez des guides ciblés par forme de visage, style de monture et question d’ajustement, puis validez avec VisuTry.', eyebrow: 'Décisions lunettes ciblées', title: 'Guides lunettes par forme de visage, monture et ajustement', intro: 'Chaque guide traite une décision à la fois. Après la réponse courte, passez directement à la détection, au conseil, à l’essayage ou à la comparaison.', groups: [{ type: 'face-frame', eyebrow: 'Visage × monture', title: 'Styles de montures selon la forme du visage', description: 'À utiliser quand vous avez déjà une direction de monture et souhaitez vérifier sa cohérence avec vos proportions.' }, { type: 'gender-style', eyebrow: 'Intention de style', title: 'Guides de style par forme de visage', description: 'Utilisez-les comme présélection de style, pas comme règle de genre stricte. Proportion et ajustement restent prioritaires.' }, { type: 'decision-question', eyebrow: 'Questions de décision', title: 'Réponses directes aux questions d’ajustement', description: 'Commencez par la question, lisez la réponse courte puis validez avec une photo ou une comparaison.' }], openGuide: 'Ouvrir le guide', homeBreadcrumb: 'Accueil', guidesBreadcrumb: 'Guides lunettes', phaseBNote: 'Les guides détaillés multilingues arriveront en phase B. En attendant, utilisez directement les outils VisuTry.' },
  es: { metaTitle: 'Guías de gafas por forma de cara, montura y ajuste | VisuTry', metaDescription: 'Explora guías específicas por forma facial, estilo de montura y preguntas de ajuste y valida con las herramientas de VisuTry.', eyebrow: 'Decisiones de gafas concretas', title: 'Guías de gafas por forma de cara, montura y ajuste', intro: 'Cada guía resuelve una decisión. Lee la respuesta corta y pasa directamente a detección, asesor, prueba virtual o comparación.', groups: [{ type: 'face-frame', eyebrow: 'Cara × montura', title: 'Estilos de montura para formas faciales', description: 'Úsalas cuando ya tengas una dirección de montura y quieras comprobar si encaja con tus proporciones.' }, { type: 'gender-style', eyebrow: 'Estilo', title: 'Guías de estilo por forma facial', description: 'Úsalas como shortlist de estilo, no como reglas rígidas de género. Proporción y ajuste siguen primero.' }, { type: 'decision-question', eyebrow: 'Preguntas de decisión', title: 'Respuestas directas sobre ajuste de gafas', description: 'Empieza por la pregunta, obtén una respuesta corta y valida con foto o comparación.' }], openGuide: 'Abrir guía', homeBreadcrumb: 'Inicio', guidesBreadcrumb: 'Guías de gafas', phaseBNote: 'Las guías detalladas multilingües llegarán en la fase B. Mientras tanto, usa directamente las herramientas de VisuTry.' },
  pt: { metaTitle: 'Guias de óculos por formato do rosto, armação e ajuste | VisuTry', metaDescription: 'Explore guias focados em formato facial, estilo de armação e ajuste e valide com as ferramentas do VisuTry.', eyebrow: 'Decisões de óculos objetivas', title: 'Guias de óculos por formato do rosto, armação e ajuste', intro: 'Cada guia resolve uma decisão por vez. Leia a resposta curta e siga para detecção, consultor, prova virtual ou comparação.', groups: [{ type: 'face-frame', eyebrow: 'Rosto × armação', title: 'Estilos de armação para formatos faciais', description: 'Use quando já tiver uma direção de armação e quiser conferir se ela faz sentido para suas proporções.' }, { type: 'gender-style', eyebrow: 'Estilo', title: 'Guias de estilo por formato facial', description: 'Use como shortlist de estilo, não como regra rígida de gênero. Proporção e ajuste continuam primeiro.' }, { type: 'decision-question', eyebrow: 'Perguntas de decisão', title: 'Respostas diretas sobre ajuste de óculos', description: 'Comece pela pergunta, veja a resposta curta e valide com foto ou comparação.' }], openGuide: 'Abrir guia', homeBreadcrumb: 'Início', guidesBreadcrumb: 'Guias de óculos', phaseBNote: 'Os guias detalhados multilíngues chegam na fase B. Até lá, use diretamente as ferramentas do VisuTry.' },
  id: { metaTitle: 'Panduan kacamata menurut bentuk wajah, frame, dan fit | VisuTry', metaDescription: 'Jelajahi panduan keputusan kacamata menurut bentuk wajah, gaya frame, dan pertanyaan fit lalu validasi dengan VisuTry.', eyebrow: 'Keputusan kacamata yang fokus', title: 'Panduan Kacamata menurut Bentuk Wajah, Frame, dan Fit', intro: 'Setiap panduan fokus pada satu keputusan. Baca jawaban singkat lalu lanjut ke deteksi, advisor, virtual try-on, atau compare.', groups: [{ type: 'face-frame', eyebrow: 'Wajah × frame', title: 'Gaya frame untuk bentuk wajah tertentu', description: 'Gunakan saat Anda sudah punya arah frame dan ingin mengecek kecocokannya dengan proporsi wajah.' }, { type: 'gender-style', eyebrow: 'Gaya', title: 'Panduan gaya menurut bentuk wajah', description: 'Gunakan sebagai shortlist gaya, bukan aturan gender yang kaku. Proporsi dan fit tetap utama.' }, { type: 'decision-question', eyebrow: 'Pertanyaan keputusan', title: 'Jawaban langsung tentang fit kacamata', description: 'Mulai dari pertanyaan, baca jawaban singkat, lalu validasi dengan foto atau perbandingan.' }], openGuide: 'Buka panduan', homeBreadcrumb: 'Beranda', guidesBreadcrumb: 'Panduan kacamata', phaseBNote: 'Panduan kombinasi multibahasa akan hadir di Fase B. Untuk sekarang, lanjutkan langsung dengan alat VisuTry.' },
  ru: { metaTitle: 'Гайды по очкам: форма лица, оправа и посадка | VisuTry', metaDescription: 'Изучайте точечные гайды по форме лица, стилю оправы и посадке и проверяйте выбор инструментами VisuTry.', eyebrow: 'Точные решения при выборе очков', title: 'Гайды по очкам: форма лица, оправа и посадка', intro: 'Каждый гайд отвечает на один вопрос. После короткого ответа переходите к определению формы, советнику, примерке или сравнению.', groups: [{ type: 'face-frame', eyebrow: 'Лицо × оправа', title: 'Стили оправ для разных форм лица', description: 'Используйте, когда уже есть интересующее направление оправы и нужно проверить его по пропорциям.' }, { type: 'gender-style', eyebrow: 'Стиль', title: 'Стилевые гайды по форме лица', description: 'Используйте как короткий список стилей, а не как жёсткое гендерное правило. Пропорции и посадка важнее.' }, { type: 'decision-question', eyebrow: 'Вопросы выбора', title: 'Прямые ответы о посадке очков', description: 'Начните с вопроса, получите короткий ответ и подтвердите выбор на фото или сравнением.' }], openGuide: 'Открыть гайд', homeBreadcrumb: 'Главная', guidesBreadcrumb: 'Гайды по очкам', phaseBNote: 'Подробные многоязычные гайды появятся в Phase B. Пока используйте инструменты VisuTry напрямую.' },
  ar: { metaTitle: 'أدلة النظارات حسب شكل الوجه والإطار والملاءمة | VisuTry', metaDescription: 'استكشف أدلة مركزة حسب شكل الوجه ونمط الإطار وأسئلة الملاءمة ثم تحقق من الاختيار بأدوات VisuTry.', eyebrow: 'قرارات نظارات مركزة', title: 'أدلة النظارات حسب شكل الوجه والإطار والملاءمة', intro: 'يعالج كل دليل قراراً واحداً. اقرأ الإجابة المختصرة ثم انتقل مباشرة إلى اكتشاف الشكل أو المستشار أو التجربة أو المقارنة.', groups: [{ type: 'face-frame', eyebrow: 'الوجه × الإطار', title: 'أنماط إطارات لأشكال وجه محددة', description: 'استخدمها عندما يكون لديك اتجاه إطار وتريد معرفة مدى ملاءمته لنسب وجهك.' }, { type: 'gender-style', eyebrow: 'الأسلوب', title: 'أدلة أسلوب حسب شكل الوجه', description: 'استخدمها كقائمة أسلوب مختصرة لا كقواعد جنس صارمة. النسب والملاءمة أولاً.' }, { type: 'decision-question', eyebrow: 'أسئلة القرار', title: 'إجابات مباشرة عن ملاءمة النظارات', description: 'ابدأ بالسؤال، اقرأ الإجابة المختصرة ثم تحقق منها بصورة أو مقارنة.' }], openGuide: 'افتح الدليل', homeBreadcrumb: 'الرئيسية', guidesBreadcrumb: 'أدلة النظارات', phaseBNote: 'ستتوفر الأدلة التفصيلية متعددة اللغات في المرحلة B. حالياً يمكنك استخدام أدوات VisuTry مباشرة.' },
}

export function getSearchToToolSharedCopy(locale: string): SharedCopy {
  return shared[getValidLocale(locale)]
}

export function getSearchToToolLandingCopy(locale: string, routeId: SearchToToolRouteId): SearchToToolLandingCopy {
  const resolved = getValidLocale(locale)
  const base = resolved === 'en' ? en[routeId] : localized[resolved][routeId]
  const common = shared[resolved]
  return {
    ...base,
    principles: common.principles,
    ctaLabels: common.ctaLabels,
    faqEyebrow: common.nextStep,
    faqTitle: common.commonQuestions,
  }
}

export function getGlassesGuideHubCopy(locale: string): GlassesGuideHubCopy {
  return hub[getValidLocale(locale)]
}
