import { defaultLocale, isValidLocale, type Locale } from '@/i18n'

export type SearchToToolPhaseARouteId =
  | 'find-glasses-for-my-face'
  | 'try-glasses-on-photo'
  | 'ai-glasses-advisor'
  | 'what-glasses-suit-my-face'
  | 'virtual-glasses-try-on'
  | 'compare-glasses-frames'

type StepItem = { title: string; text: string }
type FaqItem = { question: string; answer: string }
type SchemaStep = { name: string; text: string }

type PageKind = 'selection' | 'tryOn' | 'advisor' | 'compare'

type RouteSeed = {
  kind: PageKind
  metaTitle: string
  metaDescription: string
  eyebrow: string
  title: string
  intro: string
  faqTitle: string
}

type KindCopy = {
  steps: readonly [StepItem, StepItem, StepItem]
  principles: readonly [string, string, string]
  faq: readonly [FaqItem, FaqItem, FaqItem]
  faqEyebrow: string
  ctaLabels: { detector: string; advisor: string; tryOn: string; compare: string }
  howTo?: { name: string; description: string; steps: readonly [SchemaStep, SchemaStep, SchemaStep] }
  software?: { description: string; featureList: readonly [string, string, string, string] }
}

export type SearchToToolPhaseACopy = Omit<RouteSeed, 'kind'> & KindCopy & { kind: PageKind }

const kindCopies: Record<Locale, Record<PageKind, KindCopy>> = {
  en: {
    selection: {
      steps: [{ title: 'Understand your face', text: 'Start with face proportions and a free face-shape estimate.' }, { title: 'Shortlist frames', text: 'Narrow the shapes and proportions worth testing.' }, { title: 'Validate visually', text: 'Use try-on or side-by-side compare before deciding.' }],
      principles: ['Use face shape as a first filter, not a rigid rule.', 'Frame width and scale matter as much as silhouette.', 'Compare a small shortlist instead of browsing endlessly.'],
      faq: [{ question: 'How do I find glasses that suit my face?', answer: 'Start with face proportions, narrow a few frame directions, then validate width, scale, and style on your own photo.' }, { question: 'Should I choose glasses only by face shape?', answer: 'No. Frame width, bridge fit, lens depth, prescription needs, comfort, and personal style also matter.' }, { question: 'Can I validate a specific pair?', answer: 'Yes. Use a glasses product image or retailer screenshot in virtual try-on, or compare several candidates side by side.' }],
      faqEyebrow: 'Ready to narrow the options',
      ctaLabels: { detector: 'Detect my face shape free', advisor: 'Get glasses advice', tryOn: 'Try glasses on my photo', compare: 'Compare frames' },
      howTo: { name: 'How to find glasses for your face', description: 'Use face guidance, shortlist frame directions, and validate them on your own photo.', steps: [{ name: 'Detect', text: 'Estimate your likely face shape from one clear photo.' }, { name: 'Shortlist', text: 'Choose a few frame shapes and proportions worth testing.' }, { name: 'Validate', text: 'Try one exact frame or compare several candidates side by side.' }] },
    },
    tryOn: {
      steps: [{ title: 'Upload your photo', text: 'Use a clear, straight-on face photo with even light.' }, { title: 'Add a glasses image', text: 'Use a product photo or retailer screenshot.' }, { title: 'Preview and compare', text: 'Check the look, then compare alternatives if needed.' }],
      principles: ['Use a front-facing photo for the cleanest visual check.', 'Try-on helps with appearance; confirm physical fit and size separately.', 'Compare a shortlist when two or more frames remain close.'],
      faq: [{ question: 'Can I try glasses on a photo online?', answer: 'Yes. Upload a clear face photo and a glasses product image or screenshot to preview the frame on your photo.' }, { question: 'Can I use a retailer screenshot?', answer: 'Yes. A clean product image or retailer screenshot can be used. Confirm exact size and model details with the seller.' }, { question: 'What if I want to compare more than one pair?', answer: 'Use Frame Compare to review several candidates side by side instead of relying on memory.' }],
      faqEyebrow: 'Ready to preview',
      ctaLabels: { detector: 'Check my face shape first', advisor: 'Get glasses advice', tryOn: 'Try glasses on my photo', compare: 'Compare frames side by side' },
      software: { description: 'Browser-based virtual glasses try-on from a face photo and a glasses product image.', featureList: ['Upload your own face photo', 'Use a glasses product image or screenshot', 'Preview a specific frame', 'Continue into side-by-side comparison'] },
    },
    advisor: {
      steps: [{ title: 'Understand your face', text: 'Use visible face proportions as a practical starting point.' }, { title: 'Get frame guidance', text: 'Turn the analysis into a smaller set of frame directions worth testing.' }, { title: 'Validate the shortlist', text: 'Use virtual try-on and compare before deciding.' }],
      principles: ['Use recommendations to narrow choices, not impose one answer.', 'Connect guidance to visual proof with try-on.', 'Keep fit, prescription, and comfort checks separate from appearance.'],
      faq: [{ question: 'What does an AI glasses advisor do?', answer: 'It turns visible face proportions and your photo into practical frame guidance before you try specific glasses.' }, { question: 'Is the advisor the same as virtual try-on?', answer: 'No. The advisor narrows directions; virtual try-on shows how a specific frame looks on your photo.' }, { question: 'Should I use face shape alone?', answer: 'No. Frame width, lens depth, bridge fit, prescription needs, and personal style also matter.' }],
      faqEyebrow: 'Personalized next step',
      ctaLabels: { detector: 'Detect my face shape free', advisor: 'Open AI glasses advisor', tryOn: 'Try glasses on my photo', compare: 'Compare frames' },
      software: { description: 'AI-assisted eyewear guidance from a face photo, connected to virtual try-on and frame comparison.', featureList: ['Photo-based face analysis', 'Personalized frame guidance', 'Continuation into virtual try-on', 'Continuation into frame comparison'] },
    },
    compare: {
      steps: [{ title: 'Upload one photo', text: 'Use a clear, straight-on face photo.' }, { title: 'Choose up to four frames', text: 'Select built-in presets that are useful to compare.' }, { title: 'Review side by side', text: 'Decide with a comparison board instead of memory alone.' }],
      principles: ['Compare clearly different silhouettes first.', 'Each generated frame result uses credits.', 'Confirm exact size and model with the seller before buying.'],
      faq: [{ question: 'How do I compare glasses frames online?', answer: 'Upload one face photo, choose up to four built-in presets, and generate side-by-side try-on results.' }, { question: 'Is this better than trying one pair at a time?', answer: 'Side-by-side comparison helps when several silhouettes look close; single try-on is useful for one exact product image.' }, { question: 'Do I need to know my face shape first?', answer: 'No. It is optional, but the free detector can help narrow the shortlist first.' }],
      faqEyebrow: 'Next step',
      ctaLabels: { detector: 'Detect my face shape', advisor: 'Get glasses advice', tryOn: 'Try one pair first', compare: 'Open frame compare' },
      software: { description: 'Compare glasses frames side by side with AI try-on results on your photo.', featureList: ['Compare up to four frame presets', 'Side-by-side AI try-on results', 'Built for purchase decisions', 'Works in the browser'] },
    },
  },
  id: {
    selection: { steps: [{ title: 'Pahami wajah Anda', text: 'Mulai dari proporsi wajah dan estimasi bentuk wajah gratis.' }, { title: 'Pilih beberapa frame', text: 'Persempit bentuk dan proporsi yang layak dicoba.' }, { title: 'Validasi secara visual', text: 'Gunakan coba virtual atau perbandingan sebelum memutuskan.' }], principles: ['Gunakan bentuk wajah sebagai filter awal, bukan aturan mutlak.', 'Lebar dan skala frame sama pentingnya dengan bentuk.', 'Bandingkan beberapa kandidat terbaik saja.'], faq: [{ question: 'Bagaimana menemukan kacamata yang cocok?', answer: 'Mulai dari proporsi wajah, pilih beberapa arah frame, lalu cek skala dan gaya pada foto Anda.' }, { question: 'Apakah cukup memilih berdasarkan bentuk wajah?', answer: 'Tidak. Lebar frame, bridge, kedalaman lensa, kebutuhan resep, kenyamanan, dan gaya juga penting.' }, { question: 'Bisakah saya memeriksa satu frame tertentu?', answer: 'Ya. Gunakan gambar produk atau tangkapan layar toko di coba virtual, atau bandingkan beberapa frame.' }], faqEyebrow: 'Siap mempersempit pilihan', ctaLabels: { detector: 'Deteksi bentuk wajah gratis', advisor: 'Dapatkan saran kacamata', tryOn: 'Coba kacamata di foto saya', compare: 'Bandingkan frame' }, howTo: { name: 'Cara menemukan kacamata untuk wajah Anda', description: 'Gunakan panduan wajah, pilih beberapa frame, lalu validasi di foto Anda.', steps: [{ name: 'Deteksi', text: 'Perkirakan bentuk wajah dari satu foto.' }, { name: 'Pilih', text: 'Pilih beberapa bentuk dan proporsi frame.' }, { name: 'Validasi', text: 'Coba satu frame atau bandingkan beberapa kandidat.' }] } },
    tryOn: { steps: [{ title: 'Unggah foto Anda', text: 'Gunakan foto wajah yang jelas dan menghadap depan.' }, { title: 'Tambahkan gambar kacamata', text: 'Gunakan foto produk atau tangkapan layar toko.' }, { title: 'Lihat dan bandingkan', text: 'Periksa tampilannya lalu bandingkan alternatif bila perlu.' }], principles: ['Gunakan foto menghadap depan.', 'Coba virtual membantu tampilan; cek ukuran fisik secara terpisah.', 'Bandingkan kandidat jika pilihannya masih dekat.'], faq: [{ question: 'Bisakah mencoba kacamata pada foto?', answer: 'Ya. Unggah foto wajah dan gambar kacamata untuk melihat pratinjau pada foto Anda.' }, { question: 'Bisakah memakai screenshot toko?', answer: 'Ya. Gunakan gambar yang bersih dan konfirmasikan ukuran serta model dengan penjual.' }, { question: 'Bagaimana membandingkan beberapa pasang?', answer: 'Gunakan Frame Compare untuk melihat kandidat berdampingan.' }], faqEyebrow: 'Siap mencoba', ctaLabels: { detector: 'Periksa bentuk wajah dulu', advisor: 'Dapatkan saran kacamata', tryOn: 'Coba kacamata di foto saya', compare: 'Bandingkan frame berdampingan' }, software: { description: 'Coba kacamata virtual di browser dari foto wajah dan gambar produk kacamata.', featureList: ['Unggah foto wajah sendiri', 'Gunakan gambar produk atau screenshot', 'Lihat satu frame tertentu', 'Lanjutkan ke perbandingan berdampingan'] } },
    advisor: { steps: [{ title: 'Pahami wajah Anda', text: 'Gunakan proporsi wajah sebagai titik awal.' }, { title: 'Dapatkan arahan frame', text: 'Ubah analisis menjadi beberapa arah frame yang layak dicoba.' }, { title: 'Validasi pilihan', text: 'Gunakan coba virtual dan perbandingan sebelum memilih.' }], principles: ['Gunakan rekomendasi untuk mempersempit pilihan.', 'Hubungkan saran dengan bukti visual.', 'Pisahkan penilaian tampilan dari fit dan resep.'], faq: [{ question: 'Apa fungsi AI glasses advisor?', answer: 'Ia mengubah proporsi wajah dan foto menjadi panduan frame praktis.' }, { question: 'Apakah sama dengan coba virtual?', answer: 'Tidak. Advisor membantu memilih arah; coba virtual menunjukkan satu frame di foto Anda.' }, { question: 'Apakah bentuk wajah saja cukup?', answer: 'Tidak. Lebar, bridge, kedalaman lensa, resep, dan gaya juga penting.' }], faqEyebrow: 'Langkah personal berikutnya', ctaLabels: { detector: 'Deteksi bentuk wajah gratis', advisor: 'Buka AI glasses advisor', tryOn: 'Coba kacamata di foto saya', compare: 'Bandingkan frame' }, software: { description: 'Panduan kacamata berbantuan AI dari foto wajah, terhubung ke coba virtual dan perbandingan.', featureList: ['Analisis wajah dari foto', 'Panduan frame personal', 'Lanjut ke coba virtual', 'Lanjut ke perbandingan frame'] } },
    compare: { steps: [{ title: 'Unggah satu foto', text: 'Gunakan foto wajah yang jelas.' }, { title: 'Pilih hingga empat frame', text: 'Pilih preset yang berguna untuk dibandingkan.' }, { title: 'Lihat berdampingan', text: 'Bandingkan hasil dalam satu tampilan.' }], principles: ['Bandingkan siluet yang berbeda terlebih dahulu.', 'Setiap hasil frame menggunakan kredit.', 'Konfirmasi ukuran dan model dengan penjual.'], faq: [{ question: 'Bagaimana membandingkan frame online?', answer: 'Unggah satu foto, pilih hingga empat preset, lalu buat hasil coba berdampingan.' }, { question: 'Apakah lebih baik daripada mencoba satu per satu?', answer: 'Perbandingan berdampingan membantu saat beberapa pilihan terlihat mirip.' }, { question: 'Haruskah tahu bentuk wajah dulu?', answer: 'Tidak wajib, tetapi detektor gratis dapat membantu mempersempit pilihan.' }], faqEyebrow: 'Langkah berikutnya', ctaLabels: { detector: 'Deteksi bentuk wajah', advisor: 'Dapatkan saran', tryOn: 'Coba satu frame dulu', compare: 'Buka perbandingan frame' }, software: { description: 'Bandingkan frame kacamata berdampingan dengan hasil coba AI pada foto Anda.', featureList: ['Bandingkan hingga empat preset', 'Hasil berdampingan', 'Untuk membantu keputusan beli', 'Berjalan di browser'] } },
  },
  ar: {
    selection: { steps: [{ title: 'افهم وجهك', text: 'ابدأ بنسب الوجه وتقدير مجاني لشكل الوجه.' }, { title: 'اختصر الخيارات', text: 'اختر بعض أشكال وأحجام الإطارات المناسبة للتجربة.' }, { title: 'تحقق بصريًا', text: 'استخدم التجربة أو المقارنة قبل القرار.' }], principles: ['استخدم شكل الوجه كمرشح أولي لا كقاعدة صارمة.', 'عرض الإطار وحجمه مهمان بقدر شكله.', 'قارن قائمة قصيرة بدل تصفح خيارات لا تنتهي.'], faq: [{ question: 'كيف أجد نظارات تناسب وجهي؟', answer: 'ابدأ بنسب الوجه، ثم اختر بعض اتجاهات الإطارات وتحقق من الحجم والأسلوب على صورتك.' }, { question: 'هل أختار حسب شكل الوجه فقط؟', answer: 'لا. العرض والجسر وعمق العدسة والوصفة والراحة والأسلوب مهمة أيضًا.' }, { question: 'هل يمكنني اختبار إطار محدد؟', answer: 'نعم. استخدم صورة منتج أو لقطة شاشة في التجربة الافتراضية أو قارن عدة خيارات.' }], faqEyebrow: 'جاهز لتقليل الخيارات', ctaLabels: { detector: 'اكتشف شكل وجهي مجانًا', advisor: 'احصل على نصيحة', tryOn: 'جرّب النظارات على صورتي', compare: 'قارن الإطارات' }, howTo: { name: 'كيفية إيجاد نظارات لوجهك', description: 'استخدم إرشاد الوجه ثم اختصر الإطارات وتحقق منها على صورتك.', steps: [{ name: 'اكتشف', text: 'قدّر شكل وجهك من صورة واضحة.' }, { name: 'اختصر', text: 'اختر بعض الأشكال والأحجام.' }, { name: 'تحقق', text: 'جرّب إطارًا أو قارن عدة خيارات.' }] } },
    tryOn: { steps: [{ title: 'ارفع صورتك', text: 'استخدم صورة أمامية واضحة.' }, { title: 'أضف صورة النظارات', text: 'استخدم صورة منتج أو لقطة شاشة من المتجر.' }, { title: 'عاين وقارن', text: 'تحقق من المظهر ثم قارن البدائل عند الحاجة.' }], principles: ['استخدم صورة أمامية واضحة.', 'التجربة تساعد في المظهر؛ تحقق من المقاس الفعلي منفصلًا.', 'قارن قائمة قصيرة عندما تتقارب الخيارات.'], faq: [{ question: 'هل يمكن تجربة النظارات على صورة؟', answer: 'نعم. ارفع صورة وجه وصورة للنظارات لمعاينة الإطار.' }, { question: 'هل يمكن استخدام لقطة شاشة من متجر؟', answer: 'نعم، واستخدم صورة نظيفة وتحقق من المقاس والطراز لدى البائع.' }, { question: 'كيف أقارن أكثر من إطار؟', answer: 'استخدم Frame Compare لرؤية عدة خيارات جنبًا إلى جنب.' }], faqEyebrow: 'جاهز للمعاينة', ctaLabels: { detector: 'تحقق من شكل وجهي أولًا', advisor: 'احصل على نصيحة', tryOn: 'جرّب النظارات على صورتي', compare: 'قارن الإطارات جنبًا إلى جنب' }, software: { description: 'تجربة نظارات افتراضية في المتصفح من صورة وجه وصورة منتج.', featureList: ['ارفع صورة وجهك', 'استخدم صورة منتج أو لقطة شاشة', 'عاين إطارًا محددًا', 'انتقل إلى المقارنة'] } },
    advisor: { steps: [{ title: 'افهم وجهك', text: 'استخدم نسب الوجه كنقطة بداية عملية.' }, { title: 'احصل على إرشاد للإطارات', text: 'حوّل التحليل إلى مجموعة أصغر تستحق التجربة.' }, { title: 'تحقق من القائمة', text: 'استخدم التجربة والمقارنة قبل القرار.' }], principles: ['استخدم التوصيات لتقليل الخيارات.', 'اربط الإرشاد بمعاينة بصرية.', 'افصل بين المظهر والمقاس والوصفة والراحة.'], faq: [{ question: 'ماذا يفعل مستشار النظارات بالذكاء الاصطناعي؟', answer: 'يحوّل نسب الوجه والصورة إلى إرشاد عملي للإطارات.' }, { question: 'هل هو نفس التجربة الافتراضية؟', answer: 'لا. المستشار يحدد الاتجاهات، والتجربة تعرض إطارًا محددًا على صورتك.' }, { question: 'هل يكفي شكل الوجه وحده؟', answer: 'لا. العرض وعمق العدسة والجسر والوصفة والأسلوب مهمة أيضًا.' }], faqEyebrow: 'الخطوة الشخصية التالية', ctaLabels: { detector: 'اكتشف شكل وجهي مجانًا', advisor: 'افتح مستشار النظارات', tryOn: 'جرّب النظارات على صورتي', compare: 'قارن الإطارات' }, software: { description: 'إرشاد نظارات بمساعدة الذكاء الاصطناعي من صورة وجه مع التجربة والمقارنة.', featureList: ['تحليل الوجه من الصورة', 'إرشاد شخصي للإطارات', 'الانتقال للتجربة', 'الانتقال للمقارنة'] } },
    compare: { steps: [{ title: 'ارفع صورة واحدة', text: 'استخدم صورة وجه واضحة.' }, { title: 'اختر حتى أربعة إطارات', text: 'اختر نماذج مفيدة للمقارنة.' }, { title: 'راجع جنبًا إلى جنب', text: 'اتخذ القرار من لوحة مقارنة واحدة.' }], principles: ['ابدأ بأشكال مختلفة بوضوح.', 'كل نتيجة إطار تستخدم رصيدًا.', 'تحقق من المقاس والطراز لدى البائع.'], faq: [{ question: 'كيف أقارن إطارات النظارات أونلاين؟', answer: 'ارفع صورة واختر حتى أربعة نماذج ثم أنشئ نتائج جنبًا إلى جنب.' }, { question: 'هل هذا أفضل من تجربة إطار واحد؟', answer: 'المقارنة مفيدة عندما تكون عدة أشكال متقاربة.' }, { question: 'هل يجب أن أعرف شكل وجهي أولًا؟', answer: 'لا، لكنه يمكن أن يساعد في تقليل القائمة.' }], faqEyebrow: 'الخطوة التالية', ctaLabels: { detector: 'اكتشف شكل وجهي', advisor: 'احصل على نصيحة', tryOn: 'جرّب إطارًا واحدًا', compare: 'افتح مقارنة الإطارات' }, software: { description: 'قارن إطارات النظارات جنبًا إلى جنب بنتائج تجربة AI على صورتك.', featureList: ['قارن حتى أربعة نماذج', 'نتائج جنبًا إلى جنب', 'مصمم لقرار الشراء', 'يعمل في المتصفح'] } },
  },
  ru: {
    selection: { steps: [{ title: 'Оцените лицо', text: 'Начните с пропорций и бесплатной оценки формы лица.' }, { title: 'Сузьте выбор', text: 'Оставьте несколько форм и пропорций оправ.' }, { title: 'Проверьте визуально', text: 'Используйте примерку или сравнение перед решением.' }], principles: ['Форма лица — первый фильтр, а не жёсткое правило.', 'Ширина и масштаб оправы так же важны, как форма.', 'Сравнивайте короткий список кандидатов.'], faq: [{ question: 'Как найти очки, которые мне идут?', answer: 'Оцените пропорции, выберите несколько направлений и проверьте масштаб и стиль на своём фото.' }, { question: 'Достаточно ли формы лица?', answer: 'Нет. Важны ширина, мост, глубина линз, рецепт, комфорт и стиль.' }, { question: 'Можно проверить конкретную оправу?', answer: 'Да. Используйте фото товара или скриншот магазина в виртуальной примерке либо сравните несколько вариантов.' }], faqEyebrow: 'Готовы сузить выбор', ctaLabels: { detector: 'Определить форму бесплатно', advisor: 'Получить совет', tryOn: 'Примерить очки на фото', compare: 'Сравнить оправы' }, howTo: { name: 'Как подобрать очки для лица', description: 'Используйте пропорции лица, сузьте выбор и проверьте оправы на своём фото.', steps: [{ name: 'Определите', text: 'Оцените форму лица по фото.' }, { name: 'Отберите', text: 'Выберите несколько форм и пропорций.' }, { name: 'Проверьте', text: 'Примерьте одну оправу или сравните несколько.' }] } },
    tryOn: { steps: [{ title: 'Загрузите фото', text: 'Используйте чёткое фото анфас.' }, { title: 'Добавьте изображение очков', text: 'Подойдёт фото товара или скриншот магазина.' }, { title: 'Посмотрите и сравните', text: 'Оцените образ и при необходимости сравните варианты.' }], principles: ['Используйте фото анфас.', 'Примерка показывает внешний вид; физический размер проверяйте отдельно.', 'Сравнивайте несколько близких кандидатов.'], faq: [{ question: 'Можно примерить очки на фото онлайн?', answer: 'Да. Загрузите фото лица и изображение очков для предварительного просмотра.' }, { question: 'Можно использовать скриншот магазина?', answer: 'Да. Используйте чистое изображение и уточняйте размер и модель у продавца.' }, { question: 'Как сравнить несколько пар?', answer: 'Используйте Frame Compare для просмотра вариантов рядом.' }], faqEyebrow: 'Готовы к примерке', ctaLabels: { detector: 'Сначала проверить форму лица', advisor: 'Получить совет', tryOn: 'Примерить очки на фото', compare: 'Сравнить оправы рядом' }, software: { description: 'Виртуальная примерка очков в браузере по фото лица и изображению товара.', featureList: ['Загрузить своё фото', 'Использовать фото товара или скриншот', 'Посмотреть конкретную оправу', 'Перейти к сравнению'] } },
    advisor: { steps: [{ title: 'Оцените лицо', text: 'Используйте пропорции как практическую отправную точку.' }, { title: 'Получите рекомендации', text: 'Сведите анализ к нескольким направлениям оправ.' }, { title: 'Проверьте список', text: 'Используйте примерку и сравнение перед решением.' }], principles: ['Рекомендации должны сужать выбор, а не диктовать ответ.', 'Подтверждайте советы визуальной примеркой.', 'Отдельно проверяйте посадку, рецепт и комфорт.'], faq: [{ question: 'Что делает AI-консультант по очкам?', answer: 'Он превращает пропорции лица и фото в практические рекомендации по оправам.' }, { question: 'Это то же самое, что виртуальная примерка?', answer: 'Нет. Консультант выбирает направления, а примерка показывает конкретную оправу.' }, { question: 'Достаточно ли формы лица?', answer: 'Нет. Важны ширина, глубина линз, мост, рецепт и стиль.' }], faqEyebrow: 'Персональный следующий шаг', ctaLabels: { detector: 'Определить форму бесплатно', advisor: 'Открыть AI-консультант', tryOn: 'Примерить очки', compare: 'Сравнить оправы' }, software: { description: 'AI-рекомендации по очкам из фото лица с переходом к примерке и сравнению.', featureList: ['Анализ лица по фото', 'Персональные рекомендации', 'Переход к примерке', 'Переход к сравнению'] } },
    compare: { steps: [{ title: 'Загрузите одно фото', text: 'Используйте чёткое фото анфас.' }, { title: 'Выберите до четырёх оправ', text: 'Выберите пресеты, которые имеет смысл сравнить.' }, { title: 'Смотрите рядом', text: 'Принимайте решение на одной доске сравнения.' }], principles: ['Сначала сравнивайте заметно разные силуэты.', 'Каждый результат оправы использует кредиты.', 'Уточняйте размер и модель у продавца.'], faq: [{ question: 'Как сравнить оправы онлайн?', answer: 'Загрузите фото, выберите до четырёх пресетов и создайте результаты рядом.' }, { question: 'Это лучше примерки по одной?', answer: 'Сравнение помогает, когда несколько вариантов выглядят похоже.' }, { question: 'Нужно сначала знать форму лица?', answer: 'Нет, но бесплатный детектор помогает сузить список.' }], faqEyebrow: 'Следующий шаг', ctaLabels: { detector: 'Определить форму лица', advisor: 'Получить совет', tryOn: 'Сначала примерить одну', compare: 'Открыть сравнение оправ' }, software: { description: 'Сравнение оправ рядом с AI-примеркой на вашем фото.', featureList: ['До четырёх пресетов', 'Результаты рядом', 'Для решения о покупке', 'Работает в браузере'] } },
  },
  de: {
    selection: { steps: [{ title: 'Gesicht verstehen', text: 'Beginne mit Proportionen und einem kostenlosen Gesichtsform-Check.' }, { title: 'Brillen eingrenzen', text: 'Wähle wenige Formen und Proportionen zum Testen.' }, { title: 'Visuell prüfen', text: 'Nutze Anprobe oder Vergleich vor der Entscheidung.' }], principles: ['Gesichtsform ist ein erster Filter, keine starre Regel.', 'Breite und Maßstab sind so wichtig wie die Silhouette.', 'Vergleiche eine kleine Auswahl.'], faq: [{ question: 'Wie finde ich eine Brille, die zu meinem Gesicht passt?', answer: 'Starte mit Proportionen, grenze einige Richtungen ein und prüfe Maßstab und Stil auf deinem Foto.' }, { question: 'Sollte ich nur nach Gesichtsform wählen?', answer: 'Nein. Breite, Steg, Glastiefe, Sehstärke, Komfort und Stil zählen ebenfalls.' }, { question: 'Kann ich ein bestimmtes Modell prüfen?', answer: 'Ja. Nutze Produktbild oder Händler-Screenshot in der virtuellen Anprobe oder vergleiche mehrere Modelle.' }], faqEyebrow: 'Bereit zum Eingrenzen', ctaLabels: { detector: 'Gesichtsform kostenlos erkennen', advisor: 'Brillenberatung öffnen', tryOn: 'Brille auf meinem Foto testen', compare: 'Brillen vergleichen' }, howTo: { name: 'So findest du Brillen für dein Gesicht', description: 'Nutze Gesichtsproportionen, grenze Modelle ein und prüfe sie auf deinem Foto.', steps: [{ name: 'Erkennen', text: 'Schätze deine Gesichtsform aus einem Foto.' }, { name: 'Eingrenzen', text: 'Wähle einige Formen und Proportionen.' }, { name: 'Prüfen', text: 'Teste eine Brille oder vergleiche mehrere.' }] } },
    tryOn: { steps: [{ title: 'Foto hochladen', text: 'Nutze ein klares frontales Gesichtsbild.' }, { title: 'Brillenbild hinzufügen', text: 'Nutze Produktfoto oder Händler-Screenshot.' }, { title: 'Ansehen und vergleichen', text: 'Prüfe den Look und vergleiche bei Bedarf Alternativen.' }], principles: ['Nutze ein frontales Foto.', 'Die Anprobe zeigt den Look; physische Passform separat prüfen.', 'Vergleiche eine kleine Auswahl bei knappen Entscheidungen.'], faq: [{ question: 'Kann ich Brillen online auf einem Foto testen?', answer: 'Ja. Lade ein Gesichtsbild und ein Brillenbild für die Vorschau hoch.' }, { question: 'Kann ich einen Shop-Screenshot verwenden?', answer: 'Ja. Nutze ein sauberes Bild und bestätige Größe und Modell beim Händler.' }, { question: 'Wie vergleiche ich mehrere Brillen?', answer: 'Nutze Frame Compare für eine Ansicht nebeneinander.' }], faqEyebrow: 'Bereit zur Vorschau', ctaLabels: { detector: 'Zuerst Gesichtsform prüfen', advisor: 'Brillenberatung öffnen', tryOn: 'Brille auf meinem Foto testen', compare: 'Brillen nebeneinander vergleichen' }, software: { description: 'Browserbasierte virtuelle Brillenanprobe mit Gesichts- und Produktfoto.', featureList: ['Eigenes Gesichtsbild hochladen', 'Produktbild oder Screenshot verwenden', 'Bestimmte Brille ansehen', 'Zum Vergleich wechseln'] } },
    advisor: { steps: [{ title: 'Gesicht verstehen', text: 'Nutze Proportionen als praktischen Ausgangspunkt.' }, { title: 'Brillenrichtung erhalten', text: 'Reduziere die Analyse auf wenige sinnvolle Richtungen.' }, { title: 'Auswahl prüfen', text: 'Nutze Anprobe und Vergleich vor der Entscheidung.' }], principles: ['Empfehlungen sollen eingrenzen, nicht diktieren.', 'Verbinde Beratung mit visueller Prüfung.', 'Passform, Sehstärke und Komfort separat prüfen.'], faq: [{ question: 'Was macht ein AI-Brillenberater?', answer: 'Er wandelt sichtbare Gesichtsproportionen und dein Foto in praktische Brillenempfehlungen um.' }, { question: 'Ist das dasselbe wie virtuelle Anprobe?', answer: 'Nein. Die Beratung grenzt Richtungen ein; die Anprobe zeigt ein konkretes Modell.' }, { question: 'Reicht die Gesichtsform allein?', answer: 'Nein. Breite, Glastiefe, Steg, Sehstärke und Stil sind ebenfalls wichtig.' }], faqEyebrow: 'Persönlicher nächster Schritt', ctaLabels: { detector: 'Gesichtsform kostenlos erkennen', advisor: 'AI-Brillenberater öffnen', tryOn: 'Brille auf meinem Foto testen', compare: 'Brillen vergleichen' }, software: { description: 'KI-gestützte Brillenberatung aus einem Gesichtsbild mit Anprobe und Vergleich.', featureList: ['Fotoanalyse des Gesichts', 'Personalisierte Brillenberatung', 'Weiter zur Anprobe', 'Weiter zum Vergleich'] } },
    compare: { steps: [{ title: 'Ein Foto hochladen', text: 'Nutze ein klares frontales Foto.' }, { title: 'Bis zu vier Brillen wählen', text: 'Wähle Presets, die sich sinnvoll vergleichen lassen.' }, { title: 'Nebeneinander prüfen', text: 'Entscheide auf einer Vergleichsansicht.' }], principles: ['Vergleiche zuerst deutlich unterschiedliche Silhouetten.', 'Jedes generierte Ergebnis nutzt Credits.', 'Bestätige Größe und Modell beim Händler.'], faq: [{ question: 'Wie vergleiche ich Brillen online?', answer: 'Lade ein Foto hoch, wähle bis zu vier Presets und erzeuge Ergebnisse nebeneinander.' }, { question: 'Ist das besser als einzeln anzuprobieren?', answer: 'Der Direktvergleich hilft, wenn mehrere Formen ähnlich wirken.' }, { question: 'Muss ich meine Gesichtsform kennen?', answer: 'Nein, der kostenlose Check kann die Auswahl aber eingrenzen.' }], faqEyebrow: 'Nächster Schritt', ctaLabels: { detector: 'Gesichtsform erkennen', advisor: 'Brillenberatung öffnen', tryOn: 'Erst eine Brille testen', compare: 'Brillenvergleich öffnen' }, software: { description: 'Brillen nebeneinander mit KI-Anprobe auf deinem Foto vergleichen.', featureList: ['Bis zu vier Presets', 'Ergebnisse nebeneinander', 'Für Kaufentscheidungen', 'Im Browser nutzbar'] } },
  },
  ja: {
    selection: { steps: [{ title: '顔の特徴を確認', text: '顔の比率と無料の顔型診断から始めます。' }, { title: '候補を絞る', text: '試す価値のある形とサイズ感に絞ります。' }, { title: '写真で確認', text: '試着や比較で見た目を確かめてから決めます。' }], principles: ['顔型は最初の絞り込みであり絶対的なルールではありません。', 'フレーム幅とサイズ感も形と同じくらい重要です。', '少数の候補を比較します。'], faq: [{ question: '自分に似合うメガネはどう探しますか？', answer: '顔の比率から候補を絞り、自分の写真でサイズ感とスタイルを確認します。' }, { question: '顔型だけで選んでよいですか？', answer: 'いいえ。幅、ブリッジ、レンズの深さ、度数、快適さ、好みも重要です。' }, { question: '特定の商品を確認できますか？', answer: 'はい。商品画像やショップのスクリーンショットを試着に使うか、複数候補を比較できます。' }], faqEyebrow: '候補を絞る準備', ctaLabels: { detector: '無料で顔型を診断', advisor: 'メガネ提案を見る', tryOn: '自分の写真で試着', compare: 'フレームを比較' }, howTo: { name: '自分の顔に合うメガネの探し方', description: '顔の特徴から候補を絞り、自分の写真で確認します。', steps: [{ name: '診断', text: '写真から顔型を推定します。' }, { name: '絞り込み', text: 'いくつかの形とサイズ感を選びます。' }, { name: '確認', text: '1本を試着するか複数を比較します。' }] } },
    tryOn: { steps: [{ title: '顔写真をアップロード', text: '明るい正面写真を使います。' }, { title: 'メガネ画像を追加', text: '商品写真やショップのスクリーンショットを使います。' }, { title: '試着して比較', text: '見た目を確認し、必要なら候補を比較します。' }], principles: ['正面写真を使うと確認しやすくなります。', '試着は見た目の確認用です。実際のサイズは別途確認してください。', '候補が近いときは比較します。'], faq: [{ question: '写真でメガネを試着できますか？', answer: 'はい。顔写真とメガネ画像をアップロードして見た目を確認できます。' }, { question: 'ショップのスクリーンショットも使えますか？', answer: 'はい。きれいな画像を使い、正確なサイズと型番は販売店で確認してください。' }, { question: '複数のメガネを比べるには？', answer: 'Frame Compareで候補を並べて確認できます。' }], faqEyebrow: '試着を始める', ctaLabels: { detector: '先に顔型を確認', advisor: 'メガネ提案を見る', tryOn: '自分の写真で試着', compare: 'フレームを並べて比較' }, software: { description: '顔写真と商品画像からブラウザでメガネをバーチャル試着できます。', featureList: ['自分の顔写真を使用', '商品画像やスクリーンショットを使用', '特定のフレームを確認', '比較へ進む'] } },
    advisor: { steps: [{ title: '顔の特徴を確認', text: '顔の比率を実用的な出発点にします。' }, { title: 'フレーム提案を取得', text: '分析から試す価値のある方向を絞ります。' }, { title: '候補を確認', text: '試着と比較で決定前に確認します。' }], principles: ['提案は候補を絞るために使います。', '提案を写真での確認につなげます。', 'フィット、度数、快適さは別に確認します。'], faq: [{ question: 'AIメガネアドバイザーは何をしますか？', answer: '顔の比率と写真から実用的なフレームの方向を提案します。' }, { question: 'バーチャル試着と同じですか？', answer: 'いいえ。アドバイザーは方向を絞り、試着は特定のフレームの見た目を確認します。' }, { question: '顔型だけで十分ですか？', answer: 'いいえ。幅、レンズの深さ、ブリッジ、度数、好みも重要です。' }], faqEyebrow: 'パーソナルな次のステップ', ctaLabels: { detector: '無料で顔型を診断', advisor: 'AIメガネアドバイザーを開く', tryOn: '自分の写真で試着', compare: 'フレームを比較' }, software: { description: '顔写真からAIがメガネ選びを支援し、試着と比較へつなげます。', featureList: ['写真による顔分析', 'パーソナルなフレーム提案', '試着へ進む', '比較へ進む'] } },
    compare: { steps: [{ title: '写真を1枚アップロード', text: '明るい正面写真を使います。' }, { title: '最大4本を選択', text: '比較したいプリセットを選びます。' }, { title: '並べて確認', text: '1つの比較画面で判断します。' }], principles: ['まず違いが分かりやすい形を比較します。', '生成する各フレーム結果にはクレジットを使います。', '正確なサイズと型番は販売店で確認してください。'], faq: [{ question: 'オンラインでフレームを比較する方法は？', answer: '顔写真をアップロードし、最大4つのプリセットを選んで並べて結果を生成します。' }, { question: '1本ずつ試すより良いですか？', answer: '候補が似ているときは並べて比較すると判断しやすくなります。' }, { question: '先に顔型を知る必要がありますか？', answer: '必須ではありませんが、無料診断で候補を絞れます。' }], faqEyebrow: '次のステップ', ctaLabels: { detector: '顔型を診断', advisor: 'メガネ提案を見る', tryOn: 'まず1本を試着', compare: 'フレーム比較を開く' }, software: { description: '自分の写真でAI試着結果を並べてメガネフレームを比較します。', featureList: ['最大4つのプリセット', '並べた試着結果', '購入判断を支援', 'ブラウザで利用'] } },
  },
  es: {
    selection: { steps: [{ title: 'Entiende tu rostro', text: 'Empieza por las proporciones y una estimación gratuita de la forma facial.' }, { title: 'Reduce las opciones', text: 'Elige unas pocas formas y proporciones para probar.' }, { title: 'Valida visualmente', text: 'Usa prueba virtual o comparación antes de decidir.' }], principles: ['Usa la forma facial como primer filtro, no como regla rígida.', 'El ancho y la escala importan tanto como la silueta.', 'Compara una lista corta de candidatos.'], faq: [{ question: '¿Cómo encuentro gafas que me favorezcan?', answer: 'Empieza por las proporciones, reduce algunas direcciones y comprueba escala y estilo en tu foto.' }, { question: '¿Debo elegir solo por la forma de la cara?', answer: 'No. También importan ancho, puente, profundidad de lente, graduación, comodidad y estilo.' }, { question: '¿Puedo probar una montura concreta?', answer: 'Sí. Usa una foto de producto o captura de tienda en la prueba virtual, o compara varias opciones.' }], faqEyebrow: 'Listo para reducir opciones', ctaLabels: { detector: 'Detectar mi forma gratis', advisor: 'Obtener consejo sobre gafas', tryOn: 'Probar gafas en mi foto', compare: 'Comparar monturas' }, howTo: { name: 'Cómo encontrar gafas para tu cara', description: 'Usa proporciones faciales, reduce opciones y valídalas en tu foto.', steps: [{ name: 'Detectar', text: 'Estima la forma de tu cara con una foto.' }, { name: 'Reducir', text: 'Elige unas pocas formas y proporciones.' }, { name: 'Validar', text: 'Prueba una montura o compara varias.' }] } },
    tryOn: { steps: [{ title: 'Sube tu foto', text: 'Usa una foto frontal clara.' }, { title: 'Añade la imagen de las gafas', text: 'Usa una foto de producto o captura de tienda.' }, { title: 'Previsualiza y compara', text: 'Comprueba el aspecto y compara alternativas si hace falta.' }], principles: ['Usa una foto frontal.', 'La prueba ayuda con el aspecto; confirma el ajuste físico aparte.', 'Compara una lista corta cuando las opciones estén cerca.'], faq: [{ question: '¿Puedo probar gafas en una foto online?', answer: 'Sí. Sube una foto de tu cara y una imagen de las gafas para ver una vista previa.' }, { question: '¿Puedo usar una captura de una tienda?', answer: 'Sí. Usa una imagen limpia y confirma talla y modelo con el vendedor.' }, { question: '¿Cómo comparo varios pares?', answer: 'Usa Frame Compare para ver los candidatos lado a lado.' }], faqEyebrow: 'Listo para probar', ctaLabels: { detector: 'Comprobar primero mi forma facial', advisor: 'Obtener consejo', tryOn: 'Probar gafas en mi foto', compare: 'Comparar monturas lado a lado' }, software: { description: 'Prueba virtual de gafas en el navegador con una foto facial y una imagen de producto.', featureList: ['Sube tu propia foto', 'Usa imagen de producto o captura', 'Previsualiza una montura', 'Continúa a comparación'] } },
    advisor: { steps: [{ title: 'Entiende tu rostro', text: 'Usa las proporciones como punto de partida práctico.' }, { title: 'Obtén orientación', text: 'Convierte el análisis en unas pocas direcciones de montura.' }, { title: 'Valida la selección', text: 'Usa prueba virtual y comparación antes de decidir.' }], principles: ['Usa las recomendaciones para reducir opciones.', 'Conecta el consejo con una comprobación visual.', 'Separa aspecto de ajuste, graduación y comodidad.'], faq: [{ question: '¿Qué hace un asesor de gafas con IA?', answer: 'Convierte las proporciones visibles y tu foto en orientación práctica sobre monturas.' }, { question: '¿Es lo mismo que la prueba virtual?', answer: 'No. El asesor reduce direcciones; la prueba muestra una montura concreta.' }, { question: '¿Basta la forma de la cara?', answer: 'No. También importan ancho, profundidad, puente, graduación y estilo.' }], faqEyebrow: 'Siguiente paso personalizado', ctaLabels: { detector: 'Detectar mi forma gratis', advisor: 'Abrir asesor de gafas IA', tryOn: 'Probar gafas en mi foto', compare: 'Comparar monturas' }, software: { description: 'Orientación de gafas asistida por IA desde una foto, conectada con prueba virtual y comparación.', featureList: ['Análisis facial por foto', 'Orientación personalizada', 'Continuar a prueba virtual', 'Continuar a comparación'] } },
    compare: { steps: [{ title: 'Sube una foto', text: 'Usa una foto frontal clara.' }, { title: 'Elige hasta cuatro monturas', text: 'Selecciona presets útiles para comparar.' }, { title: 'Revísalas lado a lado', text: 'Decide desde una sola vista de comparación.' }], principles: ['Compara primero siluetas claramente distintas.', 'Cada resultado generado usa créditos.', 'Confirma talla y modelo con el vendedor.'], faq: [{ question: '¿Cómo comparo monturas online?', answer: 'Sube una foto, elige hasta cuatro presets y genera resultados lado a lado.' }, { question: '¿Es mejor que probar una por una?', answer: 'La comparación ayuda cuando varias opciones se parecen.' }, { question: '¿Necesito saber mi forma facial primero?', answer: 'No, aunque el detector gratuito puede reducir la lista.' }], faqEyebrow: 'Siguiente paso', ctaLabels: { detector: 'Detectar mi forma facial', advisor: 'Obtener consejo', tryOn: 'Probar una primero', compare: 'Abrir comparación de monturas' }, software: { description: 'Compara monturas lado a lado con resultados de prueba IA sobre tu foto.', featureList: ['Hasta cuatro presets', 'Resultados lado a lado', 'Pensado para decisiones de compra', 'Funciona en navegador'] } },
  },
  pt: {
    selection: { steps: [{ title: 'Entenda seu rosto', text: 'Comece pelas proporções e uma estimativa gratuita do formato do rosto.' }, { title: 'Reduza as opções', text: 'Escolha algumas formas e proporções para testar.' }, { title: 'Valide visualmente', text: 'Use prova virtual ou comparação antes de decidir.' }], principles: ['Use o formato do rosto como primeiro filtro, não como regra rígida.', 'Largura e escala importam tanto quanto a silhueta.', 'Compare uma lista curta de candidatos.'], faq: [{ question: 'Como encontro óculos que combinam com meu rosto?', answer: 'Comece pelas proporções, reduza algumas direções e confira escala e estilo na sua foto.' }, { question: 'Devo escolher só pelo formato do rosto?', answer: 'Não. Largura, ponte, profundidade da lente, grau, conforto e estilo também importam.' }, { question: 'Posso testar uma armação específica?', answer: 'Sim. Use uma imagem de produto ou captura da loja na prova virtual, ou compare várias opções.' }], faqEyebrow: 'Pronto para reduzir as opções', ctaLabels: { detector: 'Detectar meu rosto grátis', advisor: 'Receber recomendação', tryOn: 'Provar óculos na minha foto', compare: 'Comparar armações' }, howTo: { name: 'Como encontrar óculos para seu rosto', description: 'Use proporções faciais, reduza opções e valide na sua foto.', steps: [{ name: 'Detectar', text: 'Estime o formato do rosto por uma foto.' }, { name: 'Reduzir', text: 'Escolha algumas formas e proporções.' }, { name: 'Validar', text: 'Prove uma armação ou compare várias.' }] } },
    tryOn: { steps: [{ title: 'Envie sua foto', text: 'Use uma foto frontal nítida.' }, { title: 'Adicione a imagem dos óculos', text: 'Use foto de produto ou captura da loja.' }, { title: 'Visualize e compare', text: 'Confira o visual e compare alternativas se necessário.' }], principles: ['Use uma foto frontal.', 'A prova ajuda com aparência; confirme o ajuste físico separadamente.', 'Compare uma lista curta quando as opções estiverem próximas.'], faq: [{ question: 'Posso provar óculos em uma foto online?', answer: 'Sim. Envie uma foto do rosto e uma imagem dos óculos para visualizar.' }, { question: 'Posso usar captura de uma loja?', answer: 'Sim. Use uma imagem limpa e confirme tamanho e modelo com o vendedor.' }, { question: 'Como comparar vários pares?', answer: 'Use Frame Compare para ver candidatos lado a lado.' }], faqEyebrow: 'Pronto para visualizar', ctaLabels: { detector: 'Verificar meu rosto primeiro', advisor: 'Receber recomendação', tryOn: 'Provar óculos na minha foto', compare: 'Comparar armações lado a lado' }, software: { description: 'Prova virtual de óculos no navegador com foto do rosto e imagem do produto.', featureList: ['Envie sua própria foto', 'Use imagem de produto ou captura', 'Visualize uma armação específica', 'Continue para comparação'] } },
    advisor: { steps: [{ title: 'Entenda seu rosto', text: 'Use as proporções como ponto de partida prático.' }, { title: 'Receba orientação', text: 'Transforme a análise em poucas direções de armação.' }, { title: 'Valide a seleção', text: 'Use prova virtual e comparação antes de decidir.' }], principles: ['Use recomendações para reduzir opções.', 'Conecte orientação com prova visual.', 'Separe aparência de ajuste, grau e conforto.'], faq: [{ question: 'O que faz um consultor de óculos com IA?', answer: 'Transforma proporções visíveis e sua foto em orientação prática de armações.' }, { question: 'É igual à prova virtual?', answer: 'Não. O consultor reduz direções; a prova mostra uma armação específica.' }, { question: 'Só o formato do rosto basta?', answer: 'Não. Largura, profundidade, ponte, grau e estilo também importam.' }], faqEyebrow: 'Próximo passo personalizado', ctaLabels: { detector: 'Detectar meu rosto grátis', advisor: 'Abrir consultor de óculos IA', tryOn: 'Provar óculos na minha foto', compare: 'Comparar armações' }, software: { description: 'Orientação de óculos com IA a partir de uma foto, ligada à prova virtual e comparação.', featureList: ['Análise facial por foto', 'Orientação personalizada', 'Continuar para prova', 'Continuar para comparação'] } },
    compare: { steps: [{ title: 'Envie uma foto', text: 'Use uma foto frontal nítida.' }, { title: 'Escolha até quatro armações', text: 'Selecione presets úteis para comparar.' }, { title: 'Revise lado a lado', text: 'Decida em uma única visão comparativa.' }], principles: ['Compare primeiro silhuetas claramente diferentes.', 'Cada resultado gerado usa créditos.', 'Confirme tamanho e modelo com o vendedor.'], faq: [{ question: 'Como comparar armações online?', answer: 'Envie uma foto, escolha até quatro presets e gere resultados lado a lado.' }, { question: 'É melhor do que provar uma por vez?', answer: 'A comparação ajuda quando várias opções parecem semelhantes.' }, { question: 'Preciso saber meu formato de rosto antes?', answer: 'Não, mas o detector grátis pode reduzir a lista.' }], faqEyebrow: 'Próximo passo', ctaLabels: { detector: 'Detectar formato do rosto', advisor: 'Receber recomendação', tryOn: 'Provar uma primeiro', compare: 'Abrir comparação de armações' }, software: { description: 'Compare armações lado a lado com resultados de prova IA na sua foto.', featureList: ['Até quatro presets', 'Resultados lado a lado', 'Para decisões de compra', 'Funciona no navegador'] } },
  },
  fr: {
    selection: { steps: [{ title: 'Comprendre votre visage', text: 'Commencez par les proportions et une estimation gratuite de la forme du visage.' }, { title: 'Réduire les options', text: 'Retenez quelques formes et proportions à tester.' }, { title: 'Valider visuellement', text: 'Utilisez l’essayage ou la comparaison avant de décider.' }], principles: ['Utilisez la forme du visage comme premier filtre, pas comme règle rigide.', 'La largeur et l’échelle comptent autant que la silhouette.', 'Comparez une courte sélection.'], faq: [{ question: 'Comment trouver des lunettes qui me vont ?', answer: 'Commencez par les proportions, retenez quelques directions puis vérifiez l’échelle et le style sur votre photo.' }, { question: 'Faut-il choisir uniquement selon la forme du visage ?', answer: 'Non. Largeur, pont, profondeur des verres, correction, confort et style comptent aussi.' }, { question: 'Puis-je tester une monture précise ?', answer: 'Oui. Utilisez une photo produit ou une capture de boutique dans l’essayage, ou comparez plusieurs montures.' }], faqEyebrow: 'Prêt à réduire les options', ctaLabels: { detector: 'Détecter ma forme gratuitement', advisor: 'Obtenir des conseils', tryOn: 'Essayer des lunettes sur ma photo', compare: 'Comparer les montures' }, howTo: { name: 'Comment trouver des lunettes pour votre visage', description: 'Utilisez les proportions, réduisez les options et validez-les sur votre photo.', steps: [{ name: 'Détecter', text: 'Estimez la forme du visage depuis une photo.' }, { name: 'Réduire', text: 'Choisissez quelques formes et proportions.' }, { name: 'Valider', text: 'Essayez une monture ou comparez-en plusieurs.' }] } },
    tryOn: { steps: [{ title: 'Importer votre photo', text: 'Utilisez une photo de face nette.' }, { title: 'Ajouter l’image des lunettes', text: 'Utilisez une photo produit ou une capture de boutique.' }, { title: 'Prévisualiser et comparer', text: 'Vérifiez le rendu puis comparez si nécessaire.' }], principles: ['Utilisez une photo de face.', 'L’essayage vérifie le rendu ; confirmez l’ajustement physique séparément.', 'Comparez une courte sélection si les options sont proches.'], faq: [{ question: 'Puis-je essayer des lunettes sur une photo ?', answer: 'Oui. Importez une photo de visage et une image de lunettes pour voir le rendu.' }, { question: 'Puis-je utiliser une capture de boutique ?', answer: 'Oui. Utilisez une image propre et confirmez taille et modèle auprès du vendeur.' }, { question: 'Comment comparer plusieurs paires ?', answer: 'Utilisez Frame Compare pour voir les candidats côte à côte.' }], faqEyebrow: 'Prêt à essayer', ctaLabels: { detector: 'Vérifier d’abord ma forme', advisor: 'Obtenir des conseils', tryOn: 'Essayer des lunettes sur ma photo', compare: 'Comparer côte à côte' }, software: { description: 'Essayage virtuel de lunettes dans le navigateur avec photo du visage et image produit.', featureList: ['Importer votre photo', 'Utiliser une image produit ou capture', 'Voir une monture précise', 'Continuer vers la comparaison'] } },
    advisor: { steps: [{ title: 'Comprendre votre visage', text: 'Utilisez les proportions comme point de départ pratique.' }, { title: 'Obtenir des orientations', text: 'Transformez l’analyse en quelques directions de montures.' }, { title: 'Valider la sélection', text: 'Utilisez essayage et comparaison avant de décider.' }], principles: ['Utilisez les recommandations pour réduire les choix.', 'Reliez les conseils à une vérification visuelle.', 'Séparez apparence, ajustement, correction et confort.'], faq: [{ question: 'Que fait un conseiller lunettes IA ?', answer: 'Il transforme les proportions visibles et votre photo en conseils pratiques de montures.' }, { question: 'Est-ce la même chose que l’essayage virtuel ?', answer: 'Non. Le conseiller réduit les directions ; l’essayage montre une monture précise.' }, { question: 'La forme du visage suffit-elle ?', answer: 'Non. Largeur, profondeur, pont, correction et style comptent aussi.' }], faqEyebrow: 'Prochaine étape personnalisée', ctaLabels: { detector: 'Détecter ma forme gratuitement', advisor: 'Ouvrir le conseiller lunettes IA', tryOn: 'Essayer sur ma photo', compare: 'Comparer les montures' }, software: { description: 'Conseils lunettes assistés par IA depuis une photo, reliés à l’essayage et à la comparaison.', featureList: ['Analyse du visage par photo', 'Conseils personnalisés', 'Continuer vers l’essayage', 'Continuer vers la comparaison'] } },
    compare: { steps: [{ title: 'Importer une photo', text: 'Utilisez une photo de face nette.' }, { title: 'Choisir jusqu’à quatre montures', text: 'Sélectionnez des modèles utiles à comparer.' }, { title: 'Voir côte à côte', text: 'Décidez depuis une seule vue comparative.' }], principles: ['Comparez d’abord des silhouettes clairement différentes.', 'Chaque résultat généré utilise des crédits.', 'Confirmez taille et modèle auprès du vendeur.'], faq: [{ question: 'Comment comparer des montures en ligne ?', answer: 'Importez une photo, choisissez jusqu’à quatre modèles et générez les résultats côte à côte.' }, { question: 'Est-ce mieux que d’essayer une paire à la fois ?', answer: 'La comparaison aide lorsque plusieurs options se ressemblent.' }, { question: 'Dois-je connaître ma forme de visage avant ?', answer: 'Non, mais le détecteur gratuit peut réduire la liste.' }], faqEyebrow: 'Étape suivante', ctaLabels: { detector: 'Détecter ma forme', advisor: 'Obtenir des conseils', tryOn: 'Essayer une paire', compare: 'Ouvrir la comparaison' }, software: { description: 'Comparez des montures côte à côte avec des résultats d’essayage IA sur votre photo.', featureList: ['Jusqu’à quatre modèles', 'Résultats côte à côte', 'Pour décider avant achat', 'Fonctionne dans le navigateur'] } },
  },
}

const routeSeeds: Record<Locale, Record<SearchToToolPhaseARouteId, RouteSeed>> = {
  en: {
    'find-glasses-for-my-face': { kind: 'selection', metaTitle: 'Find Glasses for My Face from a Photo | VisuTry', metaDescription: 'Find glasses for your face from one photo. Detect your likely face shape, shortlist frame directions, then validate them with virtual try-on or side-by-side compare.', eyebrow: 'Photo-first frame shortlisting', title: 'Find Glasses for My Face', intro: 'Turn one photo into a practical shortlist: understand your face proportions, narrow the frame directions worth trying, then validate the final candidates visually.', faqTitle: 'Move from shortlist to visual proof' },
    'try-glasses-on-photo': { kind: 'tryOn', metaTitle: 'Try Glasses on a Photo Online | VisuTry', metaDescription: 'Try glasses on your photo online. Upload a clear face photo and a glasses product image or screenshot, preview the look, then compare alternative frames side by side.', eyebrow: 'Photo-based virtual glasses preview', title: 'Try Glasses on Your Photo Online', intro: 'Upload your own photo and a glasses image to preview one specific pair, then compare alternatives side by side when you need more confidence before buying.', faqTitle: 'Start with your photo and one frame' },
    'ai-glasses-advisor': { kind: 'advisor', metaTitle: 'AI Glasses Advisor: Find Frames for Your Face | VisuTry', metaDescription: 'Use the VisuTry AI glasses advisor to turn a face photo into practical frame guidance, then validate the shortlist with virtual try-on or side-by-side comparison.', eyebrow: 'Personalized eyewear guidance', title: 'AI Glasses Advisor', intro: 'Use your photo to narrow the frame directions worth considering, understand why they may work, then validate the shortlist with try-on or side-by-side comparison.', faqTitle: 'Open the glasses advisor' },
    'what-glasses-suit-my-face': { kind: 'selection', metaTitle: 'What Glasses Suit My Face? Upload a Photo and Shortlist Frames', metaDescription: 'What glasses suit my face? Use the free face shape detector on your photo, shortlist frame shapes, then confirm with virtual try-on or side-by-side compare.', eyebrow: 'Photo-first glasses advice', title: 'What Glasses Suit My Face?', intro: 'Upload one photo to estimate your face shape, turn that into a practical frame shortlist, then confirm the look with try-on or frame compare.', faqTitle: 'Start with a free photo check' },
    'virtual-glasses-try-on': { kind: 'tryOn', metaTitle: 'Virtual Glasses Try On from Your Photo | VisuTry', metaDescription: 'Virtual glasses try on online from a face photo and any glasses product image or screenshot. See the look before you buy, then compare frames side by side.', eyebrow: 'Virtual try-on from your photo', title: 'Virtual Glasses Try On Online', intro: 'See how glasses look on your face before you buy. Upload your photo and a frame image, then continue into compare when you want a cleaner side-by-side decision.', faqTitle: 'Start with a photo try-on' },
    'compare-glasses-frames': { kind: 'compare', metaTitle: 'Compare Glasses Frames Side by Side on Your Photo | VisuTry', metaDescription: 'Compare glasses frames on your photo. Choose up to four built-in presets, generate AI try-on results side by side, and decide which look works better.', eyebrow: 'Side-by-side frame decisions', title: 'Compare Glasses Frames on Your Photo', intro: 'When one try-on is not enough, compare a few frame directions together. Pick presets, generate results side by side, and keep the look that fits you best.', faqTitle: 'Open side-by-side compare' },
  },
  id: {
    'find-glasses-for-my-face': { kind: 'selection', metaTitle: 'Cari Kacamata untuk Wajah Saya dari Foto | VisuTry', metaDescription: 'Temukan kacamata untuk wajah Anda dari satu foto, pilih beberapa arah frame, lalu validasi dengan coba virtual atau perbandingan.', eyebrow: 'Pemilihan frame berbasis foto', title: 'Cari Kacamata untuk Wajah Saya', intro: 'Ubah satu foto menjadi shortlist praktis: pahami proporsi wajah, persempit arah frame, lalu validasi kandidat secara visual.', faqTitle: 'Dari shortlist ke bukti visual' },
    'try-glasses-on-photo': { kind: 'tryOn', metaTitle: 'Coba Kacamata pada Foto Online | VisuTry', metaDescription: 'Unggah foto wajah dan gambar kacamata untuk mencoba secara virtual, lalu bandingkan alternatif berdampingan.', eyebrow: 'Pratinjau kacamata dari foto', title: 'Coba Kacamata pada Foto Anda', intro: 'Unggah foto Anda dan gambar kacamata untuk melihat satu pasangan, lalu bandingkan alternatif jika Anda membutuhkan kepastian lebih.', faqTitle: 'Mulai dari foto dan satu frame' },
    'ai-glasses-advisor': { kind: 'advisor', metaTitle: 'AI Glasses Advisor: Cari Frame untuk Wajah Anda | VisuTry', metaDescription: 'Gunakan AI glasses advisor VisuTry untuk mengubah foto wajah menjadi panduan frame dan validasi dengan coba virtual.', eyebrow: 'Panduan kacamata personal', title: 'AI Glasses Advisor', intro: 'Gunakan foto Anda untuk mempersempit arah frame yang layak dipertimbangkan, lalu validasi dengan coba virtual atau perbandingan.', faqTitle: 'Buka glasses advisor' },
    'what-glasses-suit-my-face': { kind: 'selection', metaTitle: 'Kacamata Apa yang Cocok untuk Wajah Saya? | VisuTry', metaDescription: 'Gunakan detektor bentuk wajah gratis, pilih beberapa bentuk frame, lalu konfirmasikan dengan coba virtual atau perbandingan.', eyebrow: 'Saran kacamata berbasis foto', title: 'Kacamata Apa yang Cocok untuk Wajah Saya?', intro: 'Unggah satu foto, perkirakan bentuk wajah, buat shortlist frame, lalu konfirmasikan tampilannya secara visual.', faqTitle: 'Mulai dengan pemeriksaan foto gratis' },
    'virtual-glasses-try-on': { kind: 'tryOn', metaTitle: 'Coba Kacamata Virtual dari Foto | VisuTry', metaDescription: 'Coba kacamata secara virtual dari foto wajah dan gambar produk atau screenshot, lalu bandingkan frame.', eyebrow: 'Coba virtual dari foto Anda', title: 'Coba Kacamata Virtual Online', intro: 'Lihat bagaimana kacamata terlihat sebelum membeli. Unggah foto dan gambar frame, lalu bandingkan alternatif bila perlu.', faqTitle: 'Mulai dengan coba dari foto' },
    'compare-glasses-frames': { kind: 'compare', metaTitle: 'Bandingkan Frame Kacamata pada Foto | VisuTry', metaDescription: 'Bandingkan hingga empat preset frame dengan hasil coba AI berdampingan pada foto Anda.', eyebrow: 'Keputusan frame berdampingan', title: 'Bandingkan Frame Kacamata pada Foto Anda', intro: 'Saat satu try-on belum cukup, bandingkan beberapa arah frame dalam satu tampilan untuk keputusan yang lebih jelas.', faqTitle: 'Buka perbandingan berdampingan' },
  },
  ar: {
    'find-glasses-for-my-face': { kind: 'selection', metaTitle: 'اعثر على نظارات تناسب وجهي من صورة | VisuTry', metaDescription: 'استخدم صورة واحدة لتحديد اتجاهات الإطارات ثم تحقق منها بالتجربة الافتراضية أو المقارنة.', eyebrow: 'اختيار إطارات يبدأ بالصورة', title: 'اعثر على نظارات تناسب وجهي', intro: 'حوّل صورة واحدة إلى قائمة عملية: افهم نسب وجهك، اختصر اتجاهات الإطارات، ثم تحقق من المرشحين بصريًا.', faqTitle: 'من القائمة المختصرة إلى التحقق البصري' },
    'try-glasses-on-photo': { kind: 'tryOn', metaTitle: 'جرّب النظارات على صورة أونلاين | VisuTry', metaDescription: 'ارفع صورة وجه وصورة نظارات لمعاينة المظهر ثم قارن البدائل جنبًا إلى جنب.', eyebrow: 'معاينة نظارات بالاعتماد على الصورة', title: 'جرّب النظارات على صورتك', intro: 'ارفع صورتك وصورة النظارات لمعاينة إطار محدد، ثم قارن البدائل إذا احتجت إلى ثقة أكبر.', faqTitle: 'ابدأ بصورتك وإطار واحد' },
    'ai-glasses-advisor': { kind: 'advisor', metaTitle: 'مستشار نظارات بالذكاء الاصطناعي | VisuTry', metaDescription: 'حوّل صورة الوجه إلى إرشاد عملي للإطارات ثم تحقق من القائمة بالتجربة أو المقارنة.', eyebrow: 'إرشاد شخصي للنظارات', title: 'مستشار النظارات بالذكاء الاصطناعي', intro: 'استخدم صورتك لتقليل اتجاهات الإطارات وفهم سبب ملاءمتها ثم تحقق بالتجربة أو المقارنة.', faqTitle: 'افتح مستشار النظارات' },
    'what-glasses-suit-my-face': { kind: 'selection', metaTitle: 'ما النظارات التي تناسب وجهي؟ | VisuTry', metaDescription: 'استخدم كاشف شكل الوجه المجاني، اختصر أشكال الإطارات ثم تحقق بالتجربة الافتراضية أو المقارنة.', eyebrow: 'نصيحة نظارات تبدأ بالصورة', title: 'ما النظارات التي تناسب وجهي؟', intro: 'ارفع صورة لتقدير شكل الوجه، حوّل النتيجة إلى قائمة إطارات، ثم تحقق من المظهر بصريًا.', faqTitle: 'ابدأ بفحص مجاني للصورة' },
    'virtual-glasses-try-on': { kind: 'tryOn', metaTitle: 'تجربة نظارات افتراضية من صورتك | VisuTry', metaDescription: 'جرّب النظارات افتراضيًا باستخدام صورة وجه وصورة منتج أو لقطة شاشة ثم قارن الإطارات.', eyebrow: 'تجربة افتراضية من صورتك', title: 'تجربة النظارات الافتراضية أونلاين', intro: 'شاهد كيف تبدو النظارات قبل الشراء. ارفع صورتك وصورة إطار ثم قارن البدائل عند الحاجة.', faqTitle: 'ابدأ بتجربة من الصورة' },
    'compare-glasses-frames': { kind: 'compare', metaTitle: 'قارن إطارات النظارات على صورتك | VisuTry', metaDescription: 'قارن حتى أربعة إطارات بنتائج تجربة AI جنبًا إلى جنب على صورتك.', eyebrow: 'قرار الإطارات جنبًا إلى جنب', title: 'قارن إطارات النظارات على صورتك', intro: 'عندما لا تكفي تجربة واحدة، قارن عدة اتجاهات للإطارات معًا واتخذ قرارًا أوضح.', faqTitle: 'افتح المقارنة جنبًا إلى جنب' },
  },
  ru: {
    'find-glasses-for-my-face': { kind: 'selection', metaTitle: 'Подобрать очки для моего лица по фото | VisuTry', metaDescription: 'Подберите направления оправ по одному фото и проверьте их виртуальной примеркой или сравнением.', eyebrow: 'Подбор оправ по фото', title: 'Подобрать очки для моего лица', intro: 'Превратите одно фото в практический список: оцените пропорции, сузьте направления оправ и проверьте кандидатов визуально.', faqTitle: 'От списка к визуальной проверке' },
    'try-glasses-on-photo': { kind: 'tryOn', metaTitle: 'Примерить очки на фото онлайн | VisuTry', metaDescription: 'Загрузите фото лица и изображение очков, оцените образ и сравните альтернативы рядом.', eyebrow: 'Виртуальная примерка по фото', title: 'Примерить очки на своём фото', intro: 'Загрузите своё фото и изображение очков, чтобы посмотреть конкретную пару и сравнить альтернативы.', faqTitle: 'Начните с фото и одной оправы' },
    'ai-glasses-advisor': { kind: 'advisor', metaTitle: 'AI-консультант по очкам для вашего лица | VisuTry', metaDescription: 'Получите практические рекомендации по оправам из фото лица и проверьте их примеркой или сравнением.', eyebrow: 'Персональные рекомендации по очкам', title: 'AI-консультант по очкам', intro: 'Используйте фото, чтобы сузить направления оправ, понять рекомендации и проверить список визуально.', faqTitle: 'Открыть консультант по очкам' },
    'what-glasses-suit-my-face': { kind: 'selection', metaTitle: 'Какие очки подходят моему лицу? | VisuTry', metaDescription: 'Определите форму лица бесплатно, сузьте формы оправ и подтвердите выбор виртуальной примеркой.', eyebrow: 'Советы по очкам из фото', title: 'Какие очки подходят моему лицу?', intro: 'Загрузите фото, оцените форму лица, составьте список оправ и проверьте образ примеркой или сравнением.', faqTitle: 'Начните с бесплатной проверки фото' },
    'virtual-glasses-try-on': { kind: 'tryOn', metaTitle: 'Виртуальная примерка очков по фото | VisuTry', metaDescription: 'Примерьте очки по фото лица и изображению товара или скриншоту, затем сравните варианты.', eyebrow: 'Виртуальная примерка по вашему фото', title: 'Виртуальная примерка очков онлайн', intro: 'Посмотрите, как очки выглядят до покупки: загрузите фото и изображение оправы, затем сравните варианты.', faqTitle: 'Начните с примерки по фото' },
    'compare-glasses-frames': { kind: 'compare', metaTitle: 'Сравнить оправы очков на фото | VisuTry', metaDescription: 'Сравните до четырёх пресетов оправ с AI-примеркой рядом на вашем фото.', eyebrow: 'Сравнение оправ рядом', title: 'Сравнить оправы очков на своём фото', intro: 'Если одной примерки мало, сравните несколько направлений оправ в одной визуальной доске.', faqTitle: 'Открыть сравнение рядом' },
  },
  de: {
    'find-glasses-for-my-face': { kind: 'selection', metaTitle: 'Brille für mein Gesicht per Foto finden | VisuTry', metaDescription: 'Finde passende Brillenrichtungen aus einem Foto und prüfe sie per virtueller Anprobe oder Direktvergleich.', eyebrow: 'Brillenauswahl mit Foto als Ausgangspunkt', title: 'Brille für mein Gesicht finden', intro: 'Mach aus einem Foto eine praktische Auswahl: Proportionen verstehen, Brillenrichtungen eingrenzen und Kandidaten visuell prüfen.', faqTitle: 'Von der Auswahl zur visuellen Prüfung' },
    'try-glasses-on-photo': { kind: 'tryOn', metaTitle: 'Brille online auf Foto anprobieren | VisuTry', metaDescription: 'Lade Gesichtsbild und Brillenfoto hoch, sieh den Look und vergleiche Alternativen nebeneinander.', eyebrow: 'Virtuelle Brillenvorschau per Foto', title: 'Brille auf deinem Foto anprobieren', intro: 'Lade dein Foto und ein Brillenbild hoch, prüfe ein konkretes Modell und vergleiche bei Bedarf Alternativen.', faqTitle: 'Mit Foto und einer Brille starten' },
    'ai-glasses-advisor': { kind: 'advisor', metaTitle: 'AI-Brillenberater: Brillen für dein Gesicht | VisuTry', metaDescription: 'Verwandle ein Gesichtsbild in praktische Brillenberatung und prüfe die Auswahl per Anprobe oder Vergleich.', eyebrow: 'Personalisierte Brillenberatung', title: 'AI-Brillenberater', intro: 'Nutze dein Foto, um sinnvolle Brillenrichtungen einzugrenzen und die Auswahl anschließend visuell zu prüfen.', faqTitle: 'Brillenberater öffnen' },
    'what-glasses-suit-my-face': { kind: 'selection', metaTitle: 'Welche Brille passt zu meinem Gesicht? | VisuTry', metaDescription: 'Nutze den kostenlosen Gesichtsform-Check, grenze Brillenformen ein und bestätige sie per virtueller Anprobe.', eyebrow: 'Brillenberatung mit Foto', title: 'Welche Brille passt zu meinem Gesicht?', intro: 'Lade ein Foto hoch, schätze deine Gesichtsform, erstelle eine kleine Auswahl und prüfe den Look visuell.', faqTitle: 'Mit einem kostenlosen Foto-Check starten' },
    'virtual-glasses-try-on': { kind: 'tryOn', metaTitle: 'Virtuelle Brillenanprobe mit deinem Foto | VisuTry', metaDescription: 'Probiere Brillen virtuell mit Gesichtsbild und Produktfoto oder Screenshot und vergleiche Varianten.', eyebrow: 'Virtuelle Anprobe mit deinem Foto', title: 'Virtuelle Brillenanprobe online', intro: 'Sieh vor dem Kauf, wie eine Brille wirkt. Lade Foto und Brillenbild hoch und vergleiche bei Bedarf Alternativen.', faqTitle: 'Mit Foto-Anprobe starten' },
    'compare-glasses-frames': { kind: 'compare', metaTitle: 'Brillenrahmen auf deinem Foto vergleichen | VisuTry', metaDescription: 'Vergleiche bis zu vier Brillen-Presets mit KI-Anprobe nebeneinander auf deinem Foto.', eyebrow: 'Brillenentscheidung im Direktvergleich', title: 'Brillenrahmen auf deinem Foto vergleichen', intro: 'Wenn eine einzelne Anprobe nicht reicht, vergleiche mehrere Brillenrichtungen gemeinsam in einer Ansicht.', faqTitle: 'Direktvergleich öffnen' },
  },
  ja: {
    'find-glasses-for-my-face': { kind: 'selection', metaTitle: '写真から自分の顔に合うメガネを探す | VisuTry', metaDescription: '写真1枚から顔の特徴を確認し、フレーム候補を絞って試着や比較で確認します。', eyebrow: '写真から始めるフレーム選び', title: '自分の顔に合うメガネを探す', intro: '写真1枚から顔の比率を確認し、試すフレームの方向を絞って最後に写真で確認します。', faqTitle: '候補から写真での確認へ' },
    'try-glasses-on-photo': { kind: 'tryOn', metaTitle: '写真でメガネをオンライン試着 | VisuTry', metaDescription: '顔写真とメガネの商品画像をアップロードして試着し、候補を並べて比較できます。', eyebrow: '写真ベースのメガネ試着', title: '自分の写真でメガネを試着', intro: '自分の写真とメガネ画像を使って1本の見た目を確認し、必要なら候補を並べて比較します。', faqTitle: '写真と1本のフレームから始める' },
    'ai-glasses-advisor': { kind: 'advisor', metaTitle: 'AIメガネアドバイザー：顔に合うフレーム提案 | VisuTry', metaDescription: '顔写真から実用的なフレーム提案を受け、バーチャル試着や比較で候補を確認します。', eyebrow: 'パーソナルなメガネ提案', title: 'AIメガネアドバイザー', intro: '写真から試す価値のあるフレーム方向を絞り、理由を理解してから試着や比較で確認します。', faqTitle: 'メガネアドバイザーを開く' },
    'what-glasses-suit-my-face': { kind: 'selection', metaTitle: '私に似合うメガネは？写真から候補を提案 | VisuTry', metaDescription: '無料の顔型診断で候補を絞り、バーチャル試着やフレーム比較で似合うか確認します。', eyebrow: '写真から始めるメガネ選び', title: '私に似合うメガネは？', intro: '写真1枚から顔型を推定し、フレーム候補を作って試着や比較で見た目を確認します。', faqTitle: '無料の写真チェックから始める' },
    'virtual-glasses-try-on': { kind: 'tryOn', metaTitle: '写真でメガネをバーチャル試着 | VisuTry', metaDescription: '顔写真と商品画像やスクリーンショットからメガネを試着し、候補を比較できます。', eyebrow: '自分の写真でバーチャル試着', title: 'メガネのバーチャル試着', intro: '購入前にメガネの見た目を確認。顔写真とフレーム画像をアップロードし、必要なら候補を比較します。', faqTitle: '写真試着から始める' },
    'compare-glasses-frames': { kind: 'compare', metaTitle: '写真でメガネフレームを並べて比較 | VisuTry', metaDescription: '最大4つのフレームをAI試着し、自分の写真で並べて比較できます。', eyebrow: '並べて決めるフレーム比較', title: '自分の写真でメガネフレームを比較', intro: '1本の試着だけでは決めにくいとき、複数のフレーム方向を並べて比較して判断します。', faqTitle: 'フレーム比較を開く' },
  },
  es: {
    'find-glasses-for-my-face': { kind: 'selection', metaTitle: 'Encontrar gafas para mi cara desde una foto | VisuTry', metaDescription: 'Encuentra gafas desde una foto, reduce direcciones de montura y valídalas con prueba virtual o comparación.', eyebrow: 'Selección de monturas desde una foto', title: 'Encontrar gafas para mi cara', intro: 'Convierte una foto en una lista práctica: entiende tus proporciones, reduce direcciones y valida visualmente los candidatos.', faqTitle: 'De la lista corta a la prueba visual' },
    'try-glasses-on-photo': { kind: 'tryOn', metaTitle: 'Probar gafas en una foto online | VisuTry', metaDescription: 'Sube una foto de tu cara y una imagen de gafas, previsualiza el resultado y compara alternativas lado a lado.', eyebrow: 'Prueba de gafas basada en foto', title: 'Probar gafas en tu foto', intro: 'Sube tu foto y una imagen de gafas para ver un par concreto y compara alternativas cuando necesites más seguridad.', faqTitle: 'Empieza con tu foto y una montura' },
    'ai-glasses-advisor': { kind: 'advisor', metaTitle: 'Asesor de gafas IA: monturas para tu cara | VisuTry', metaDescription: 'Convierte una foto facial en orientación práctica de monturas y valida la selección con prueba virtual.', eyebrow: 'Orientación personalizada de gafas', title: 'Asesor de gafas con IA', intro: 'Usa tu foto para reducir las direcciones de montura, entender por qué pueden funcionar y validarlas visualmente.', faqTitle: 'Abrir el asesor de gafas' },
    'what-glasses-suit-my-face': { kind: 'selection', metaTitle: '¿Qué gafas me quedan bien? Usa una foto | VisuTry', metaDescription: 'Usa el detector facial gratuito, reduce formas de montura y confirma con prueba virtual o comparación.', eyebrow: 'Consejo de gafas desde una foto', title: '¿Qué gafas me quedan bien?', intro: 'Sube una foto, estima tu forma facial, crea una lista de monturas y confirma el aspecto con prueba o comparación.', faqTitle: 'Empieza con una comprobación gratuita' },
    'virtual-glasses-try-on': { kind: 'tryOn', metaTitle: 'Prueba virtual de gafas desde tu foto | VisuTry', metaDescription: 'Prueba gafas virtualmente con una foto facial y una imagen de producto o captura, y compara monturas.', eyebrow: 'Prueba virtual desde tu foto', title: 'Prueba virtual de gafas online', intro: 'Mira cómo quedan las gafas antes de comprar. Sube tu foto y una imagen de la montura y compara alternativas.', faqTitle: 'Empieza con una prueba en foto' },
    'compare-glasses-frames': { kind: 'compare', metaTitle: 'Comparar monturas en tu foto lado a lado | VisuTry', metaDescription: 'Compara hasta cuatro monturas con resultados de prueba IA lado a lado en tu foto.', eyebrow: 'Decisiones de montura lado a lado', title: 'Comparar monturas en tu foto', intro: 'Cuando una prueba no basta, compara varias direcciones de montura juntas y decide con una vista más clara.', faqTitle: 'Abrir comparación lado a lado' },
  },
  pt: {
    'find-glasses-for-my-face': { kind: 'selection', metaTitle: 'Encontrar óculos para meu rosto por foto | VisuTry', metaDescription: 'Encontre óculos a partir de uma foto, reduza direções de armação e valide com prova virtual ou comparação.', eyebrow: 'Seleção de armações a partir da foto', title: 'Encontrar óculos para meu rosto', intro: 'Transforme uma foto em uma lista prática: entenda as proporções, reduza direções e valide os candidatos visualmente.', faqTitle: 'Da lista curta à prova visual' },
    'try-glasses-on-photo': { kind: 'tryOn', metaTitle: 'Provar óculos em uma foto online | VisuTry', metaDescription: 'Envie foto do rosto e imagem dos óculos, visualize o resultado e compare alternativas lado a lado.', eyebrow: 'Prova de óculos baseada em foto', title: 'Provar óculos na sua foto', intro: 'Envie sua foto e uma imagem dos óculos para ver um par específico e compare alternativas quando precisar de mais confiança.', faqTitle: 'Comece com sua foto e uma armação' },
    'ai-glasses-advisor': { kind: 'advisor', metaTitle: 'Consultor de óculos IA: armações para seu rosto | VisuTry', metaDescription: 'Transforme uma foto facial em orientação prática de armações e valide a seleção com prova virtual.', eyebrow: 'Orientação personalizada de óculos', title: 'Consultor de óculos com IA', intro: 'Use sua foto para reduzir direções de armação, entender por que podem funcionar e validar visualmente.', faqTitle: 'Abrir o consultor de óculos' },
    'what-glasses-suit-my-face': { kind: 'selection', metaTitle: 'Quais óculos combinam com meu rosto? | VisuTry', metaDescription: 'Use o detector facial grátis, reduza formatos de armação e confirme com prova virtual ou comparação.', eyebrow: 'Conselho de óculos a partir da foto', title: 'Quais óculos combinam com meu rosto?', intro: 'Envie uma foto, estime o formato do rosto, crie uma lista de armações e confirme o visual com prova ou comparação.', faqTitle: 'Comece com uma verificação gratuita' },
    'virtual-glasses-try-on': { kind: 'tryOn', metaTitle: 'Prova virtual de óculos com sua foto | VisuTry', metaDescription: 'Prove óculos virtualmente com foto do rosto e imagem de produto ou captura, depois compare armações.', eyebrow: 'Prova virtual com sua foto', title: 'Prova virtual de óculos online', intro: 'Veja como os óculos ficam antes da compra. Envie sua foto e a imagem da armação e compare alternativas.', faqTitle: 'Comece com uma prova por foto' },
    'compare-glasses-frames': { kind: 'compare', metaTitle: 'Comparar armações lado a lado na sua foto | VisuTry', metaDescription: 'Compare até quatro armações com resultados de prova IA lado a lado na sua foto.', eyebrow: 'Decisões de armação lado a lado', title: 'Comparar armações na sua foto', intro: 'Quando uma prova não basta, compare várias direções de armação juntas e decida em uma visão mais clara.', faqTitle: 'Abrir comparação lado a lado' },
  },
  fr: {
    'find-glasses-for-my-face': { kind: 'selection', metaTitle: 'Trouver des lunettes pour mon visage depuis une photo | VisuTry', metaDescription: 'Trouvez des lunettes depuis une photo, réduisez les directions de montures puis validez par essayage ou comparaison.', eyebrow: 'Sélection de montures à partir d’une photo', title: 'Trouver des lunettes pour mon visage', intro: 'Transformez une photo en sélection pratique : comprenez les proportions, réduisez les directions et validez visuellement les candidats.', faqTitle: 'De la sélection à la preuve visuelle' },
    'try-glasses-on-photo': { kind: 'tryOn', metaTitle: 'Essayer des lunettes sur une photo en ligne | VisuTry', metaDescription: 'Importez une photo de visage et une image de lunettes, prévisualisez le rendu puis comparez les alternatives.', eyebrow: 'Essayage de lunettes basé sur une photo', title: 'Essayer des lunettes sur votre photo', intro: 'Importez votre photo et une image de lunettes pour voir une paire précise puis comparez les alternatives si nécessaire.', faqTitle: 'Commencez avec votre photo et une monture' },
    'ai-glasses-advisor': { kind: 'advisor', metaTitle: 'Conseiller lunettes IA : montures pour votre visage | VisuTry', metaDescription: 'Transformez une photo de visage en conseils pratiques de montures et validez la sélection par essayage.', eyebrow: 'Conseils lunettes personnalisés', title: 'Conseiller lunettes IA', intro: 'Utilisez votre photo pour réduire les directions de montures, comprendre les recommandations et les valider visuellement.', faqTitle: 'Ouvrir le conseiller lunettes' },
    'what-glasses-suit-my-face': { kind: 'selection', metaTitle: 'Quelles lunettes me vont ? Utilisez une photo | VisuTry', metaDescription: 'Utilisez le détecteur gratuit, réduisez les formes de montures puis confirmez par essayage ou comparaison.', eyebrow: 'Conseils lunettes à partir d’une photo', title: 'Quelles lunettes me vont ?', intro: 'Importez une photo, estimez votre forme de visage, créez une courte sélection puis confirmez le rendu.', faqTitle: 'Commencez par une vérification photo gratuite' },
    'virtual-glasses-try-on': { kind: 'tryOn', metaTitle: 'Essayage virtuel de lunettes depuis votre photo | VisuTry', metaDescription: 'Essayez virtuellement des lunettes avec une photo et une image produit ou capture, puis comparez les montures.', eyebrow: 'Essayage virtuel depuis votre photo', title: 'Essayage virtuel de lunettes en ligne', intro: 'Voyez le rendu avant achat. Importez votre photo et une image de monture puis comparez les alternatives.', faqTitle: 'Commencez par un essayage photo' },
    'compare-glasses-frames': { kind: 'compare', metaTitle: 'Comparer des montures sur votre photo côte à côte | VisuTry', metaDescription: 'Comparez jusqu’à quatre montures avec des résultats d’essayage IA côte à côte sur votre photo.', eyebrow: 'Décision de montures côte à côte', title: 'Comparer des montures sur votre photo', intro: 'Quand un seul essayage ne suffit pas, comparez plusieurs directions ensemble dans une vue plus claire.', faqTitle: 'Ouvrir la comparaison côte à côte' },
  },
}

export function getSearchToToolPhaseACopy(locale: string, routeId: SearchToToolPhaseARouteId): SearchToToolPhaseACopy {
  const resolved = isValidLocale(locale) ? locale : defaultLocale
  const seed = routeSeeds[resolved][routeId]
  return { ...seed, ...kindCopies[resolved][seed.kind], kind: seed.kind }
}
