export type CombinationSearchPageType = 'face-frame' | 'gender-style' | 'decision-question'

export type CombinationSearchPage = {
  slug: string
  type: CombinationSearchPageType
  title: string
  metaDescription: string
  eyebrow: string
  intro: string
  queryCluster: string
  primaryAnswer: string
  whyItWorks: string
  watchFor: string
  decisionTip: string
  faq: readonly { question: string; answer: string }[]
  includeCtas: readonly ('detector' | 'try_on' | 'compare' | 'advisor')[]
  bottomCtas: readonly ('detector' | 'try_on' | 'compare' | 'advisor')[]
  ctaLabels?: {
    detector?: string
    tryOn?: string
    compare?: string
    advisor?: string
  }
  relatedOwnerPath?: string
}

const faceFrame = (
  slug: string,
  title: string,
  metaDescription: string,
  face: string,
  frame: string,
  primaryAnswer: string,
  whyItWorks: string,
  watchFor: string,
  decisionTip: string,
  relatedOwnerPath: string,
): CombinationSearchPage => ({
  slug,
  type: 'face-frame',
  title,
  metaDescription,
  eyebrow: `${frame} frames × ${face} face`,
  intro: primaryAnswer,
  queryCluster: `face-frame:${face.toLowerCase()}:${frame.toLowerCase()}`,
  primaryAnswer,
  whyItWorks,
  watchFor,
  decisionTip,
  relatedOwnerPath,
  includeCtas: ['detector', 'try_on', 'compare'],
  bottomCtas: ['try_on', 'compare'],
  ctaLabels: {
    detector: 'Check my face shape first',
    tryOn: `Try ${frame.toLowerCase()} glasses on my photo`,
    compare: 'Compare frame directions',
  },
  faq: [
    {
      question: `Do ${frame.toLowerCase()} glasses suit a ${face.toLowerCase()} face?`,
      answer: primaryAnswer,
    },
    {
      question: `What should I check before buying ${frame.toLowerCase()} glasses?`,
      answer: watchFor,
    },
    {
      question: 'Is face shape enough to choose a frame?',
      answer: 'No. Face shape is a useful first filter, but frame width, bridge fit, lens depth, prescription needs, and personal style should all be checked before purchase.',
    },
  ],
})

const genderStyle = (
  slug: string,
  title: string,
  metaDescription: string,
  face: string,
  audience: 'Women' | 'Men',
  primaryAnswer: string,
  whyItWorks: string,
  watchFor: string,
  decisionTip: string,
  relatedOwnerPath: string,
): CombinationSearchPage => ({
  slug,
  type: 'gender-style',
  title,
  metaDescription,
  eyebrow: `${face} face · ${audience.toLowerCase()}`,
  intro: primaryAnswer,
  queryCluster: `gender-style:${face.toLowerCase()}:${audience.toLowerCase()}`,
  primaryAnswer,
  whyItWorks,
  watchFor,
  decisionTip,
  relatedOwnerPath,
  includeCtas: ['detector', 'advisor', 'try_on'],
  bottomCtas: ['advisor', 'try_on'],
  ctaLabels: {
    detector: 'Check my face shape',
    advisor: 'Get personalized frame advice',
    tryOn: 'Try shortlisted frames on my photo',
  },
  faq: [
    {
      question: `What glasses usually suit ${audience.toLowerCase()} with a ${face.toLowerCase()} face?`,
      answer: primaryAnswer,
    },
    {
      question: 'Should gender decide the frame shape?',
      answer: 'No. These pages use common styling intent, not a rule. Proportion, fit, comfort, prescription, and the look you want matter more than gender labels.',
    },
    {
      question: 'How do I narrow the shortlist?',
      answer: decisionTip,
    },
  ],
})

const decisionQuestion = (
  slug: string,
  title: string,
  metaDescription: string,
  primaryAnswer: string,
  whyItWorks: string,
  watchFor: string,
  decisionTip: string,
  includeCtas: CombinationSearchPage['includeCtas'] = ['detector', 'try_on', 'compare'],
  bottomCtas: CombinationSearchPage['bottomCtas'] = ['try_on', 'compare'],
): CombinationSearchPage => ({
  slug,
  type: 'decision-question',
  title,
  metaDescription,
  eyebrow: 'Eyewear decision question',
  intro: primaryAnswer,
  queryCluster: `decision-question:${slug}`,
  primaryAnswer,
  whyItWorks,
  watchFor,
  decisionTip,
  includeCtas,
  bottomCtas,
  ctaLabels: {
    detector: 'Check my face shape',
    tryOn: 'Test the look on my photo',
    compare: 'Compare a few frames',
    advisor: 'Get personalized advice',
  },
  faq: [
    { question: title.replace(/\?$/, '' ) + '?', answer: primaryAnswer },
    { question: 'What is the fastest way to validate the choice?', answer: decisionTip },
    { question: 'What can virtual try-on not confirm?', answer: 'A visual preview cannot confirm physical comfort, exact bridge pressure, optical measurements, or prescription suitability. Confirm those with the seller or an optical professional.' },
  ],
})

export const COMBINATION_SEARCH_PAGES: readonly CombinationSearchPage[] = [
  // Face × frame: curated, high-intent combinations only.
  faceFrame(
    'best-rectangle-glasses-for-round-face',
    'Best Rectangle Glasses for a Round Face',
    'Rectangle glasses can add useful structure to a round face. See what proportions to look for, then try the direction on your own photo.',
    'Round', 'Rectangle',
    'Rectangle frames are a strong first direction for many round faces because their straight top line and visible corners contrast with softer facial curves.',
    'The contrast can make the frame feel more defined without requiring an oversized or very heavy look.',
    'Avoid frames that are much narrower than the cheeks or so shallow that they look undersized. Width and brow alignment matter as much as the rectangle shape itself.',
    'Try one medium-width rectangle and one slightly wider option side by side. Keep the one that looks proportional rather than simply the most angular.',
    '/style/round-face',
  ),
  faceFrame(
    'best-square-glasses-for-round-face',
    'Best Square Glasses for a Round Face',
    'Square glasses create stronger corners against a round face. Learn when the shape works best and compare it with softer alternatives.',
    'Round', 'Square',
    'Square frames can create a crisp, structured contrast on a round face, especially when the frame is wide enough to sit naturally across the cheek area.',
    'The visible corners add definition while a balanced lens depth keeps the frame from looking too severe.',
    'Very thick square frames can dominate smaller features. Also avoid a frame that ends inside the widest point of the cheeks.',
    'Compare a classic square with a rectangle. If the square feels too heavy, keep the angular idea but reduce lens depth or rim thickness.',
    '/style/round-face',
  ),
  faceFrame(
    'best-browline-glasses-for-round-face',
    'Best Browline Glasses for a Round Face',
    'Browline glasses can add upper-face definition to a round face. See what to check before choosing the look.',
    'Round', 'Browline',
    'Browline frames can work well on round faces because the stronger upper rim creates a horizontal anchor while the lower lens stays visually lighter.',
    'That upper emphasis can add structure without surrounding the whole face with a heavy geometric outline.',
    'Make sure the browline follows rather than fights your natural eyebrow angle, and avoid a frame that is too narrow across the temples.',
    'Try a browline next to a rectangle. Choose browline when you want structure concentrated at the top rather than around the entire lens.',
    '/style/round-face',
  ),
  faceFrame(
    'best-cat-eye-glasses-for-round-face',
    'Best Cat-Eye Glasses for a Round Face',
    'Cat-eye glasses can add lift and diagonal movement to a round face. Learn how much upsweep is useful before trying them on your photo.',
    'Round', 'Cat-Eye',
    'A controlled cat-eye can suit a round face because the outer upsweep introduces diagonal movement and definition above the cheek line.',
    'The lift can visually redirect attention upward instead of repeating the face’s softer circular outline.',
    'An extremely narrow or sharply exaggerated cat-eye may pinch the face visually. Check temple width and make sure the upsweep does not sit far above the brows.',
    'Compare a subtle cat-eye with a rectangle. The cat-eye is usually the better choice when you want lift and personality rather than purely geometric contrast.',
    '/style/round-face',
  ),
  faceFrame(
    'best-geometric-glasses-for-round-face',
    'Best Geometric Glasses for a Round Face',
    'Geometric glasses can add deliberate angles to a round face. See how to use the contrast without letting the frame overpower your features.',
    'Round', 'Geometric',
    'Geometric frames can be effective on a round face because multiple straight edges create contrast with a smooth jawline and fuller cheek contour.',
    'The shape feels distinctive while still following the same principle as rectangle or square frames: introduce visible structure.',
    'Too many sharp edges plus a very thick rim can become visually busy. Keep the overall frame width proportional to the face.',
    'Use geometric frames as the bolder comparison option beside a simpler rectangle. If both work, choose based on how expressive you want the eyewear to feel.',
    '/style/round-face',
  ),
  faceFrame(
    'best-cat-eye-glasses-for-oval-face',
    'Best Cat-Eye Glasses for an Oval Face',
    'Cat-eye glasses often work naturally with balanced oval proportions. See how to choose the right width and amount of lift.',
    'Oval', 'Cat-Eye',
    'Oval faces support many frame shapes, and cat-eye frames are useful when you want to emphasize the cheekbones and add a deliberate upward line.',
    'Because the face is already balanced, the cat-eye can be selected for expression rather than correction.',
    'Avoid an upsweep that extends far beyond the temple width or a lens that is so shallow it looks disconnected from the rest of the face.',
    'Compare a subtle cat-eye with a stronger one. The better option usually follows your brow and cheekbone scale without making the outer corner the only thing you notice.',
    '/style/oval-face',
  ),
  faceFrame(
    'best-aviator-glasses-for-oval-face',
    'Best Aviator Glasses for an Oval Face',
    'Aviator glasses can suit an oval face when lens depth and bridge width stay in proportion. Use this guide before testing the look on your photo.',
    'Oval', 'Aviator',
    'Aviators often suit oval faces because the softly tapered lens adds character while the overall proportions remain balanced.',
    'The shape can add vertical depth without forcing the face to look wider or more angular than it is.',
    'Large aviator lenses can cover too much cheek area, while a bridge that sits too low can make the frame look oversized even when the width is correct.',
    'Try one classic aviator and one shallower version. Keep the version whose lens depth complements your face length rather than simply choosing the larger frame.',
    '/style/oval-face',
  ),
  faceFrame(
    'best-browline-glasses-for-oval-face',
    'Best Browline Glasses for an Oval Face',
    'Browline glasses give an oval face more upper-frame definition. See what proportions keep the look balanced.',
    'Oval', 'Browline',
    'Browline frames work well with oval proportions when you want a stronger visual anchor around the brows without adding equal weight around the lower lens.',
    'The face’s natural balance leaves room for the heavier upper rim to become the main styling feature.',
    'Watch for a browline that sits too high or extends beyond the temples. The frame should echo the brow area rather than create a second unrelated line.',
    'Compare a browline against a classic rectangle. Choose browline when the upper-rim emphasis adds character without making the forehead feel crowded.',
    '/style/oval-face',
  ),
  faceFrame(
    'best-oversized-glasses-for-oval-face',
    'Best Oversized Glasses for an Oval Face',
    'Oversized glasses can work on an oval face, but scale matters more than the label. Learn how to keep a larger frame proportional.',
    'Oval', 'Oversized',
    'Oval faces can carry larger frames because their balanced proportions do not require one specific corrective shape.',
    'A larger lens can become a fashion statement while still preserving the face’s natural symmetry.',
    'Oversized should not mean wider than the temples by a large margin or low enough to rest visually on the cheeks. Bridge fit and eyebrow visibility remain important.',
    'Compare your preferred oversized frame with one medium-size option. If the large frame still leaves the face visible and centered, the scale is probably working.',
    '/style/oval-face',
  ),
  faceFrame(
    'best-round-glasses-for-square-face',
    'Best Round Glasses for a Square Face',
    'Round glasses can soften the strong angles of a square face. See when the contrast works and what width to avoid.',
    'Square', 'Round',
    'Round frames are a classic contrast for a square face because curved lenses soften the visual repetition of a broad forehead and defined jawline.',
    'The curve creates a different geometry instead of stacking another strong box shape on top of the face.',
    'Tiny round frames can look undersized against a wider jaw. Aim for enough width and lens depth to stay in scale with the face.',
    'Compare a true round frame with a soft oval. If the circle feels too stylized, the oval keeps the softening effect with less visual contrast.',
    '/style/square-face',
  ),
  faceFrame(
    'best-aviator-glasses-for-square-face',
    'Best Aviator Glasses for a Square Face',
    'Aviators can soften a square face while keeping a strong frame identity. Learn what bridge and lens depth to check.',
    'Square', 'Aviator',
    'Aviator lenses add curves and taper against a square jaw, giving you contrast without making the frame look delicate.',
    'The rounded lower lens can soften the face while the top bar preserves a confident horizontal line.',
    'Avoid an aviator that is too narrow or whose bottom edge ends directly on the widest jaw line. Very deep lenses can also dominate shorter square faces.',
    'Compare a classic aviator with a round frame. Pick the aviator when you want softness plus a stronger top line.',
    '/style/square-face',
  ),
  faceFrame(
    'best-rimless-glasses-for-square-face',
    'Best Rimless Glasses for a Square Face',
    'Rimless glasses can reduce visual weight on a square face. See why lens shape and size matter even when the frame is minimal.',
    'Square', 'Rimless',
    'Rimless glasses can work well on square faces because they avoid adding another heavy outline around an already structured jaw and forehead.',
    'A softer lens shape keeps the eyewear present without competing with strong facial angles.',
    'Minimal construction does not fix poor proportions. A lens that is too narrow, shallow, or small can still look out of scale.',
    'Compare rimless with a thin metal oval. Choose rimless when you want the least visual weight while keeping enough lens size to match the face.',
    '/style/square-face',
  ),
  faceFrame(
    'best-rounded-glasses-for-heart-shaped-face',
    'Best Rounded Glasses for a Heart-Shaped Face',
    'Rounded glasses can soften a heart-shaped face when the upper rim stays light and the lens adds presence lower down.',
    'Heart', 'Rounded',
    'Rounded frames can suit heart-shaped faces because soft lens curves avoid adding extra weight to a broader forehead while keeping visual presence through the lower half of the frame.',
    'That balance can connect the upper face to a narrower chin without relying on a very heavy brow line.',
    'Avoid frames with dense decoration at the top or a width that extends far past the forehead. Keep the bridge comfortable and centered.',
    'Compare a rounded frame with a subtle cat-eye. Rounded frames are usually calmer; cat-eye adds more lift and expression.',
    '/style/heart-face',
  ),
  faceFrame(
    'best-cat-eye-glasses-for-heart-shaped-face',
    'Best Cat-Eye Glasses for a Heart-Shaped Face',
    'A subtle cat-eye can echo the upper-face structure of a heart-shaped face without becoming too top-heavy.',
    'Heart', 'Cat-Eye',
    'A controlled cat-eye can work on heart-shaped faces when the frame keeps the brow area light and uses a gentle outer lift rather than a thick, heavy top rim.',
    'The lift can emphasize cheekbones while the lens still carries enough depth to balance a narrower chin.',
    'Avoid highly decorated or very wide outer corners that add more weight where the face is already widest.',
    'Try a subtle cat-eye beside a rounded frame. Choose the cat-eye if the lift flatters the cheekbones without making the forehead feel broader.',
    '/style/heart-face',
  ),
  faceFrame(
    'best-browline-glasses-for-diamond-face',
    'Best Browline Glasses for a Diamond Face',
    'Browline glasses can add presence near a narrower forehead on a diamond face. See how to avoid crowding prominent cheekbones.',
    'Diamond', 'Browline',
    'Browline frames can help a diamond face by adding controlled width and definition near the brow area while leaving the lower lens lighter around prominent cheekbones.',
    'The upper emphasis can visually connect narrower temples to the wider middle of the face.',
    'Avoid very narrow lenses or a thick lower rim that visually pinches the cheek area. Check that the top bar does not sit too high above the brows.',
    'Compare a browline with an oval frame. Browline works when you want more upper-face definition; oval is the softer alternative.',
    '/style/diamond-face',
  ),
  faceFrame(
    'best-oversized-glasses-for-long-face',
    'Best Oversized Glasses for a Long Face',
    'Oversized glasses can add useful lens depth to a long or oblong face. Learn how to add scale without making the frame too wide.',
    'Long', 'Oversized',
    'A deeper oversized frame can suit an oblong face because lens depth interrupts a long vertical line and adds visible scale across the middle of the face.',
    'The goal is usually depth and presence, not simply maximum width.',
    'Avoid very shallow oversized frames or frames extending far beyond the temples. A large frame should still stay centered and stable on the bridge.',
    'Compare a deep oversized rectangle with a medium browline. Choose the larger frame only if the added depth improves proportion rather than covering the face.',
    '/style/oblong-face',
  ),

  // Gender / styling intent. These are guidance pages, not gender rules.
  genderStyle(
    'glasses-for-round-face-women',
    'Glasses for a Round Face: Women’s Styling Guide',
    'A practical women’s styling guide for round faces, with frame directions to shortlist before using virtual try-on.',
    'Round', 'Women',
    'For a round face, start with frames that add some structure or lift: rectangles, squares, controlled cat-eyes, and light geometric shapes are strong directions to compare.',
    'These shapes create contrast with softer facial curves while still leaving room for personal style, color, and material choices.',
    'Do not choose only by label or trend. Frame width, brow alignment, bridge fit, and how much lens depth you like will change the result.',
    'Shortlist one structured frame, one lifted frame, and one softer alternative, then try all three on the same photo.',
    '/style/round-face',
  ),
  genderStyle(
    'glasses-for-round-face-men',
    'Glasses for a Round Face: Men’s Styling Guide',
    'A practical men’s styling guide for round faces, from rectangle and square frames to lighter geometric options.',
    'Round', 'Men',
    'For a round face, rectangle, square, browline, and restrained geometric frames are useful starting points because they introduce clearer edges and horizontal structure.',
    'The contrast can define the eyewear without requiring an aggressive or oversized frame.',
    'Avoid automatically choosing the thickest frame. A medium rim with the right width often looks more proportional than a very heavy box shape.',
    'Compare one classic rectangle with one browline and one softer option. Use the photo result to judge scale rather than relying on category names.',
    '/style/round-face',
  ),
  genderStyle(
    'glasses-for-oval-face-women',
    'Glasses for an Oval Face: Women’s Styling Guide',
    'Oval faces can support many frame shapes. Use this women’s styling guide to narrow the shortlist by scale and expression.',
    'Oval', 'Women',
    'Oval proportions are flexible, so the best shortlist often comes from deciding how expressive you want the eyewear to be: cat-eye, browline, rectangle, aviator, and balanced oversized frames can all work.',
    'Because there is less need to correct the face outline, color, material, brow alignment, and lens depth become more important decision variables.',
    'The main risk is scale. Very wide or very narrow frames can disturb otherwise balanced proportions.',
    'Choose three different moods rather than three nearly identical shapes, then compare them on one photo.',
    '/style/oval-face',
  ),
  genderStyle(
    'glasses-for-oval-face-men',
    'Glasses for an Oval Face: Men’s Styling Guide',
    'A practical men’s guide to glasses for oval faces, including rectangle, browline, aviator, and balanced square directions.',
    'Oval', 'Men',
    'Oval faces usually support rectangle, square, browline, aviator, and other balanced frame shapes, so style preference and fit can lead the decision.',
    'The face is already proportionally balanced, which gives you more freedom to choose between classic, minimal, or statement eyewear.',
    'Do not let the frame become much wider than the temples or so shallow that it looks undersized against the face length.',
    'Compare a classic structured frame, a lighter metal option, and one bolder choice. Keep the one that fits your features rather than the category stereotype.',
    '/style/oval-face',
  ),
  genderStyle(
    'glasses-for-square-face-women',
    'Glasses for a Square Face: Women’s Styling Guide',
    'Use curved or lighter frames to contrast a square face, or choose deliberate geometry when you want to emphasize strong structure.',
    'Square', 'Women',
    'Round, oval, thin metal, soft aviator, and lighter cat-eye frames are useful directions when you want contrast with a defined jaw and broad forehead.',
    'Curves and lighter construction can soften the overall look, while a deliberate geometric frame can instead emphasize structure if that is the style goal.',
    'Avoid assuming every square face needs a round frame. Width, lens size, and how much jaw emphasis you want should guide the choice.',
    'Try one curved frame, one aviator or thin metal frame, and one stronger geometric option before deciding.',
    '/style/square-face',
  ),
  genderStyle(
    'glasses-for-square-face-men',
    'Glasses for a Square Face: Men’s Styling Guide',
    'A practical men’s guide to frames for square faces, with softer alternatives and structured options to compare.',
    'Square', 'Men',
    'Round, oval, aviator, and lighter metal frames create contrast with a square face; a refined rectangle can also work when you intentionally want to reinforce the structure.',
    'The useful decision is whether you want the frame to soften the jaw or echo it—not whether one shape is universally correct.',
    'Heavy boxy frames that match the jaw exactly can feel visually dense. Check rim thickness and lens depth as well as shape.',
    'Compare one curved frame with one structured frame. The side-by-side result will show whether contrast or reinforcement suits your style better.',
    '/style/square-face',
  ),
  genderStyle(
    'glasses-for-heart-shaped-face-women',
    'Glasses for a Heart-Shaped Face: Women’s Styling Guide',
    'A women’s styling guide for heart-shaped faces, with lighter, rounded, and subtle cat-eye options to compare.',
    'Heart-Shaped', 'Women',
    'Lightweight rounded frames, subtle cat-eyes, and frames with less visual weight at the brow are useful starting points for a heart-shaped face.',
    'They can keep a broader upper face from becoming top-heavy while adding enough presence around the eyes and lower lens area.',
    'Very wide or heavily decorated brow lines can amplify forehead width. Keep the upper frame controlled and check temple alignment.',
    'Compare a rounded frame, a subtle cat-eye, and one light metal frame on the same photo.',
    '/style/heart-face',
  ),
  genderStyle(
    'glasses-for-diamond-face-women',
    'Glasses for a Diamond Face: Women’s Styling Guide',
    'A women’s styling guide for diamond faces, focusing on oval, cat-eye, rimless, and browline directions.',
    'Diamond', 'Women',
    'Oval, rimless, subtle cat-eye, and browline frames can work well on diamond faces because they add softness or controlled width around narrower temples.',
    'The goal is usually to connect the forehead and jaw to prominent cheekbones rather than add more width at the cheeks themselves.',
    'Very narrow frames can pinch visually at the cheekbones, while thick lower rims can make the middle face feel crowded.',
    'Try one soft oval, one lifted cat-eye, and one upper-emphasis browline to see which relationship with the cheekbones feels best.',
    '/style/diamond-face',
  ),

  // Decision questions: direct answers with immediate product validation.
  decisionQuestion(
    'do-round-glasses-suit-a-round-face',
    'Do Round Glasses Suit a Round Face?',
    'Round glasses can suit a round face, but they repeat rather than contrast the face shape. Learn when that is intentional and when another shape may work better.',
    'Yes, they can. Round-on-round is not automatically wrong; it creates a softer, more harmonious look. If you want more definition, a rectangle, square, or lifted cat-eye will usually create stronger contrast.',
    'Matching shapes create harmony, while contrasting shapes create definition. The right choice depends on the look you want rather than a rigid face-shape rule.',
    'Small round frames can exaggerate fullness or look undersized. Check frame width and avoid a lens that sits well inside the cheeks.',
    'Try a round frame and a rectangle side by side on the same photo. That instantly shows whether harmony or contrast feels better on your face.',
  ),
  decisionQuestion(
    'do-aviators-suit-an-oval-face',
    'Do Aviators Suit an Oval Face?',
    'Aviators often suit oval faces because the proportions are flexible. Lens depth, bridge position, and overall scale decide whether the frame works.',
    'Usually, yes. Oval faces can carry the tapered aviator shape well, especially when the lens depth is proportional to the face length and the frame does not extend far past the temples.',
    'The oval face already has balanced proportions, so aviators can be selected mainly for style and scale rather than correction.',
    'Very deep lenses or a low-sitting bridge can make an aviator look oversized. Check cheek clearance and brow alignment.',
    'Try one classic aviator and one shallower alternative on your photo, then compare which lens depth looks more natural.',
  ),
  decisionQuestion(
    'are-cat-eye-glasses-good-for-round-faces',
    'Are Cat-Eye Glasses Good for Round Faces?',
    'Cat-eye glasses can be a strong choice for round faces because the outer lift adds diagonal movement and definition.',
    'Yes, especially when the upsweep is controlled rather than extreme. The diagonal outer corner creates contrast with softer cheeks and a curved jawline.',
    'The shape redirects attention upward and adds structure without requiring a heavy rectangular frame.',
    'A very narrow cat-eye can pinch the face visually. Make sure the frame reaches the temple area and the outer corner does not sit far above the brows.',
    'Compare a subtle cat-eye with a rectangle. Choose based on whether you prefer lift and expression or cleaner geometric structure.',
  ),
  decisionQuestion(
    'should-glasses-cover-your-eyebrows',
    'Should Glasses Cover Your Eyebrows?',
    'Glasses do not have to leave every eyebrow fully visible, but the upper rim should usually relate naturally to your brow line instead of cutting across it awkwardly.',
    'A frame often looks balanced when its top line follows or sits near the natural eyebrow shape. Some oversized and fashion frames intentionally overlap more.',
    'Brow alignment affects how centered and intentional the frame looks, but it is not a strict fitting rule for every design.',
    'If the frame hides the brows completely and also sits low on the cheeks, it may simply be too large or positioned poorly. Fit and bridge height matter.',
    'Use a straight-on photo and compare two frame heights. Pick the one whose upper rim works with your brow rather than judging eyebrow visibility alone.',
    ['try_on', 'compare', 'advisor'], ['try_on', 'compare'],
  ),
  decisionQuestion(
    'how-wide-should-glasses-be-for-my-face',
    'How Wide Should Glasses Be for My Face?',
    'A good starting point is a frame whose overall width is close to your face width at the temples, without obvious squeezing or large overhang.',
    'Proportional width keeps the eyes reasonably centered in the lenses and prevents the frame from looking pinched or oversized.',
    'Style can intentionally go wider, but large overhang, visible temple flare, or a frame much narrower than the cheeks are warning signs.',
    'Compare a medium and a wider frame on the same photo, then confirm the actual millimeter measurements and temple fit with the seller before buying.',
    ['detector', 'try_on', 'compare'], ['try_on', 'compare'],
  ),
  decisionQuestion(
    'how-should-glasses-fit-your-face',
    'How Should Glasses Fit Your Face?',
    'Glasses should look centered, sit securely at the bridge, avoid obvious temple flare, and keep the lens scale proportional to your features.',
    'Visual balance comes from several relationships at once: overall width, bridge position, eyebrow line, lens depth, cheek clearance, and where the pupils sit within the lenses.',
    'A photo preview cannot confirm physical comfort, slipping, pressure behind the ears, or prescription measurements. Those require real dimensions and fitting.',
    'Use virtual try-on for visual proportion, then confirm frame measurements and physical fit before purchase.',
    ['advisor', 'try_on', 'compare'], ['try_on', 'advisor'],
  ),
] as const

export const COMBINATION_SEARCH_PAGE_SLUGS = COMBINATION_SEARCH_PAGES.map((page) => page.slug)

export function getCombinationSearchPage(slug: string): CombinationSearchPage | undefined {
  return COMBINATION_SEARCH_PAGES.find((page) => page.slug === slug)
}
