import type { GlassesPreset } from '@/config/glasses-presets'

export const STYLE_EXPLORER_GLASSES_PRESETS: GlassesPreset[] = [
  {
    id: 'sun-wayfarer-black',
    name: 'Classic Black Wayfarer',
    style: 'Wayfarer Sunglasses',
    assetPath: 'assets/glasses-presets/style-explorer/sun-wayfarer-black.jpg',
    promptHint: 'classic glossy black wayfarer sunglasses with dark gray lenses and subtle silver rivets',
    category: 'sunglasses',
    shape: 'wayfarer',
    rimType: 'full-rim',
    material: 'acetate',
    colorFamily: 'black',
    visualWeight: 4,
    styleTags: ['classic', 'professional', 'vacation'],
    occasionTags: ['everyday', 'weekend', 'outdoor'],
    suitableFaceShapes: ['oval', 'round', 'heart', 'oblong'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'sun-aviator-gold',
    name: 'Gold Aviator',
    style: 'Aviator Sunglasses',
    assetPath: 'assets/glasses-presets/style-explorer/sun-aviator-gold.jpg',
    promptHint: 'thin gold metal aviator sunglasses with a double bridge and dark olive green teardrop lenses',
    category: 'sunglasses',
    shape: 'aviator',
    rimType: 'full-rim',
    material: 'metal',
    colorFamily: 'gold',
    visualWeight: 3,
    styleTags: ['classic', 'bold', 'vacation'],
    occasionTags: ['weekend', 'outdoor'],
    suitableFaceShapes: ['oval', 'square', 'heart', 'oblong'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'sun-cat-eye-black',
    name: 'Black Cat-Eye',
    style: 'Cat-Eye Sunglasses',
    assetPath: 'assets/glasses-presets/style-explorer/sun-cat-eye-black.jpg',
    promptHint: 'glossy black acetate cat-eye sunglasses with elegant upswept corners and dark gradient lenses',
    category: 'sunglasses',
    shape: 'cat-eye',
    rimType: 'full-rim',
    material: 'acetate',
    colorFamily: 'black',
    visualWeight: 4,
    styleTags: ['bold', 'creative', 'vacation'],
    occasionTags: ['weekend', 'outdoor'],
    suitableFaceShapes: ['oval', 'round', 'heart', 'diamond'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'sun-oversized-gradient',
    name: 'Oversized Gradient',
    style: 'Oversized Sunglasses',
    assetPath: 'assets/glasses-presets/style-explorer/sun-oversized-gradient.jpg',
    promptHint: 'oversized tortoise acetate sunglasses with large softly square lenses and warm brown gradient tint',
    category: 'sunglasses',
    shape: 'oversized-square',
    rimType: 'full-rim',
    material: 'acetate',
    colorFamily: 'tortoise',
    visualWeight: 5,
    styleTags: ['bold', 'classic', 'vacation'],
    occasionTags: ['weekend', 'outdoor'],
    suitableFaceShapes: ['oval', 'oblong', 'heart', 'diamond'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'sun-narrow-rectangle-black',
    name: 'Narrow Rectangle',
    style: 'Narrow Rectangle Sunglasses',
    assetPath: 'assets/glasses-presets/style-explorer/sun-narrow-rectangle-black.jpg',
    promptHint: 'slim glossy black narrow rectangular sunglasses with shallow dark lenses and a clean minimal silhouette',
    category: 'sunglasses',
    shape: 'narrow-rectangle',
    rimType: 'full-rim',
    material: 'acetate',
    colorFamily: 'black',
    visualWeight: 4,
    styleTags: ['creative', 'bold', 'minimal'],
    occasionTags: ['weekend', 'outdoor'],
    suitableFaceShapes: ['oval', 'round', 'heart', 'oblong'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'sun-round-tortoise',
    name: 'Tortoise Round',
    style: 'Round Sunglasses',
    assetPath: 'assets/glasses-presets/style-explorer/sun-round-tortoise.jpg',
    promptHint: 'warm tortoise acetate round sunglasses with brown lenses and a relaxed vintage character',
    category: 'sunglasses',
    shape: 'round',
    rimType: 'full-rim',
    material: 'acetate',
    colorFamily: 'tortoise',
    visualWeight: 3,
    styleTags: ['classic', 'creative', 'vacation'],
    occasionTags: ['everyday', 'weekend', 'outdoor'],
    suitableFaceShapes: ['oval', 'square', 'diamond', 'oblong'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'optical-transparent-geometric',
    name: 'Transparent Geometric',
    style: 'Transparent Geometric Optical',
    assetPath: 'assets/glasses-presets/style-explorer/optical-transparent-geometric.jpg',
    promptHint: 'transparent clear acetate geometric optical glasses with softly faceted lenses and a modern lightweight appearance',
    category: 'optical',
    shape: 'geometric',
    rimType: 'full-rim',
    material: 'acetate',
    colorFamily: 'transparent',
    visualWeight: 2,
    styleTags: ['creative', 'minimal'],
    occasionTags: ['everyday', 'weekend'],
    suitableFaceShapes: ['oval', 'round', 'heart'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'optical-statement-color',
    name: 'Statement Color',
    style: 'Statement Color Optical',
    assetPath: 'assets/glasses-presets/style-explorer/optical-statement-color.jpg',
    promptHint: 'deep burgundy acetate statement optical glasses with a bold softly square silhouette and clear lenses',
    category: 'optical',
    shape: 'square',
    rimType: 'full-rim',
    material: 'acetate',
    colorFamily: 'burgundy',
    visualWeight: 5,
    styleTags: ['bold', 'creative'],
    occasionTags: ['weekend', 'everyday'],
    suitableFaceShapes: ['oval', 'round', 'oblong'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'optical-warm-tortoise',
    name: 'Warm Tortoise Acetate',
    style: 'Warm Tortoise Optical',
    assetPath: 'assets/glasses-presets/style-explorer/optical-warm-tortoise.jpg',
    promptHint: 'warm tortoise acetate optical glasses with a softly square wayfarer-inspired shape and clear lenses',
    category: 'optical',
    shape: 'wayfarer',
    rimType: 'full-rim',
    material: 'acetate',
    colorFamily: 'tortoise',
    visualWeight: 3,
    styleTags: ['classic', 'professional'],
    occasionTags: ['everyday', 'work'],
    suitableFaceShapes: ['oval', 'round', 'heart', 'oblong'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'optical-thin-gold-oval',
    name: 'Thin Gold Metal Oval',
    style: 'Thin Gold Oval Optical',
    assetPath: 'assets/glasses-presets/style-explorer/optical-thin-gold-oval.jpg',
    promptHint: 'thin gold metal oval optical glasses with clear lenses, delicate bridge and transparent nose pads',
    category: 'optical',
    shape: 'oval',
    rimType: 'full-rim',
    material: 'metal',
    colorFamily: 'gold',
    visualWeight: 1,
    styleTags: ['minimal', 'professional', 'classic'],
    occasionTags: ['work', 'everyday'],
    suitableFaceShapes: ['square', 'heart', 'diamond', 'oblong'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'optical-clear-soft-square',
    name: 'Clear Soft Square',
    style: 'Clear Soft Square Optical',
    assetPath: 'assets/glasses-presets/style-explorer/optical-clear-soft-square.jpg',
    promptHint: 'clear transparent acetate optical glasses with a soft square shape, subtle rounded corners and clear lenses',
    category: 'optical',
    shape: 'square',
    rimType: 'full-rim',
    material: 'acetate',
    colorFamily: 'transparent',
    visualWeight: 2,
    styleTags: ['minimal', 'creative', 'professional'],
    occasionTags: ['everyday', 'work'],
    suitableFaceShapes: ['oval', 'round', 'heart'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'optical-slim-browline',
    name: 'Slim Browline',
    style: 'Slim Browline Optical',
    assetPath: 'assets/glasses-presets/style-explorer/optical-slim-browline.jpg',
    promptHint: 'slim black and gold mixed-material browline optical glasses with a light upper accent and thin metal lower rim',
    category: 'optical',
    shape: 'browline',
    rimType: 'semi-rimless',
    material: 'mixed',
    colorFamily: 'black',
    visualWeight: 3,
    styleTags: ['professional', 'classic', 'minimal'],
    occasionTags: ['work', 'everyday'],
    suitableFaceShapes: ['oval', 'round', 'heart', 'oblong'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'sun-shield-wraparound-black',
    name: 'Black Shield Wraparound',
    style: 'Shield Wraparound Sunglasses',
    assetPath: 'assets/glasses-presets/style-explorer/sun-shield-wraparound-black.jpg',
    promptHint: 'fashion-oriented black shield wraparound sunglasses with a single dark smoke lens, sculpted brow line and streamlined sport silhouette',
    category: 'sunglasses',
    shape: 'shield',
    rimType: 'shield',
    material: 'sport-polymer',
    colorFamily: 'black',
    visualWeight: 5,
    styleTags: ['bold', 'creative', 'vacation'],
    occasionTags: ['outdoor', 'weekend'],
    suitableFaceShapes: ['oval', 'round', 'oblong'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'sun-curved-flat-top-black',
    name: 'Curved Flat-Top Black',
    style: 'Curved Flat-Top Sunglasses',
    assetPath: 'assets/glasses-presets/style-explorer/sun-curved-flat-top-black.jpg',
    promptHint: 'architectural black acetate sunglasses with a strong curved flat top, wide rectangular lenses and dark smoke tint',
    category: 'sunglasses',
    shape: 'flat-top',
    rimType: 'full-rim',
    material: 'acetate',
    colorFamily: 'black',
    visualWeight: 5,
    styleTags: ['bold', 'minimal', 'creative'],
    occasionTags: ['weekend', 'outdoor'],
    suitableFaceShapes: ['oval', 'round', 'oblong'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'optical-rimless-geometric',
    name: 'Rimless Geometric',
    style: 'Rimless Geometric Optical',
    assetPath: 'assets/glasses-presets/style-explorer/optical-rimless-geometric.jpg',
    promptHint: 'true rimless geometric optical glasses with clear softly hexagonal lenses, a thin silver bridge and minimal transparent nose pads',
    category: 'optical',
    shape: 'rimless-geometric',
    rimType: 'rimless',
    material: 'rimless',
    colorFamily: 'silver',
    visualWeight: 1,
    styleTags: ['minimal', 'professional', 'creative'],
    occasionTags: ['work', 'everyday'],
    suitableFaceShapes: ['oval', 'round', 'heart', 'square'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
  {
    id: 'optical-slim-black-oval',
    name: 'Slim Black Oval',
    style: 'Slim Black Oval Optical',
    assetPath: 'assets/glasses-presets/style-explorer/optical-slim-black-oval.jpg',
    promptHint: 'slim glossy black oval optical glasses with low-profile lenses, fine acetate rims and a clean 1990s minimal character',
    category: 'optical',
    shape: 'oval',
    rimType: 'full-rim',
    material: 'acetate',
    colorFamily: 'black',
    visualWeight: 2,
    styleTags: ['minimal', 'classic', 'professional'],
    occasionTags: ['work', 'everyday'],
    suitableFaceShapes: ['square', 'heart', 'diamond', 'oblong'],
    isStyleExplorerEnabled: true,
    collection: 'style-explorer',
  },
]

export const STYLE_EXPLORER_SUNGLASSES_IDS = STYLE_EXPLORER_GLASSES_PRESETS
  .filter((preset) => preset.category === 'sunglasses')
  .map((preset) => preset.id)

export const STYLE_EXPLORER_OPTICAL_IDS = STYLE_EXPLORER_GLASSES_PRESETS
  .filter((preset) => preset.category === 'optical')
  .map((preset) => preset.id)
