export type VisualSeoAssetId = `VSEO-${string}`
export type VisualSeoAssetBatch = 'B01' | 'B02' | 'B03' | 'B04' | 'B05' | 'B06'
export type VisualSeoAssetStage = 'hero' | 'compare' | 'fit' | 'characteristics' | 'identify'

export type VisualSeoAsset = {
  id: VisualSeoAssetId
  batch: VisualSeoAssetBatch
  sourcePath: string
  publicPath: string
  pagePath: string
  width: number
  height: number
  heading: string
  alt: string
  body: string
  displayWidth?: 'primary' | 'secondary' | 'compare'
  bodyPosition?: 'before' | 'after'
  stage?: VisualSeoAssetStage
  priority?: boolean
  link?: {
    href: string
    label: string
  }
}

/**
 * B01 is the first accepted visual SEO unit. Keep the page copy here so the
 * rendered figure, image sitemap, and asset QA all use the same mapping.
 */
export const B01_VISUAL_SEO_ASSETS = [
  {
    id: 'VSEO-001',
    batch: 'B01',
    sourcePath: 'assets/visual-seo/B01/source/VSEO-001__ai-face-shape-detector-example.png',
    publicPath: '/images/seo/core/ai-face-shape-detector-example.webp',
    pagePath: '/face-shape-detector',
    width: 1448,
    height: 1086,
    heading: 'What the AI Face Shape Detector Measures',
    alt: 'AI face shape detector measuring forehead width, cheekbone width, jaw width, and face length',
    body: 'The detector compares four visible proportions: forehead width, cheekbone width, jaw width, and overall face length. Together, these measurements provide a practical estimate of your likely face shape from one clear photo.',
  },
  {
    id: 'VSEO-002',
    batch: 'B01',
    sourcePath: 'assets/visual-seo/B01/source/VSEO-002__common-face-shapes-guide.png',
    publicPath: '/images/seo/core/common-face-shapes-guide.webp',
    pagePath: '/face-shape-detector',
    width: 1448,
    height: 1086,
    heading: 'Common Face Shapes',
    alt: 'Guide comparing round, oval, square, heart, diamond, and oblong face shapes',
    body: 'Common face shapes include round, oval, square, heart, diamond, and oblong. The boundaries are visual guidelines rather than fixed labels, so comparing the full set of proportions is more useful than relying on one feature alone.',
    link: {
      href: '/en/what-is-my-face-shape',
      label: 'Learn how to identify your face shape',
    },
  },
  {
    id: 'VSEO-003',
    batch: 'B01',
    sourcePath: 'assets/visual-seo/B01/source/VSEO-003__face-shape-photo-analysis-result.png',
    publicPath: '/images/seo/core/face-shape-photo-analysis-result.webp',
    pagePath: '/face-shape-detector',
    width: 1448,
    height: 1086,
    heading: 'What a Face Shape Analysis Result Shows',
    alt: 'Example face shape photo analysis result with facial proportions and a likely face shape',
    body: 'A useful result connects the estimated shape to the measurements behind it. Use the result as a starting point for glasses discovery, then validate frame width, lens depth, bridge position, and overall visual balance.',
    link: {
      href: '/en/what-is-my-face-shape',
      label: 'See how to use your face shape result',
    },
  },
  {
    id: 'VSEO-004',
    batch: 'B01',
    sourcePath: 'assets/visual-seo/B01/source/VSEO-004__how-to-identify-your-face-shape.png',
    publicPath: '/images/seo/face-shapes/how-to-identify-your-face-shape.webp',
    pagePath: '/what-is-my-face-shape',
    width: 1448,
    height: 1086,
    heading: 'How to Identify Your Face Shape',
    alt: 'How to identify your face shape by comparing forehead width, cheekbone width, jaw width, and face length',
    body: 'Compare four proportions: forehead width, cheekbone width, jaw width, and overall face length. The relationship between these measurements helps distinguish common face shapes such as oval, round, square, heart, diamond, and oblong.',
    link: {
      href: '/en/face-shape-detector',
      label: 'Try the free face shape detector',
    },
  },
  {
    id: 'VSEO-005',
    batch: 'B01',
    sourcePath: 'assets/visual-seo/B01/source/VSEO-005__face-shape-comparison-guide.png',
    publicPath: '/images/seo/face-shapes/face-shape-comparison-guide.webp',
    pagePath: '/what-is-my-face-shape',
    width: 1536,
    height: 1024,
    heading: 'Face Shape Comparison Guide',
    alt: 'Face shape comparison guide showing round, oval, square, heart, diamond, and oblong proportions',
    body: 'Compare the six common face-shape patterns side by side: soft curves, balanced length, a defined jaw, a wider forehead, wider cheekbones, or longer proportions. Real faces can sit between categories, so use the comparison as a directional guide.',
  },
  {
    id: 'VSEO-006',
    batch: 'B01',
    sourcePath: 'assets/visual-seo/B01/source/VSEO-006__what-is-my-face-shape-result.png',
    publicPath: '/images/seo/face-shapes/what-is-my-face-shape-result.webp',
    pagePath: '/what-is-my-face-shape',
    width: 1448,
    height: 1086,
    heading: 'What Is My Face Shape? From Result to Next Step',
    alt: 'Example of a face shape result turning photo proportions into practical glasses guidance',
    body: 'Your face-shape result is most useful when it leads to a decision. Start with the likely shape, then explore frame directions and confirm the visual result on your own photo before choosing a pair.',
    link: {
      href: '/en/face-shape-detector',
      label: 'Find your face shape from a photo',
    },
  },
  {
    id: 'VSEO-007',
    batch: 'B01',
    sourcePath: 'assets/visual-seo/B01/source/VSEO-007__what-glasses-suit-my-face-guide.png',
    publicPath: '/images/seo/style/what-glasses-suit-my-face-guide.webp',
    pagePath: '/what-glasses-suit-my-face',
    width: 1448,
    height: 1086,
    heading: 'What Glasses Suit an Oval Face?',
    alt: 'Glasses guide for an oval face showing cat-eye, aviator, and soft rectangle frame directions',
    body: 'For an oval face, start with frame directions that respect balanced proportions: an upswept cat-eye, a classic aviator, or a softly defined rectangle can each create a different visual effect. Treat these as directions to test, not universal rules.',
    link: {
      href: '/en/ai-glasses-advisor',
      label: 'Get personalized glasses advice',
    },
  },
  {
    id: 'VSEO-008',
    batch: 'B01',
    sourcePath: 'assets/visual-seo/B01/source/VSEO-008__compare-glasses-for-your-face.png',
    publicPath: '/images/seo/style/compare-glasses-for-your-face.webp',
    pagePath: '/what-glasses-suit-my-face',
    width: 1448,
    height: 1086,
    heading: 'Compare Glasses for Your Face',
    alt: 'Guide comparing different glasses frame directions on a face to show how shape changes the look',
    body: 'The same face can look different with each frame direction. Compare shape, width, lens depth, and bridge placement on your photo so the final choice reflects both face proportions and the look you want.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare frames on my photo',
    },
  },
] as const satisfies readonly VisualSeoAsset[]

export const B02_VISUAL_SEO_ASSETS = [
  {
    id: 'VSEO-009',
    batch: 'B02',
    sourcePath: 'assets/visual-seo/B02/source/VSEO-009__find-glasses-for-your-face-workflow.png',
    publicPath: '/images/seo/core/find-glasses-for-your-face-workflow.webp',
    pagePath: '/what-glasses-suit-my-face',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    heading: 'How to Find Glasses for Your Face',
    alt: 'Find glasses for your face workflow from face shape detection to frame directions, try-on, and comparison',
    body: 'A useful glasses search moves from understanding your facial proportions to a small set of frame directions, then to visual validation. The goal is a confident shortlist, not a single rule that claims to decide for you.',
    link: {
      href: '/en/find-glasses-for-my-face',
      label: 'Find glasses for my face from a photo',
    },
  },
  {
    id: 'VSEO-010',
    batch: 'B02',
    sourcePath: 'assets/visual-seo/B02/source/VSEO-010__find-glasses-for-my-face.png',
    publicPath: '/images/seo/core/find-glasses-for-my-face.webp',
    pagePath: '/find-glasses-for-my-face',
    width: 1448,
    height: 1086,
    displayWidth: 'primary',
    bodyPosition: 'before',
    heading: 'Find Glasses for My Face',
    alt: 'Find glasses for a face by exploring everyday, lift, and structure frame directions',
    body: 'Once you understand the proportions of your face, explore a few visual directions instead of browsing every frame at once. Everyday, lift, and structure are starting points to test against your own features and preferences.',
    link: {
      href: '/en/ai-glasses-advisor',
      label: 'Open the AI Glasses Advisor',
    },
  },
  {
    id: 'VSEO-011',
    batch: 'B02',
    sourcePath: 'assets/visual-seo/B02/source/VSEO-011__glasses-frame-shapes-comparison.png',
    publicPath: '/images/seo/decisions/glasses-frame-shapes-comparison.webp',
    pagePath: '/find-glasses-for-my-face',
    width: 1448,
    height: 1086,
    displayWidth: 'compare',
    bodyPosition: 'before',
    heading: 'Compare Glasses Frame Shapes',
    alt: 'Same face comparing rectangle, round, cat-eye, and aviator glasses frame shapes',
    body: 'A side-by-side view makes frame shape differences easier to judge: rectangle adds a more defined outline, round softens the direction, cat-eye lifts the outer line, and aviator changes the overall balance. The right choice still depends on the look you want.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare frames on your photo',
    },
  },
  {
    id: 'VSEO-012',
    batch: 'B02',
    sourcePath: 'assets/visual-seo/B02/source/VSEO-012__try-glasses-before-choosing.png',
    publicPath: '/images/seo/decisions/try-glasses-before-choosing.webp',
    pagePath: '/find-glasses-for-my-face',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    heading: 'Try Glasses Before Choosing',
    alt: 'Shortlist glasses frame directions, try them on a face photo, and compare the visual results',
    body: 'Shortlisting reduces the search, virtual try-on shows how a chosen direction changes your photo, and comparison helps when two or more options remain close. Each step answers a different part of the decision.',
    link: {
      href: '/en/virtual-glasses-try-on',
      label: 'Try glasses on your photo',
    },
  },
  {
    id: 'VSEO-013',
    batch: 'B02',
    sourcePath: 'assets/visual-seo/B02/source/VSEO-013__virtual-glasses-try-on-before-after.png',
    publicPath: '/images/seo/core/virtual-glasses-try-on-before-after.webp',
    pagePath: '/virtual-glasses-try-on',
    width: 1448,
    height: 1086,
    displayWidth: 'primary',
    bodyPosition: 'before',
    heading: 'See What Virtual Try-On Changes',
    alt: 'Before and after showing a face photo with and without glasses in a virtual try-on preview',
    body: 'Virtual try-on places a chosen frame on your own photo so you can judge the overall visual effect before deciding whether it is worth considering further. It is visual evidence, not a promise of physical fit.',
    link: {
      href: '/en/try-glasses-on-photo',
      label: 'Try a frame on your photo',
    },
  },
  {
    id: 'VSEO-014',
    batch: 'B02',
    sourcePath: 'assets/visual-seo/B02/source/VSEO-014__virtual-try-on-different-glasses.png',
    publicPath: '/images/seo/decisions/virtual-try-on-different-glasses.webp',
    pagePath: '/virtual-glasses-try-on',
    width: 1448,
    height: 1086,
    displayWidth: 'compare',
    bodyPosition: 'before',
    heading: 'Compare Different Frame Styles',
    alt: 'Virtual try-on comparison of rectangle, cat-eye, and aviator glasses on the same face',
    body: 'Trying several frame directions on the same face makes the differences concrete. Compare outline, visual width, and the character of each style instead of relying on a product image viewed in isolation.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare different frame styles',
    },
  },
  {
    id: 'VSEO-015',
    batch: 'B02',
    sourcePath: 'assets/visual-seo/B02/source/VSEO-015__how-virtual-glasses-try-on-works.png',
    publicPath: '/images/seo/guides/how-virtual-glasses-try-on-works.webp',
    pagePath: '/virtual-glasses-try-on',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    heading: 'How Virtual Glasses Try-On Works',
    alt: 'Virtual glasses try-on workflow connecting a face photo, a selected frame, and a rendered result',
    body: 'Virtual try-on connects your face photo with a selected frame image and returns a rendered preview. The preview helps you assess appearance and proportion before moving to a closer product or fit check.',
    link: {
      href: '/en/virtual-glasses-try-on',
      label: 'Open virtual glasses try-on',
    },
  },
  {
    id: 'VSEO-016',
    batch: 'B02',
    sourcePath: 'assets/visual-seo/B02/source/VSEO-016__try-glasses-on-your-photo.png',
    publicPath: '/images/seo/core/try-glasses-on-your-photo.webp',
    pagePath: '/try-glasses-on-photo',
    width: 1448,
    height: 1086,
    displayWidth: 'primary',
    bodyPosition: 'before',
    heading: 'Try Glasses on Your Photo',
    alt: 'Original face photo transformed into a glasses try-on result',
    body: 'Start with the photo you already know, add a frame image, and inspect the resulting look in the same visual context. This makes a specific pair easier to evaluate before comparing alternatives.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare the result with other frames',
    },
  },
] as const satisfies readonly VisualSeoAsset[]

export const B03_VISUAL_SEO_ASSETS = [
  {
    id: 'VSEO-017',
    batch: 'B03',
    sourcePath: 'assets/visual-seo/B03/source/VSEO-017__photo-four-glasses-frames.png',
    publicPath: '/images/seo/core/photo-four-glasses-frames.webp',
    pagePath: '/try-glasses-on-photo',
    width: 1448,
    height: 1086,
    displayWidth: 'compare',
    bodyPosition: 'before',
    heading: 'See Four Frames on the Same Photo',
    alt: 'Same woman comparing four different eyeglass frames on the same photo',
    body: 'Keeping the photo, crop, pose, and lighting constant makes frame differences easier to judge. Compare several shapes on the same face so changes in outline and visual balance come from the eyewear rather than from a different photo.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare frames side by side',
    },
  },
  {
    id: 'VSEO-018',
    batch: 'B03',
    sourcePath: 'assets/visual-seo/B03/source/VSEO-018__glasses-photo-try-on-comparison.png',
    publicPath: '/images/seo/core/glasses-photo-try-on-comparison.webp',
    pagePath: '/try-glasses-on-photo',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    heading: 'Compare Lift and Structure on One Photo',
    alt: 'Same woman comparing an upward lifting eyeglass frame with a more structured frame on one photo',
    body: 'Two realistic frames can create different impressions even when everything else stays fixed. An upswept outline can add visual lift, while a more defined frame can add structure, making the comparison easier to evaluate on your own face.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare two shortlisted frames',
    },
  },
  {
    id: 'VSEO-019',
    batch: 'B03',
    sourcePath: 'assets/visual-seo/B03/source/VSEO-019__compare-four-glasses-frames.png',
    publicPath: '/images/seo/core/compare-four-glasses-frames.webp',
    pagePath: '/compare-glasses-frames',
    width: 1448,
    height: 1086,
    displayWidth: 'primary',
    bodyPosition: 'before',
    heading: 'Compare Four Common Frame Styles',
    alt: 'Same woman comparing rectangle, cat-eye, browline, and clear-lens aviator eyeglass frames',
    body: 'Comparing common frame families on one consistent face makes their visual differences easy to see. Rectangle, cat-eye, browline, and clear-lens aviator frames each change the outline and emphasis without changing the person underneath.',
    link: {
      href: '/en/try-glasses-on-photo',
      label: 'Try different frames on your photo',
    },
  },
  {
    id: 'VSEO-020',
    batch: 'B03',
    sourcePath: 'assets/visual-seo/B03/source/VSEO-020__glasses-frame-a-vs-b.png',
    publicPath: '/images/seo/core/glasses-frame-a-vs-b.webp',
    pagePath: '/compare-glasses-frames',
    width: 1448,
    height: 1086,
    displayWidth: 'compare',
    bodyPosition: 'before',
    heading: 'Compare Two Shortlisted Frames',
    alt: 'Same woman comparing two shortlisted eyeglass frames with defined and soft visual effects',
    body: 'A close A/B comparison helps when two frames both seem plausible. Look at how each option changes definition, softness, brow emphasis, and overall proportion instead of forcing an artificial winner before you have enough visual evidence.',
    link: {
      href: '/en/try-glasses-on-photo',
      label: 'Try a shortlisted frame on your photo',
    },
  },
  {
    id: 'VSEO-021',
    batch: 'B03',
    sourcePath: 'assets/visual-seo/B03/source/VSEO-021__best-glasses-frame-comparison-result.png',
    publicPath: '/images/seo/core/best-glasses-frame-comparison-result.webp',
    pagePath: '/compare-glasses-frames',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    heading: 'Narrow a Comparison to a Strong Match',
    alt: 'Three eyeglass frame options on the same woman with one subtly highlighted as a strong visual match',
    body: 'A shortlist can preserve several valid alternatives while still identifying one direction that appears especially balanced. The emphasis should remain qualitative and visual, without invented scores, percentages, or rankings that imply false precision.',
    link: {
      href: '/en/ai-glasses-advisor',
      label: 'Explore personalized frame directions',
    },
  },
  {
    id: 'VSEO-022',
    batch: 'B03',
    sourcePath: 'assets/visual-seo/B03/source/VSEO-022__ai-glasses-advisor-analysis.png',
    publicPath: '/images/seo/core/ai-glasses-advisor-analysis.webp',
    pagePath: '/ai-glasses-advisor',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    heading: 'What an AI Glasses Advisor Can Consider',
    alt: 'AI glasses advisor analysis showing balanced face width, gentle jaw taper, and moderate face length',
    body: 'An advisor can use visible facial proportions as practical decision inputs. Balanced width, a gentle jaw taper, and moderate face length are examples of observations that can narrow frame directions without turning the analysis into a biometric score.',
    link: {
      href: '/en/face-shape-detector',
      label: 'Understand your face proportions',
    },
  },
  {
    id: 'VSEO-023',
    batch: 'B03',
    sourcePath: 'assets/visual-seo/B03/source/VSEO-023__ai-glasses-recommendations.png',
    publicPath: '/images/seo/core/ai-glasses-recommendations.webp',
    pagePath: '/ai-glasses-advisor',
    width: 1448,
    height: 1086,
    displayWidth: 'primary',
    bodyPosition: 'before',
    heading: 'Explore AI Glasses Advisor Recommendations',
    alt: 'AI glasses advisor suggesting lift, structure, and balanced eyeglass frame directions',
    body: 'Useful recommendations reduce a large catalog to a few directions worth testing. Lift, structure, and balanced shapes describe different visual effects you can evaluate on your own face rather than treating one frame family as universally best.',
    link: {
      href: '/en/try-glasses-on-photo',
      label: 'Try a recommended frame on your photo',
    },
  },
  {
    id: 'VSEO-024',
    batch: 'B03',
    sourcePath: 'assets/visual-seo/B03/source/VSEO-024__ai-glasses-advisor-try-on.png',
    publicPath: '/images/seo/core/ai-glasses-advisor-try-on.webp',
    pagePath: '/ai-glasses-advisor',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    heading: 'From Face Analysis to Try-On and Compare',
    alt: 'AI glasses advisor workflow from face proportions to recommendations, virtual try-on, and frame comparison',
    body: 'The advisor is one step in a broader decision flow: understand visible proportions, narrow the frame directions, validate a candidate through virtual try-on, and compare the remaining options before choosing what to explore further.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare your shortlisted frames',
    },
  },
] as const satisfies readonly VisualSeoAsset[]

export const B04_VISUAL_SEO_ASSETS = [
  {
    id: 'VSEO-025',
    batch: 'B04',
    sourcePath: 'assets/visual-seo/B04/source/VSEO-025__best-glasses-for-round-face.png',
    publicPath: '/images/seo/core/best-glasses-for-round-face.webp',
    pagePath: '/style/round-face',
    width: 1448,
    height: 1086,
    displayWidth: 'primary',
    bodyPosition: 'before',
    stage: 'hero',
    heading: 'Best Glasses for Round Faces',
    alt: 'Best glasses for a round face showing rectangle, browline, and geometric frame directions',
    body: 'Rectangle, browline, and geometric frames can add structure and contrast to round proportions. Start with enough width and visible corners, then check how the frame sits relative to your cheeks and brows.',
    link: {
      href: '/en/try-on/glasses',
      label: 'Try these frame directions on your photo',
    },
  },
  {
    id: 'VSEO-026',
    batch: 'B04',
    sourcePath: 'assets/visual-seo/B04/source/VSEO-026__round-face-frame-comparison.png',
    publicPath: '/images/seo/core/round-face-frame-comparison.webp',
    pagePath: '/style/round-face',
    width: 1448,
    height: 1086,
    displayWidth: 'compare',
    bodyPosition: 'before',
    stage: 'compare',
    heading: 'Rectangle vs Round Frames on a Round Face',
    alt: 'Round face comparing rectangle and round eyeglass frames to show structure and softness',
    body: 'Rectangle frames create a more defined outline against soft curves, while round frames continue the face shape for a gentler effect. Compare both directions on the same photo to decide which visual balance feels right.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare shortlisted frames',
    },
  },
  {
    id: 'VSEO-027',
    batch: 'B04',
    sourcePath: 'assets/visual-seo/B04/source/VSEO-027__round-face-glasses-proportions.png',
    publicPath: '/images/seo/core/round-face-glasses-proportions.webp',
    pagePath: '/style/round-face',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    stage: 'fit',
    heading: 'Check Frame Proportions for a Round Face',
    alt: 'Round face glasses fit guide showing frame width, lens depth, and a slightly angular silhouette',
    body: 'Shape is only the first filter. Check that the frame has enough width for the cheek area, moderate lens depth, and a silhouette that adds direction without overwhelming the face.',
    link: {
      href: '/en/ai-glasses-advisor',
      label: 'Get personalized frame directions',
    },
  },
  {
    id: 'VSEO-028',
    batch: 'B04',
    sourcePath: 'assets/visual-seo/B04/source/VSEO-028__best-glasses-for-oval-face.png',
    publicPath: '/images/seo/core/best-glasses-for-oval-face.webp',
    pagePath: '/style/oval-face',
    width: 1448,
    height: 1086,
    displayWidth: 'primary',
    bodyPosition: 'before',
    stage: 'hero',
    heading: 'Best Glasses for Oval Faces',
    alt: 'Best glasses for an oval face showing cat-eye, aviator, and soft rectangle frame directions',
    body: 'Oval proportions work with many frame directions, including cat-eye, aviator, and soft rectangle styles. Keep the frame in proportion with the face, then use shape and scale to choose the visual effect you want.',
    link: {
      href: '/en/try-on/glasses',
      label: 'Try these frame directions on your photo',
    },
  },
  {
    id: 'VSEO-029',
    batch: 'B04',
    sourcePath: 'assets/visual-seo/B04/source/VSEO-029__oval-face-frame-comparison.png',
    publicPath: '/images/seo/core/oval-face-frame-comparison.webp',
    pagePath: '/style/oval-face',
    width: 1448,
    height: 1086,
    displayWidth: 'compare',
    bodyPosition: 'before',
    stage: 'compare',
    heading: 'Cat-Eye vs Aviator Frames on an Oval Face',
    alt: 'Oval face comparing cat-eye and aviator eyeglass frames with different lift and openness',
    body: 'A cat-eye frame can add more lift through the outer corners, while an aviator creates a more open and relaxed direction. Compare the same crop and face proportions before deciding which effect suits your style.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare shortlisted frames',
    },
  },
  {
    id: 'VSEO-030',
    batch: 'B04',
    sourcePath: 'assets/visual-seo/B04/source/VSEO-030__oval-face-glasses-proportions.png',
    publicPath: '/images/seo/core/oval-face-glasses-proportions.webp',
    pagePath: '/style/oval-face',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    stage: 'fit',
    heading: 'Check Frame Proportions for an Oval Face',
    alt: 'Oval face glasses fit guide showing frame width, lens depth, and brow relationship',
    body: 'With an oval face, compare frame width with the temples and cheek area, then check lens depth and brow relationship. Balanced proportions usually matter more than choosing one supposedly ideal frame shape.',
    link: {
      href: '/en/ai-glasses-advisor',
      label: 'Get personalized frame directions',
    },
  },
  {
    id: 'VSEO-031',
    batch: 'B04',
    sourcePath: 'assets/visual-seo/B04/source/VSEO-031__best-glasses-for-square-face.png',
    publicPath: '/images/seo/core/best-glasses-for-square-face.webp',
    pagePath: '/style/square-face',
    width: 1448,
    height: 1086,
    displayWidth: 'primary',
    bodyPosition: 'before',
    stage: 'hero',
    heading: 'Best Glasses for Square Faces',
    alt: 'Best glasses for a square face showing rounded, aviator, and light rim frame directions',
    body: 'Rounded, aviator, and light-rim frames can soften a strong jaw or create a lighter contrast with square proportions. Compare curved edges, construction, and width to choose whether you want softness or more emphasis.',
    link: {
      href: '/en/try-on/glasses',
      label: 'Try these frame directions on your photo',
    },
  },
  {
    id: 'VSEO-032',
    batch: 'B04',
    sourcePath: 'assets/visual-seo/B04/source/VSEO-032__square-face-frame-comparison.png',
    publicPath: '/images/seo/core/square-face-frame-comparison.webp',
    pagePath: '/style/square-face',
    width: 1448,
    height: 1086,
    displayWidth: 'compare',
    bodyPosition: 'before',
    stage: 'compare',
    heading: 'Rounded vs Strong Rectangle Frames on a Square Face',
    alt: 'Square face comparing rounded and strongly rectangular eyeglass frames with softer and more angular effects',
    body: 'Rounded frames soften the outline around a defined jaw, while strong rectangles echo the face structure and create a more angular effect. A neutral side-by-side comparison helps you choose the direction intentionally.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare shortlisted frames',
    },
  },
  {
    id: 'VSEO-033',
    batch: 'B04',
    sourcePath: 'assets/visual-seo/B04/source/VSEO-033__square-face-glasses-proportions.png',
    publicPath: '/images/seo/core/square-face-glasses-proportions.webp',
    pagePath: '/style/square-face',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    stage: 'fit',
    heading: 'Check Frame Proportions for a Square Face',
    alt: 'Square face glasses fit guide showing balanced frame width, softened corners, and lens depth',
    body: 'Look for a frame width that matches the face without copying the jaw exactly. Softened corners and adequate lens depth can reduce visual heaviness, while a lighter rim keeps the strong structure readable.',
    link: {
      href: '/en/ai-glasses-advisor',
      label: 'Get personalized frame directions',
    },
  },
] as const satisfies readonly VisualSeoAsset[]

export const B05_VISUAL_SEO_ASSETS = [
  {
    id: 'VSEO-034',
    batch: 'B05',
    sourcePath: 'assets/visual-seo/B05/source/VSEO-034__best-glasses-for-heart-face.png',
    publicPath: '/images/seo/core/best-glasses-for-heart-face.webp',
    pagePath: '/style/heart-face',
    width: 1448,
    height: 1086,
    displayWidth: 'primary',
    bodyPosition: 'before',
    stage: 'hero',
    heading: 'Best Glasses for Heart-Shaped Faces',
    alt: 'Best glasses directions for a heart-shaped face including cat-eye, rounded, and rimless frames',
    body: 'Cat-eye, rounded, and light or rimless frames can balance a wider forehead with a narrower chin. Compare the visual weight of the upper and lower frame lines, then check width and bridge placement on your own face.',
    link: {
      href: '/en/try-on/glasses',
      label: 'Try these frame directions on your photo',
    },
  },
  {
    id: 'VSEO-035',
    batch: 'B05',
    sourcePath: 'assets/visual-seo/B05/source/VSEO-035__heart-face-frame-comparison.png',
    publicPath: '/images/seo/core/heart-face-frame-comparison.webp',
    pagePath: '/style/heart-face',
    width: 1448,
    height: 1086,
    displayWidth: 'compare',
    bodyPosition: 'before',
    stage: 'compare',
    heading: 'Rounded vs Cat-Eye Frames on a Heart-Shaped Face',
    alt: 'Rounded vs subtle cat-eye glasses comparison on a heart-shaped face',
    body: 'A rounded frame can soften the transition from forehead to chin, while a subtle cat-eye adds lift through the outer corners. Compare both directions neutrally and choose the balance that fits your intended style.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare shortlisted frames',
    },
  },
  {
    id: 'VSEO-036',
    batch: 'B05',
    sourcePath: 'assets/visual-seo/B05/source/VSEO-036__heart-face-glasses-proportions.png',
    publicPath: '/images/seo/core/heart-face-glasses-proportions.webp',
    pagePath: '/style/heart-face',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    stage: 'fit',
    heading: 'Check Frame Proportions for a Heart-Shaped Face',
    alt: 'Frame width and proportion guide for glasses on a heart-shaped face',
    body: 'Look for a frame width that supports the cheek area without making the forehead feel heavier. Lens depth, bridge position, and a lighter lower rim can help keep the full face in visual balance.',
    link: {
      href: '/en/ai-glasses-advisor',
      label: 'Get personalized frame directions',
    },
  },
  {
    id: 'VSEO-037',
    batch: 'B05',
    sourcePath: 'assets/visual-seo/B05/source/VSEO-037__best-glasses-for-diamond-face.png',
    publicPath: '/images/seo/core/best-glasses-for-diamond-face.webp',
    pagePath: '/style/diamond-face',
    width: 1448,
    height: 1086,
    displayWidth: 'primary',
    bodyPosition: 'before',
    stage: 'hero',
    heading: 'Best Glasses for Diamond-Shaped Faces',
    alt: 'Best glasses directions for a diamond-shaped face including oval, browline, and cat-eye frames',
    body: 'Oval, browline, and cat-eye frames can balance prominent cheekbones while adding a considered emphasis near the brow. Start with the overall frame width and edge softness, then validate the effect on your own photo.',
    link: {
      href: '/en/try-on/glasses',
      label: 'Try these frame directions on your photo',
    },
  },
  {
    id: 'VSEO-038',
    batch: 'B05',
    sourcePath: 'assets/visual-seo/B05/source/VSEO-038__diamond-face-frame-comparison.png',
    publicPath: '/images/seo/core/diamond-face-frame-comparison.webp',
    pagePath: '/style/diamond-face',
    width: 1448,
    height: 1086,
    displayWidth: 'compare',
    bodyPosition: 'before',
    stage: 'compare',
    heading: 'Browline vs Oval Frames on a Diamond-Shaped Face',
    alt: 'Browline vs oval glasses comparison on a diamond-shaped face',
    body: 'A browline frame gives more emphasis to the upper face, while an oval frame creates a softer contour around the cheekbones. Seeing both on the same face helps separate shape preference from assumptions about one perfect style.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare shortlisted frames',
    },
  },
  {
    id: 'VSEO-039',
    batch: 'B05',
    sourcePath: 'assets/visual-seo/B05/source/VSEO-039__diamond-face-glasses-proportions.png',
    publicPath: '/images/seo/core/diamond-face-glasses-proportions.webp',
    pagePath: '/style/diamond-face',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    stage: 'fit',
    heading: 'Check Frame Proportions for a Diamond-Shaped Face',
    alt: 'Frame width and proportion guide for glasses on a diamond-shaped face with prominent cheekbones',
    body: 'Compare frame width with the widest cheek area, then check whether the brow line and lower rim distribute visual weight comfortably. Gently rounded edges can soften the outline without hiding the face shape.',
    link: {
      href: '/en/ai-glasses-advisor',
      label: 'Get personalized frame directions',
    },
  },
  {
    id: 'VSEO-040',
    batch: 'B05',
    sourcePath: 'assets/visual-seo/B05/source/VSEO-040__best-glasses-for-oblong-face.png',
    publicPath: '/images/seo/core/best-glasses-for-oblong-face.webp',
    pagePath: '/style/oblong-face',
    width: 1448,
    height: 1086,
    displayWidth: 'primary',
    bodyPosition: 'before',
    stage: 'hero',
    heading: 'Best Glasses for Oblong Faces',
    alt: 'Best glasses directions for an oblong face including oversized, deeper rounded, and aviator frames',
    body: 'Oversized, deeper rounded, and aviator frames can add visible width and lens depth to longer proportions. Compare the frame height, temple width, and overall scale so the glasses support rather than exaggerate the face length.',
    link: {
      href: '/en/try-on/glasses',
      label: 'Try these frame directions on your photo',
    },
  },
  {
    id: 'VSEO-041',
    batch: 'B05',
    sourcePath: 'assets/visual-seo/B05/source/VSEO-041__oblong-face-frame-comparison.png',
    publicPath: '/images/seo/core/oblong-face-frame-comparison.webp',
    pagePath: '/style/oblong-face',
    width: 1448,
    height: 1086,
    displayWidth: 'compare',
    bodyPosition: 'before',
    stage: 'compare',
    heading: 'Oversized vs Deeper Rounded Frames on an Oblong Face',
    alt: 'Oversized vs deeper rounded glasses comparison on an oblong face',
    body: 'An oversized frame changes the overall width and presence, while a deeper rounded frame adds vertical coverage and a softer outline. Compare both effects on the same crop before deciding which proportion feels more balanced.',
    link: {
      href: '/en/compare-glasses-frames',
      label: 'Compare shortlisted frames',
    },
  },
  {
    id: 'VSEO-042',
    batch: 'B05',
    sourcePath: 'assets/visual-seo/B05/source/VSEO-042__oblong-face-glasses-proportions.png',
    publicPath: '/images/seo/core/oblong-face-glasses-proportions.webp',
    pagePath: '/style/oblong-face',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'before',
    stage: 'fit',
    heading: 'Check Frame Proportions for an Oblong Face',
    alt: 'Frame width and proportion guide for glasses on an oblong face showing lens depth and scale',
    body: 'Prioritize enough frame width and lens depth to create balanced coverage across a longer face. Check the bridge, lower rim, and temple position together rather than judging height or width in isolation.',
    link: {
      href: '/en/ai-glasses-advisor',
      label: 'Get personalized frame directions',
    },
  },
] as const satisfies readonly VisualSeoAsset[]

export const B06_VISUAL_SEO_ASSETS = [
  {
    id: 'VSEO-043',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-043__round-face-shape-characteristics.png',
    publicPath: '/images/seo/face-shapes/round-face-shape-characteristics.webp',
    pagePath: '/face-shapes/round',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'characteristics',
    priority: true,
    heading: 'Round Face Shape Characteristics',
    alt: 'Round face shape characteristics showing a soft jawline, fuller cheeks, and similar face width and length',
    body: 'A round face usually has similar visible width and length, fuller cheeks, and a softly curved jawline. The outline is defined by gentle transitions rather than a sharply angled jaw.',
  },
  {
    id: 'VSEO-044',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-044__how-to-identify-round-face.png',
    publicPath: '/images/seo/face-shapes/how-to-identify-round-face.webp',
    pagePath: '/face-shapes/round',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'identify',
    priority: true,
    heading: 'How to Identify a Round Face',
    alt: 'How to identify a round face by cheekbone width, soft jawline, and similar face width and length',
    body: 'Look for a soft jawline, cheeks that form the widest area, and a face width that is relatively close to its length. Consider all three signals together instead of using cheek fullness alone.',
  },
  {
    id: 'VSEO-045',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-045__oval-face-shape-characteristics.png',
    publicPath: '/images/seo/face-shapes/oval-face-shape-characteristics.webp',
    pagePath: '/face-shapes/oval',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'characteristics',
    priority: true,
    heading: 'Oval Face Shape Characteristics',
    alt: 'Oval face shape characteristics showing a moderately longer face, balanced width, and softly tapered jaw',
    body: 'An oval face is moderately longer than it is wide, with balanced proportions and a softly tapered jaw. The cheekbones may be the widest area without one feature overwhelming the rest of the outline.',
  },
  {
    id: 'VSEO-046',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-046__how-to-identify-oval-face.png',
    publicPath: '/images/seo/face-shapes/how-to-identify-oval-face.webp',
    pagePath: '/face-shapes/oval',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'identify',
    priority: true,
    heading: 'How to Identify an Oval Face',
    alt: 'How to identify an oval face by moderate face length, balanced cheekbones, and a softly tapered jaw',
    body: 'Compare a moderate length-to-width relationship with a gradual jaw taper and balanced forehead and cheekbone width. An oval face should not read as strongly angular, nearly circular, or extremely long.',
  },
  {
    id: 'VSEO-047',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-047__square-face-shape-characteristics.png',
    publicPath: '/images/seo/face-shapes/square-face-shape-characteristics.webp',
    pagePath: '/face-shapes/square',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'characteristics',
    priority: true,
    heading: 'Square Face Shape Characteristics',
    alt: 'Square face shape characteristics showing a broad forehead, defined jaw corners, and balanced face width',
    body: 'A square face combines balanced width with a more visible jaw structure. The forehead and jaw are often similar in width, and the outline feels defined rather than continuously curved.',
  },
  {
    id: 'VSEO-048',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-048__how-to-identify-square-face.png',
    publicPath: '/images/seo/face-shapes/how-to-identify-square-face.webp',
    pagePath: '/face-shapes/square',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'identify',
    priority: true,
    heading: 'How to Identify a Square Face',
    alt: 'How to identify a square face by similar forehead and jaw width, visible jaw corners, and balanced length',
    body: 'Check whether the forehead and jaw are close in width, the jaw corners are visible, and the face is balanced rather than dominated by vertical length. A single angular feature is not enough on its own.',
  },
  {
    id: 'VSEO-049',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-049__heart-face-shape-characteristics.png',
    publicPath: '/images/seo/face-shapes/heart-face-shape-characteristics.webp',
    pagePath: '/face-shapes/heart',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'characteristics',
    priority: true,
    heading: 'Heart Face Shape Characteristics',
    alt: 'Heart face shape characteristics showing a wider forehead, prominent upper cheeks, and narrower pointed chin',
    body: 'A heart-shaped face is wider through the forehead or upper cheeks and tapers toward a narrower chin. A widow’s peak can reinforce the impression, but the forehead-to-jaw relationship matters more than the hairline.',
  },
  {
    id: 'VSEO-050',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-050__how-to-identify-heart-face.png',
    publicPath: '/images/seo/face-shapes/how-to-identify-heart-face.webp',
    pagePath: '/face-shapes/heart',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'identify',
    priority: true,
    heading: 'How to Identify a Heart-Shaped Face',
    alt: 'How to identify a heart-shaped face by a wider forehead, tapering jaw, and narrow chin',
    body: 'Compare the upper face with the lower face: the forehead or upper cheeks should carry more width while the jaw narrows toward the chin. Prominent cheekbones can occur, so check the full taper rather than one landmark.',
  },
  {
    id: 'VSEO-051',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-051__diamond-face-shape-characteristics.png',
    publicPath: '/images/seo/face-shapes/diamond-face-shape-characteristics.webp',
    pagePath: '/face-shapes/diamond',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'characteristics',
    priority: true,
    heading: 'Diamond Face Shape Characteristics',
    alt: 'Diamond face shape characteristics showing a narrow forehead, widest cheekbones, and narrow jaw and chin',
    body: 'A diamond face puts the strongest width through the cheekbones, while the forehead and jaw are both narrower. The outline widens through the middle and tapers toward both the temples and chin.',
  },
  {
    id: 'VSEO-052',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-052__how-to-identify-diamond-face.png',
    publicPath: '/images/seo/face-shapes/how-to-identify-diamond-face.webp',
    pagePath: '/face-shapes/diamond',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'identify',
    priority: true,
    heading: 'How to Identify a Diamond Face',
    alt: 'How to identify a diamond face by cheekbones wider than the forehead and jaw, with a tapered chin',
    body: 'The cheekbones should be clearly wider than both the forehead and jaw, creating a distinct middle-face emphasis. Narrow temples and a tapering lower face help distinguish diamond from heart and oval patterns.',
  },
  {
    id: 'VSEO-053',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-053__oblong-face-shape-characteristics.png',
    publicPath: '/images/seo/face-shapes/oblong-face-shape-characteristics.webp',
    pagePath: '/face-shapes/oblong',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'characteristics',
    priority: true,
    heading: 'Oblong Face Shape Characteristics',
    alt: 'Oblong face shape characteristics showing a noticeably longer face and relatively consistent width from forehead to jaw',
    body: 'An oblong face is led by vertical length, with the forehead, cheeks, and jaw often staying relatively consistent in width. The side lines may appear straighter than on an oval face.',
  },
  {
    id: 'VSEO-054',
    batch: 'B06',
    sourcePath: 'assets/visual-seo/B06/source/VSEO-054__how-to-identify-oblong-face.png',
    publicPath: '/images/seo/face-shapes/how-to-identify-oblong-face.webp',
    pagePath: '/face-shapes/oblong',
    width: 1448,
    height: 1086,
    displayWidth: 'secondary',
    bodyPosition: 'after',
    stage: 'identify',
    priority: true,
    heading: 'How to Identify an Oblong Face',
    alt: 'How to identify an oblong face by pronounced length, relatively straight sides, and consistent width across the face',
    body: 'Look first at the length-to-width relationship: vertical length is more pronounced while the forehead, cheeks, and jaw stay relatively close in width. Straighter side lines support the identification, regardless of whether the chin is rounded or angular.',
  },
] as const satisfies readonly VisualSeoAsset[]

export const VISUAL_SEO_ASSETS = [
  ...B01_VISUAL_SEO_ASSETS,
  ...B02_VISUAL_SEO_ASSETS,
  ...B03_VISUAL_SEO_ASSETS,
  ...B04_VISUAL_SEO_ASSETS,
  ...B05_VISUAL_SEO_ASSETS,
  ...B06_VISUAL_SEO_ASSETS,
] as const

export function getVisualSeoAssetsForPage(pagePath: string, batch?: VisualSeoAssetBatch): readonly VisualSeoAsset[] {
  return VISUAL_SEO_ASSETS.filter((asset) => asset.pagePath === pagePath && (!batch || asset.batch === batch))
}
