export type ConversionPurchaseContext =
  | 'try_on'
  | 'frame_compare'
  | 'style_explorer'
  | 'face_analysis_top_picks'
  | 'face_analysis_unlock'

export type PaywallCopy = {
  eyebrow: string
  title: string
  description: string
  packTitle: (count: number) => string
  oneTime: string
  benefits: string[]
  continueLabel: (price: string) => string
  processing: string
  regularUse: string
  standardFrom: (price: string) => string
  viewPlans: string
  secureCheckout: string
  close: string
  successTitle: string
  successBody: string
  cancelledTitle: string
  cancelledBody: string
  paymentError: string
}

const EN_COPY: Record<ConversionPurchaseContext, PaywallCopy> = {
  try_on: {
    eyebrow: 'TRY-ON',
    title: 'Keep trying',
    description: 'Add credits and continue where you left off without choosing a subscription.',
    packTitle: (count) => `${count} Decision Credits`,
    oneTime: 'One-time purchase',
    benefits: ['Continue virtual try-on', 'Use across VisuTry', 'Credits do not expire', 'No subscription'],
    continueLabel: (price) => `Continue for ${price}`,
    processing: 'Opening secure checkout…',
    regularUse: 'Need credits regularly?',
    standardFrom: (price) => `Standard starts at ${price}/month`,
    viewPlans: 'View subscription plans',
    secureCheckout: 'Secure checkout · One-time purchase',
    close: 'Close',
    successTitle: 'Credits added',
    successBody: 'Your credits are verified. Continue where you left off whenever you are ready.',
    cancelledTitle: 'Payment not completed',
    cancelledBody: 'Your current task is still here. You can continue whenever you are ready.',
    paymentError: 'Checkout could not be started. Please try again.',
  },
  frame_compare: {
    eyebrow: 'FRAME COMPARE',
    title: 'Finish your comparison — and keep exploring',
    description: 'Use credits to complete your current comparison, then try more frames and styles. Unused credits never expire.',
    packTitle: (count) => `${count} Decision Credits`,
    oneTime: 'One-time purchase',
    benefits: [
      'Complete your frame comparison',
      'Try more frames from the collection',
      'Explore different Style looks',
      'Unused credits never expire',
    ],
    continueLabel: (price) => `Continue for ${price}`,
    processing: 'Opening secure checkout…',
    regularUse: 'Need credits regularly?',
    standardFrom: (price) => `Standard starts at ${price}/month`,
    viewPlans: 'View subscription plans',
    secureCheckout: 'Secure checkout · One-time purchase',
    close: 'Close',
    successTitle: 'Credits added',
    successBody: 'Your credits are verified. Review your restored photo and frame choices, then start the comparison when ready.',
    cancelledTitle: 'Payment not completed',
    cancelledBody: 'Your comparison is still here. You can continue whenever you are ready.',
    paymentError: 'Checkout could not be started. Please try again.',
  },
  style_explorer: {
    eyebrow: 'STYLE EXPLORER',
    title: 'Explore 4 new looks — and keep discovering your style',
    description: 'Create your four selected looks, then keep exploring optical frames, sunglasses, and new style directions. Unused credits never expire.',
    packTitle: (count) => `${count} Decision Credits`,
    oneTime: 'One-time purchase',
    benefits: [
      'Create your next 4 Style looks',
      'Explore optical frames and sunglasses',
      'Try more styles whenever you want',
      'Unused credits never expire',
    ],
    continueLabel: (price) => `Continue for ${price}`,
    processing: 'Opening secure checkout…',
    regularUse: 'Need credits regularly?',
    standardFrom: (price) => `Standard starts at ${price}/month`,
    viewPlans: 'View subscription plans',
    secureCheckout: 'Secure checkout · One-time purchase',
    close: 'Close',
    successTitle: 'Credits added',
    successBody: 'Your credits are verified. Review your style choices, then create your four looks when ready.',
    cancelledTitle: 'Payment not completed',
    cancelledBody: 'Your Style Explorer choices are still here. You can continue whenever you are ready.',
    paymentError: 'Checkout could not be started. Please try again.',
  },
  face_analysis_top_picks: {
    eyebrow: 'YOUR TOP PICKS',
    title: 'Try your recommended frames — and keep exploring',
    description: 'Start with your 4 Face Analysis Top Picks, then compare more frames and explore different styles. Unused credits never expire.',
    packTitle: (count) => `${count} Decision Credits`,
    oneTime: 'One-time purchase',
    benefits: [
      'Try your 4 recommended frames',
      'Compare more frames from the collection',
      'Explore different Style looks',
      'Unused credits never expire',
    ],
    continueLabel: (price) => `Continue for ${price}`,
    processing: 'Opening secure checkout…',
    regularUse: 'Need credits regularly?',
    standardFrom: (price) => `Standard starts at ${price}/month`,
    viewPlans: 'View subscription plans',
    secureCheckout: 'Secure checkout · One-time purchase',
    close: 'Close',
    successTitle: 'Credits added',
    successBody: 'Your credits are verified. Your Face Analysis is still here—try your Top Picks whenever you are ready.',
    cancelledTitle: 'Payment not completed',
    cancelledBody: 'Your Face Analysis is still here. You can continue with your Top Picks whenever you are ready.',
    paymentError: 'Checkout could not be started. Please try again.',
  },
  face_analysis_unlock: {
    eyebrow: 'FACE ANALYSIS',
    title: 'Unlock your full eyewear report',
    description: 'Get your complete recommendations, styling guidance, and 30 non-expiring credits to try the frames you discover.',
    packTitle: (count) => `Full report + ${count} Decision Credits`,
    oneTime: 'One-time purchase',
    benefits: [
      'Unlock your complete Face Analysis report',
      'See personalized frame recommendations',
      'Try recommended frames and more styles',
      'Unused credits never expire',
    ],
    continueLabel: (price) => `Unlock for ${price}`,
    processing: 'Opening secure checkout…',
    regularUse: 'Need credits regularly?',
    standardFrom: (price) => `Standard starts at ${price}/month`,
    viewPlans: 'View subscription plans',
    secureCheckout: 'Secure checkout · One-time purchase',
    close: 'Close',
    successTitle: 'Report unlocked',
    successBody: 'Your payment is verified. VisuTry is reopening your complete report now.',
    cancelledTitle: 'Payment not completed',
    cancelledBody: 'Your Face Analysis report is still here. You can unlock it whenever you are ready.',
    paymentError: 'Checkout could not be started. Please try again.',
  },
}

const LOCALIZED_COMMON: Record<string, Partial<PaywallCopy>> = {
  id: {
    oneTime: 'Pembelian satu kali',
    processing: 'Membuka pembayaran aman…',
    regularUse: 'Butuh kredit secara rutin?',
    standardFrom: (price) => `Standard mulai ${price}/bulan`,
    viewPlans: 'Lihat paket langganan',
    secureCheckout: 'Pembayaran aman · Pembelian satu kali',
    close: 'Tutup',
    successTitle: 'Kredit ditambahkan',
    successBody: 'Pembayaran telah diverifikasi. Lanjutkan tugas Anda kapan saja.',
    cancelledTitle: 'Pembayaran belum selesai',
    cancelledBody: 'Tugas Anda masih tersimpan. Anda dapat melanjutkan kapan saja.',
    paymentError: 'Pembayaran tidak dapat dimulai. Silakan coba lagi.',
  },
  ar: {
    oneTime: 'شراء لمرة واحدة',
    processing: 'جارٍ فتح الدفع الآمن…',
    regularUse: 'تحتاج رصيدًا بانتظام؟',
    standardFrom: (price) => `تبدأ Standard من ${price}/شهريًا`,
    viewPlans: 'عرض خطط الاشتراك',
    secureCheckout: 'دفع آمن · شراء لمرة واحدة',
    close: 'إغلاق',
    successTitle: 'تمت إضافة الرصيد',
    successBody: 'تم التحقق من الدفع. يمكنك متابعة مهمتك عندما تكون جاهزًا.',
    cancelledTitle: 'لم يكتمل الدفع',
    cancelledBody: 'مهمتك ما زالت محفوظة. يمكنك المتابعة عندما تكون جاهزًا.',
    paymentError: 'تعذر بدء الدفع. حاول مرة أخرى.',
  },
  ru: {
    oneTime: 'Разовая покупка',
    processing: 'Открываем безопасную оплату…',
    regularUse: 'Нужны кредиты регулярно?',
    standardFrom: (price) => `Standard от ${price}/мес.`,
    viewPlans: 'Посмотреть подписки',
    secureCheckout: 'Безопасная оплата · Разовая покупка',
    close: 'Закрыть',
    successTitle: 'Кредиты добавлены',
    successBody: 'Платёж подтверждён. Продолжите с того места, где остановились.',
    cancelledTitle: 'Оплата не завершена',
    cancelledBody: 'Ваш текущий шаг сохранён. Вы сможете продолжить позже.',
    paymentError: 'Не удалось начать оплату. Попробуйте ещё раз.',
  },
  de: {
    oneTime: 'Einmaliger Kauf',
    processing: 'Sicherer Checkout wird geöffnet…',
    regularUse: 'Brauchst du regelmäßig Credits?',
    standardFrom: (price) => `Standard ab ${price}/Monat`,
    viewPlans: 'Abos ansehen',
    secureCheckout: 'Sicherer Checkout · Einmaliger Kauf',
    close: 'Schließen',
    successTitle: 'Credits hinzugefügt',
    successBody: 'Die Zahlung ist bestätigt. Du kannst deine Aufgabe jederzeit fortsetzen.',
    cancelledTitle: 'Zahlung nicht abgeschlossen',
    cancelledBody: 'Deine aktuelle Aufgabe bleibt erhalten. Du kannst später weitermachen.',
    paymentError: 'Checkout konnte nicht gestartet werden. Bitte versuche es erneut.',
  },
  ja: {
    oneTime: '1回限りの購入',
    processing: '安全な決済を開いています…',
    regularUse: '定期的にクレジットが必要ですか？',
    standardFrom: (price) => `Standard は月額 ${price} から`,
    viewPlans: 'サブスクリプションを見る',
    secureCheckout: '安全な決済 · 1回限りの購入',
    close: '閉じる',
    successTitle: 'クレジットを追加しました',
    successBody: 'お支払いを確認しました。準備ができたら続きから再開できます。',
    cancelledTitle: '支払いは完了していません',
    cancelledBody: '現在の作業はそのまま残っています。いつでも続けられます。',
    paymentError: '決済を開始できませんでした。もう一度お試しください。',
  },
  es: {
    oneTime: 'Compra única',
    processing: 'Abriendo pago seguro…',
    regularUse: '¿Necesitas créditos con frecuencia?',
    standardFrom: (price) => `Standard desde ${price}/mes`,
    viewPlans: 'Ver suscripciones',
    secureCheckout: 'Pago seguro · Compra única',
    close: 'Cerrar',
    successTitle: 'Créditos añadidos',
    successBody: 'El pago está verificado. Puedes continuar donde lo dejaste cuando quieras.',
    cancelledTitle: 'Pago no completado',
    cancelledBody: 'Tu tarea actual sigue guardada. Puedes continuar cuando quieras.',
    paymentError: 'No se pudo iniciar el pago. Inténtalo de nuevo.',
  },
  pt: {
    oneTime: 'Compra única',
    processing: 'Abrindo pagamento seguro…',
    regularUse: 'Precisa de créditos regularmente?',
    standardFrom: (price) => `Standard a partir de ${price}/mês`,
    viewPlans: 'Ver assinaturas',
    secureCheckout: 'Pagamento seguro · Compra única',
    close: 'Fechar',
    successTitle: 'Créditos adicionados',
    successBody: 'O pagamento foi verificado. Continue de onde parou quando quiser.',
    cancelledTitle: 'Pagamento não concluído',
    cancelledBody: 'Sua tarefa atual continua salva. Você pode continuar quando quiser.',
    paymentError: 'Não foi possível iniciar o pagamento. Tente novamente.',
  },
  fr: {
    oneTime: 'Achat unique',
    processing: 'Ouverture du paiement sécurisé…',
    regularUse: 'Besoin de crédits régulièrement ?',
    standardFrom: (price) => `Standard à partir de ${price}/mois`,
    viewPlans: 'Voir les abonnements',
    secureCheckout: 'Paiement sécurisé · Achat unique',
    close: 'Fermer',
    successTitle: 'Crédits ajoutés',
    successBody: 'Le paiement est vérifié. Reprenez votre tâche quand vous le souhaitez.',
    cancelledTitle: 'Paiement non terminé',
    cancelledBody: 'Votre tâche actuelle est toujours là. Vous pourrez la reprendre plus tard.',
    paymentError: 'Impossible de lancer le paiement. Veuillez réessayer.',
  },
}

const LOCALIZED_CONTEXT_COPY: Record<string, Partial<Record<ConversionPurchaseContext, Partial<PaywallCopy>>>> = {
  id: {
    try_on: {
      eyebrow: 'COBA VIRTUAL', title: 'Lanjutkan mencoba',
      description: 'Tambahkan kredit dan lanjutkan dari posisi terakhir tanpa berlangganan.',
      packTitle: (count) => `${count} Kredit Keputusan`,
      benefits: ['Lanjutkan coba virtual', 'Gunakan di seluruh VisuTry', 'Kredit tidak kedaluwarsa', 'Tanpa langganan'],
      continueLabel: (price) => `Lanjutkan dengan ${price}`,
    },
    frame_compare: {
      eyebrow: 'BANDINGKAN FRAME', title: 'Selesaikan perbandingan — lalu jelajahi lebih banyak',
      description: 'Selesaikan perbandingan saat ini, lalu coba lebih banyak frame dan gaya. Kredit yang tersisa tidak kedaluwarsa.',
      packTitle: (count) => `${count} Kredit Keputusan`,
      benefits: ['Selesaikan perbandingan frame', 'Coba lebih banyak frame', 'Jelajahi Style yang berbeda', 'Kredit tidak kedaluwarsa'],
      continueLabel: (price) => `Lanjutkan dengan ${price}`,
    },
    style_explorer: {
      eyebrow: 'STYLE EXPLORER', title: 'Jelajahi 4 tampilan baru — lalu temukan lebih banyak gaya',
      description: 'Buat empat tampilan pilihan Anda, lalu jelajahi frame optik, kacamata hitam, dan arah gaya baru.',
      packTitle: (count) => `${count} Kredit Keputusan`,
      benefits: ['Buat 4 tampilan Style berikutnya', 'Jelajahi frame optik dan kacamata hitam', 'Coba lebih banyak gaya kapan saja', 'Kredit tidak kedaluwarsa'],
      continueLabel: (price) => `Lanjutkan dengan ${price}`,
    },
    face_analysis_top_picks: {
      eyebrow: 'PILIHAN TERBAIK ANDA', title: 'Coba frame rekomendasi Anda — lalu jelajahi lebih banyak',
      description: 'Mulai dengan 4 Top Picks dari Face Analysis, lalu bandingkan lebih banyak frame dan gaya.',
      packTitle: (count) => `${count} Kredit Keputusan`,
      benefits: ['Coba 4 frame rekomendasi Anda', 'Bandingkan lebih banyak frame', 'Jelajahi Style yang berbeda', 'Kredit tidak kedaluwarsa'],
      continueLabel: (price) => `Lanjutkan dengan ${price}`,
    },
    face_analysis_unlock: {
      eyebrow: 'FACE ANALYSIS', title: 'Buka laporan eyewear lengkap Anda',
      description: 'Dapatkan rekomendasi lengkap, panduan gaya, dan 30 kredit tanpa kedaluwarsa untuk mencoba frame yang Anda temukan.',
      packTitle: (count) => `Laporan lengkap + ${count} Kredit Keputusan`,
      benefits: ['Buka laporan Face Analysis lengkap', 'Lihat rekomendasi frame personal', 'Coba frame rekomendasi dan gaya lain', 'Kredit tidak kedaluwarsa'],
      continueLabel: (price) => `Buka dengan ${price}`,
      successTitle: 'Laporan dibuka',
    },
  },
  ar: {
    try_on: {
      eyebrow: 'التجربة الافتراضية', title: 'تابع التجربة',
      description: 'أضف رصيدًا وتابع من حيث توقفت من دون اشتراك.',
      packTitle: (count) => `${count} رصيد قرار`,
      benefits: ['تابع التجربة الافتراضية', 'استخدم الرصيد في VisuTry', 'الرصيد لا تنتهي صلاحيته', 'لا اشتراك'],
      continueLabel: (price) => `تابع مقابل ${price}`,
    },
    frame_compare: {
      eyebrow: 'مقارنة الإطارات', title: 'أكمل المقارنة — ثم استكشف المزيد',
      description: 'أكمل المقارنة الحالية ثم جرّب مزيدًا من الإطارات والأنماط. الرصيد غير المستخدم لا تنتهي صلاحيته.',
      packTitle: (count) => `${count} رصيد قرار`,
      benefits: ['أكمل مقارنة الإطارات', 'جرّب مزيدًا من الإطارات', 'استكشف أنماط Style مختلفة', 'الرصيد غير المستخدم لا ينتهي'],
      continueLabel: (price) => `تابع مقابل ${price}`,
    },
    style_explorer: {
      eyebrow: 'مستكشف الأنماط', title: 'استكشف 4 إطلالات جديدة — وواصل اكتشاف أسلوبك',
      description: 'أنشئ الإطلالات الأربع المختارة ثم استكشف الإطارات الطبية والنظارات الشمسية واتجاهات أسلوب جديدة.',
      packTitle: (count) => `${count} رصيد قرار`,
      benefits: ['أنشئ 4 إطلالات Style جديدة', 'استكشف الإطارات والنظارات الشمسية', 'جرّب أنماطًا أكثر وقتما تشاء', 'الرصيد غير المستخدم لا ينتهي'],
      continueLabel: (price) => `تابع مقابل ${price}`,
    },
    face_analysis_top_picks: {
      eyebrow: 'أفضل اختياراتك', title: 'جرّب الإطارات الموصى بها — ثم استكشف المزيد',
      description: 'ابدأ بأفضل 4 اختيارات من تحليل الوجه، ثم قارن المزيد من الإطارات واستكشف أنماطًا مختلفة.',
      packTitle: (count) => `${count} رصيد قرار`,
      benefits: ['جرّب الإطارات الأربعة الموصى بها', 'قارن المزيد من الإطارات', 'استكشف أنماط Style مختلفة', 'الرصيد غير المستخدم لا ينتهي'],
      continueLabel: (price) => `تابع مقابل ${price}`,
    },
    face_analysis_unlock: {
      eyebrow: 'تحليل الوجه', title: 'افتح تقرير النظارات الكامل',
      description: 'احصل على توصياتك الكاملة وإرشادات الأسلوب و30 رصيدًا لا تنتهي صلاحيته لتجربة الإطارات التي تكتشفها.',
      packTitle: (count) => `التقرير الكامل + ${count} رصيد قرار`,
      benefits: ['افتح تقرير تحليل الوجه الكامل', 'شاهد توصيات الإطارات المخصصة', 'جرّب الإطارات الموصى بها وأنماطًا أخرى', 'الرصيد غير المستخدم لا ينتهي'],
      continueLabel: (price) => `افتح مقابل ${price}`,
      successTitle: 'تم فتح التقرير',
    },
  },
  ru: {
    try_on: {
      eyebrow: 'ВИРТУАЛЬНАЯ ПРИМЕРКА', title: 'Продолжить примерку',
      description: 'Добавьте кредиты и продолжите с того же места без подписки.',
      packTitle: (count) => `${count} кредитов для выбора`,
      benefits: ['Продолжить виртуальную примерку', 'Использовать во всём VisuTry', 'Кредиты не сгорают', 'Без подписки'],
      continueLabel: (price) => `Продолжить за ${price}`,
    },
    frame_compare: {
      eyebrow: 'СРАВНЕНИЕ ОПРАВ', title: 'Завершите сравнение — и исследуйте дальше',
      description: 'Завершите текущее сравнение, затем примерьте больше оправ и стилей. Неиспользованные кредиты не сгорают.',
      packTitle: (count) => `${count} кредитов для выбора`,
      benefits: ['Завершить сравнение оправ', 'Примерить больше оправ', 'Исследовать разные Style-образы', 'Кредиты не сгорают'],
      continueLabel: (price) => `Продолжить за ${price}`,
    },
    style_explorer: {
      eyebrow: 'STYLE EXPLORER', title: 'Создайте 4 новых образа — и продолжайте искать свой стиль',
      description: 'Создайте четыре выбранных образа, затем исследуйте оптические и солнцезащитные оправы и новые направления стиля.',
      packTitle: (count) => `${count} кредитов для выбора`,
      benefits: ['Создать следующие 4 Style-образа', 'Исследовать оптические и солнцезащитные оправы', 'Пробовать больше стилей в любое время', 'Кредиты не сгорают'],
      continueLabel: (price) => `Продолжить за ${price}`,
    },
    face_analysis_top_picks: {
      eyebrow: 'ВАШИ ЛУЧШИЕ ВАРИАНТЫ', title: 'Примерьте рекомендованные оправы — и исследуйте дальше',
      description: 'Начните с 4 лучших вариантов Face Analysis, затем сравнивайте больше оправ и стилей.',
      packTitle: (count) => `${count} кредитов для выбора`,
      benefits: ['Примерить 4 рекомендованные оправы', 'Сравнить больше оправ', 'Исследовать разные Style-образы', 'Кредиты не сгорают'],
      continueLabel: (price) => `Продолжить за ${price}`,
    },
    face_analysis_unlock: {
      eyebrow: 'АНАЛИЗ ЛИЦА', title: 'Откройте полный отчёт по подбору очков',
      description: 'Получите полные рекомендации, советы по стилю и 30 несгораемых кредитов для примерки найденных оправ.',
      packTitle: (count) => `Полный отчёт + ${count} кредитов`,
      benefits: ['Открыть полный отчёт Face Analysis', 'Увидеть персональные рекомендации', 'Примерять рекомендованные оправы и другие стили', 'Кредиты не сгорают'],
      continueLabel: (price) => `Открыть за ${price}`,
      successTitle: 'Отчёт открыт',
    },
  },
  de: {
    try_on: {
      eyebrow: 'VIRTUELLE ANPROBE', title: 'Weiter anprobieren',
      description: 'Füge Credits hinzu und mache ohne Abo dort weiter, wo du aufgehört hast.',
      packTitle: (count) => `${count} Decision Credits`,
      benefits: ['Virtuelle Anprobe fortsetzen', 'In VisuTry verwenden', 'Credits verfallen nicht', 'Kein Abo'],
      continueLabel: (price) => `Für ${price} fortfahren`,
    },
    frame_compare: {
      eyebrow: 'FASSUNGEN VERGLEICHEN', title: 'Vergleich abschließen — und weiter entdecken',
      description: 'Schließe deinen aktuellen Vergleich ab und probiere danach weitere Fassungen und Styles. Ungenutzte Credits verfallen nicht.',
      packTitle: (count) => `${count} Decision Credits`,
      benefits: ['Fassungsvergleich abschließen', 'Mehr Fassungen anprobieren', 'Weitere Style-Looks entdecken', 'Ungenutzte Credits verfallen nicht'],
      continueLabel: (price) => `Für ${price} fortfahren`,
    },
    style_explorer: {
      eyebrow: 'STYLE EXPLORER', title: 'Entdecke 4 neue Looks — und finde weiter deinen Stil',
      description: 'Erstelle vier ausgewählte Looks und entdecke danach optische Fassungen, Sonnenbrillen und neue Stilrichtungen.',
      packTitle: (count) => `${count} Decision Credits`,
      benefits: ['Die nächsten 4 Style-Looks erstellen', 'Optische Fassungen und Sonnenbrillen entdecken', 'Jederzeit weitere Styles testen', 'Ungenutzte Credits verfallen nicht'],
      continueLabel: (price) => `Für ${price} fortfahren`,
    },
    face_analysis_top_picks: {
      eyebrow: 'DEINE TOP PICKS', title: 'Probiere deine empfohlenen Fassungen — und entdecke mehr',
      description: 'Starte mit deinen 4 Face-Analysis-Top-Picks und vergleiche danach weitere Fassungen und Styles.',
      packTitle: (count) => `${count} Decision Credits`,
      benefits: ['4 empfohlene Fassungen anprobieren', 'Mehr Fassungen vergleichen', 'Weitere Style-Looks entdecken', 'Ungenutzte Credits verfallen nicht'],
      continueLabel: (price) => `Für ${price} fortfahren`,
    },
    face_analysis_unlock: {
      eyebrow: 'FACE ANALYSIS', title: 'Vollständigen Brillenbericht freischalten',
      description: 'Erhalte vollständige Empfehlungen, Styling-Hinweise und 30 nicht verfallende Credits zum Anprobieren deiner Fassungen.',
      packTitle: (count) => `Vollständiger Bericht + ${count} Credits`,
      benefits: ['Vollständigen Face-Analysis-Bericht freischalten', 'Personalisierte Fassungs-Empfehlungen sehen', 'Empfohlene Fassungen und weitere Styles testen', 'Ungenutzte Credits verfallen nicht'],
      continueLabel: (price) => `Für ${price} freischalten`,
      successTitle: 'Bericht freigeschaltet',
    },
  },
  ja: {
    try_on: {
      eyebrow: 'バーチャル試着', title: '試着を続ける',
      description: 'クレジットを追加して、サブスクリプションなしで続きから再開できます。',
      packTitle: (count) => `${count} Decision Credits`,
      benefits: ['バーチャル試着を続ける', 'VisuTry 全体で利用可能', 'クレジットは失効しません', 'サブスクリプション不要'],
      continueLabel: (price) => `${price} で続ける`,
    },
    frame_compare: {
      eyebrow: 'フレーム比較', title: '比較を仕上げて、さらに探す',
      description: '今の比較を完成させたあと、さらに多くのフレームやスタイルを試せます。未使用クレジットは失効しません。',
      packTitle: (count) => `${count} Decision Credits`,
      benefits: ['フレーム比較を完成させる', 'さらに多くのフレームを試す', 'さまざまなStyleを探す', '未使用クレジットは失効しません'],
      continueLabel: (price) => `${price} で続ける`,
    },
    style_explorer: {
      eyebrow: 'STYLE EXPLORER', title: '4つの新しいルックを試して、さらに自分のスタイルを探す',
      description: '選んだ4つのルックを作成したあと、メガネやサングラス、新しいスタイルの方向性をさらに探せます。',
      packTitle: (count) => `${count} Decision Credits`,
      benefits: ['次の4つのStyleルックを作る', 'メガネとサングラスを探す', 'いつでも別のスタイルを試す', '未使用クレジットは失効しません'],
      continueLabel: (price) => `${price} で続ける`,
    },
    face_analysis_top_picks: {
      eyebrow: 'おすすめ TOP PICKS', title: 'おすすめフレームを試して、さらに探す',
      description: 'Face Analysis のおすすめ4本から始めて、その後さらに多くのフレームやスタイルを比較できます。',
      packTitle: (count) => `${count} Decision Credits`,
      benefits: ['おすすめ4本を試す', 'さらに多くのフレームを比較する', 'さまざまなStyleを探す', '未使用クレジットは失効しません'],
      continueLabel: (price) => `${price} で続ける`,
    },
    face_analysis_unlock: {
      eyebrow: 'FACE ANALYSIS', title: 'アイウェアの完全レポートを解除',
      description: '完全なおすすめ、スタイリングガイド、そして見つけたフレームを試せる失効しない30クレジットを受け取れます。',
      packTitle: (count) => `完全レポート + ${count} Decision Credits`,
      benefits: ['Face Analysis の完全レポートを解除', 'パーソナライズされたおすすめを見る', 'おすすめフレームや別のStyleを試す', '未使用クレジットは失効しません'],
      continueLabel: (price) => `${price} で解除`,
      successTitle: 'レポートを解除しました',
    },
  },
  es: {
    try_on: {
      eyebrow: 'PRUEBA VIRTUAL', title: 'Seguir probando',
      description: 'Añade créditos y continúa donde lo dejaste sin elegir una suscripción.',
      packTitle: (count) => `${count} créditos de decisión`,
      benefits: ['Continuar la prueba virtual', 'Usar en todo VisuTry', 'Los créditos no caducan', 'Sin suscripción'],
      continueLabel: (price) => `Continuar por ${price}`,
    },
    frame_compare: {
      eyebrow: 'COMPARAR MONTURAS', title: 'Termina la comparación — y sigue explorando',
      description: 'Completa tu comparación actual y después prueba más monturas y estilos. Los créditos no utilizados no caducan.',
      packTitle: (count) => `${count} créditos de decisión`,
      benefits: ['Completar la comparación', 'Probar más monturas', 'Explorar diferentes estilos', 'Los créditos no caducan'],
      continueLabel: (price) => `Continuar por ${price}`,
    },
    style_explorer: {
      eyebrow: 'STYLE EXPLORER', title: 'Explora 4 looks nuevos — y sigue descubriendo tu estilo',
      description: 'Crea tus cuatro looks elegidos y después explora monturas ópticas, gafas de sol y nuevas direcciones de estilo.',
      packTitle: (count) => `${count} créditos de decisión`,
      benefits: ['Crear tus próximos 4 looks', 'Explorar monturas ópticas y gafas de sol', 'Probar más estilos cuando quieras', 'Los créditos no caducan'],
      continueLabel: (price) => `Continuar por ${price}`,
    },
    face_analysis_top_picks: {
      eyebrow: 'TUS TOP PICKS', title: 'Prueba tus monturas recomendadas — y sigue explorando',
      description: 'Empieza con tus 4 Top Picks de Face Analysis y después compara más monturas y estilos.',
      packTitle: (count) => `${count} créditos de decisión`,
      benefits: ['Probar tus 4 monturas recomendadas', 'Comparar más monturas', 'Explorar diferentes estilos', 'Los créditos no caducan'],
      continueLabel: (price) => `Continuar por ${price}`,
    },
    face_analysis_unlock: {
      eyebrow: 'FACE ANALYSIS', title: 'Desbloquea tu informe completo de gafas',
      description: 'Obtén recomendaciones completas, guía de estilo y 30 créditos que no caducan para probar las monturas que descubras.',
      packTitle: (count) => `Informe completo + ${count} créditos`,
      benefits: ['Desbloquear el informe completo', 'Ver recomendaciones personalizadas', 'Probar monturas recomendadas y más estilos', 'Los créditos no caducan'],
      continueLabel: (price) => `Desbloquear por ${price}`,
      successTitle: 'Informe desbloqueado',
    },
  },
  pt: {
    try_on: {
      eyebrow: 'PROVA VIRTUAL', title: 'Continue experimentando',
      description: 'Adicione créditos e continue de onde parou sem assinatura.',
      packTitle: (count) => `${count} créditos de decisão`,
      benefits: ['Continuar a prova virtual', 'Usar em todo o VisuTry', 'Créditos não expiram', 'Sem assinatura'],
      continueLabel: (price) => `Continuar por ${price}`,
    },
    frame_compare: {
      eyebrow: 'COMPARAR ARMAÇÕES', title: 'Conclua a comparação — e continue explorando',
      description: 'Conclua a comparação atual e depois experimente mais armações e estilos. Créditos não utilizados não expiram.',
      packTitle: (count) => `${count} créditos de decisão`,
      benefits: ['Concluir a comparação', 'Experimentar mais armações', 'Explorar estilos diferentes', 'Créditos não expiram'],
      continueLabel: (price) => `Continuar por ${price}`,
    },
    style_explorer: {
      eyebrow: 'STYLE EXPLORER', title: 'Explore 4 novos looks — e continue descobrindo seu estilo',
      description: 'Crie quatro looks selecionados e depois explore armações ópticas, óculos de sol e novas direções de estilo.',
      packTitle: (count) => `${count} créditos de decisão`,
      benefits: ['Criar seus próximos 4 looks', 'Explorar armações e óculos de sol', 'Experimentar mais estilos quando quiser', 'Créditos não expiram'],
      continueLabel: (price) => `Continuar por ${price}`,
    },
    face_analysis_top_picks: {
      eyebrow: 'SEUS TOP PICKS', title: 'Experimente as armações recomendadas — e continue explorando',
      description: 'Comece com os 4 Top Picks do Face Analysis e depois compare mais armações e estilos.',
      packTitle: (count) => `${count} créditos de decisão`,
      benefits: ['Experimentar as 4 armações recomendadas', 'Comparar mais armações', 'Explorar estilos diferentes', 'Créditos não expiram'],
      continueLabel: (price) => `Continuar por ${price}`,
    },
    face_analysis_unlock: {
      eyebrow: 'FACE ANALYSIS', title: 'Desbloqueie seu relatório completo de óculos',
      description: 'Receba recomendações completas, orientação de estilo e 30 créditos sem validade para experimentar as armações que descobrir.',
      packTitle: (count) => `Relatório completo + ${count} créditos`,
      benefits: ['Desbloquear o relatório completo', 'Ver recomendações personalizadas', 'Experimentar armações recomendadas e outros estilos', 'Créditos não expiram'],
      continueLabel: (price) => `Desbloquear por ${price}`,
      successTitle: 'Relatório desbloqueado',
    },
  },
  fr: {
    try_on: {
      eyebrow: 'ESSAYAGE VIRTUEL', title: 'Continuer les essayages',
      description: 'Ajoutez des crédits et reprenez là où vous vous êtes arrêté, sans abonnement.',
      packTitle: (count) => `${count} crédits de décision`,
      benefits: ['Continuer l’essayage virtuel', 'Utiliser dans tout VisuTry', 'Les crédits n’expirent pas', 'Sans abonnement'],
      continueLabel: (price) => `Continuer pour ${price}`,
    },
    frame_compare: {
      eyebrow: 'COMPARER LES MONTURES', title: 'Terminez la comparaison — puis continuez à explorer',
      description: 'Terminez votre comparaison actuelle, puis essayez davantage de montures et de styles. Les crédits inutilisés n’expirent pas.',
      packTitle: (count) => `${count} crédits de décision`,
      benefits: ['Terminer la comparaison', 'Essayer plus de montures', 'Explorer différents styles', 'Les crédits n’expirent pas'],
      continueLabel: (price) => `Continuer pour ${price}`,
    },
    style_explorer: {
      eyebrow: 'STYLE EXPLORER', title: 'Explorez 4 nouveaux looks — et continuez à découvrir votre style',
      description: 'Créez vos quatre looks sélectionnés, puis explorez des montures optiques, des lunettes de soleil et de nouvelles directions de style.',
      packTitle: (count) => `${count} crédits de décision`,
      benefits: ['Créer vos 4 prochains looks', 'Explorer montures optiques et solaires', 'Essayer plus de styles quand vous le souhaitez', 'Les crédits n’expirent pas'],
      continueLabel: (price) => `Continuer pour ${price}`,
    },
    face_analysis_top_picks: {
      eyebrow: 'VOS TOP PICKS', title: 'Essayez vos montures recommandées — puis explorez davantage',
      description: 'Commencez avec vos 4 Top Picks de Face Analysis, puis comparez davantage de montures et de styles.',
      packTitle: (count) => `${count} crédits de décision`,
      benefits: ['Essayer vos 4 montures recommandées', 'Comparer davantage de montures', 'Explorer différents styles', 'Les crédits n’expirent pas'],
      continueLabel: (price) => `Continuer pour ${price}`,
    },
    face_analysis_unlock: {
      eyebrow: 'FACE ANALYSIS', title: 'Débloquez votre rapport lunettes complet',
      description: 'Obtenez vos recommandations complètes, vos conseils de style et 30 crédits sans expiration pour essayer les montures découvertes.',
      packTitle: (count) => `Rapport complet + ${count} crédits`,
      benefits: ['Débloquer le rapport Face Analysis complet', 'Voir les recommandations personnalisées', 'Essayer les montures recommandées et d’autres styles', 'Les crédits n’expirent pas'],
      continueLabel: (price) => `Débloquer pour ${price}`,
      successTitle: 'Rapport débloqué',
    },
  },
}

const SHORTFALL_COPY: Record<string, (needed: number, required: number, current: number) => string> = {
  en: (needed, required, current) => `You’re ${needed} credit${needed === 1 ? '' : 's'} short. This step needs ${required}; you have ${current}.`,
  id: (needed, required, current) => `Anda membutuhkan ${needed} kredit lagi. Langkah ini memerlukan ${required}; Anda memiliki ${current}.`,
  ar: (needed, required, current) => `تحتاج إلى ${needed} رصيد إضافي. هذه الخطوة تتطلب ${required} ولديك ${current}.`,
  ru: (needed, required, current) => `Нужно ещё ${needed} кредитов. Для этого шага требуется ${required}, у вас ${current}.`,
  de: (needed, required, current) => `Dir fehlen ${needed} Credits. Für diesen Schritt brauchst du ${required}; du hast ${current}.`,
  ja: (needed, required, current) => `あと${needed}クレジット必要です。このステップには${required}クレジット必要で、現在${current}クレジットあります。`,
  es: (needed, required, current) => `Te faltan ${needed} créditos. Este paso necesita ${required}; tienes ${current}.`,
  pt: (needed, required, current) => `Faltam ${needed} créditos. Esta etapa precisa de ${required}; você tem ${current}.`,
  fr: (needed, required, current) => `Il vous manque ${needed} crédits. Cette étape en demande ${required} ; vous en avez ${current}.`,
}

export function getPaywallCopy(locale: string, context: ConversionPurchaseContext): PaywallCopy {
  return {
    ...EN_COPY[context],
    ...(LOCALIZED_COMMON[locale] || {}),
    ...(LOCALIZED_CONTEXT_COPY[locale]?.[context] || {}),
  }
}

export function getShortfallCopy(locale: string, needed: number, required: number, current: number) {
  return (SHORTFALL_COPY[locale] || SHORTFALL_COPY.en)(needed, required, current)
}

export function isRtlLocale(locale: string) {
  return locale === 'ar'
}
